### ISSUE TITLE
Slow startup with custom ConfigurationProperties

### ISSUE THREAD

**Issue by nkolosnjaji** [spring-projects/spring-boot#10093]
Version: Spring Boot 2.0.0.M3

In project where custom and type-safe ConfigurationProperties are used, application is starting very slowly. Last property is `Map<String, List<String>>`

Changing Spring Boot version to 1.5.6.RELEASE will start application under 1 second, where with version 2.0.0.Mx will take 5+ seconds or even more, depending on number of entries in application.yml

example of application.yml:
```
test:
  environments:
    dev:
      containers:
        xyz:      
        - entry1
        .....
        - entry70
```

Repro project:
See https://github.com/spring-projects/spring-boot-issues/pull/70
