### ISSUE TITLE
List of dynamic values don't support list

### ISSUE THREAD

**Issue by zoeminghong** [spring-projects/spring-boot#10607]
```yaml
  gateway:
      apps:
        user: ["xxxxxxx","bbbbb"]
        product: ["YYYYYYY","cccccc"]
```
When using the top writing format, there is a [neither an array nor a List nor a Map;] problem using the list accepted value. The user and product are dynamic keys.

**Comment by philwebb** [comment]
Please try the latest 2.0 milestone. If that doesn't work could you please provide a sample that shows what you mean.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by zoeminghong** [comment]
`application.yml`
```yaml
csp:
  basic:
    demo1: ["Test1","Test2"]
    demo2: ["Test3"]
```
```java
@Configuration
@ConfigurationProperties("csp")
public class PropConfig {

    Map<String ,List<String>> csp;

    public Map<String, List<String>> getCsp() {
        return csp;
    }

    public void setCsp(Map<String, List<String>> csp) {
        this.csp = csp;
    }
}
```
I'm so sorry. I was busying lately
This Map variable can't use List to set ["Test1","Test2"].
