### ISSUE TITLE
2.0.0.M5 trouble with application.yml

### ISSUE THREAD

**Issue by maystrovyy** [spring-projects/spring-boot#10627]
Does any have the same problems with yml config?
`Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 12, column 1:
    spring:
    ^
`
`expected <block end>, but found BlockMappingStart
 in 'reader', line 15, column 2:
     jpa:`
Notice: I just update spring boot ver, without any properties changing.

**Comment by bclozel** [comment]
Could you paste here the corresponding `application.yml`?

**Comment by maystrovyy** [comment]
```
server:
  port: 8080
  compression:
      enabled: true
  servlet:
    context-path: /name
#
management:
  port: 8090
  context-path: /name/management

spring:
  profiles:
    active: dev
 jpa:
   show-sql: true
   hibernate:
     ddl-auto: create-drop
   properties:
     hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
     hibernate.format_sql: false
     hibernate.cache.use_second_level_cache: false
     hibernate.cache.use_query_cache: false
     hibernate.generate_statistics: false
 datasource:
   hikari:
     jdbc-url: jdbc:mysql://localhost:32768/name?autoReconnect=true&useSSL=false
     username: root
     password: 12345
     connection-timeout: 30000
     maximum-pool-size: 3
     minimum-idle: 1
     max-lifetime: 600000
#
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.data.jpa.repository.JpaRepository: debug
```
