### ISSUE TITLE
Consider defaulting provider to the registration-id

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#10671]
It would be nice if users could avoid having to configure the provider-id for OAuth2 client registrations. Since client registrations are often a 1 to 1 mapping to the provider, this could be done by trying to use the client id for the provider id. This would change the configuration from this:

```yml
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: some-id-for-google
            client-secret: some-secret-for-google
```

to

```yml
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: some-id-for-google
            client-secret: some-secret-for-google
```
