### ISSUE TITLE
spring boot redis?

### ISSUE THREAD

**Issue by javaChain** [spring-projects/spring-boot#10776]
springboot version : 1.4.5
application.yml redis properties diffirent from JedisConnectionFactory properties!

application.yml:
```
spring:
  redis:
    host: 10.2.96.163 
    port: 6379
    database: 0
    password:
#max idle connection
    pool: 
      max-idle: 10
#min idle connection
      min-idle: 0
#max connection
      max-active: 100
#max wait time
      max-wait: -1
```

JedisConnectionFactory:
```	private JedisShardInfo shardInfo;
	private String hostName = "localhost";
	private int port = Protocol.DEFAULT_PORT;
	private int timeout = Protocol.DEFAULT_TIMEOUT;
	private String password;
	private boolean usePool = true;
	private Pool<Jedis> pool;
	private JedisPoolConfig poolConfig = new JedisPoolConfig();
	private int dbIndex = 0;
	private boolean convertPipelineAndTxResults = true;
	private RedisSentinelConfiguration sentinelConfig;
	private RedisClusterConfiguration clusterConfig;
	private JedisCluster cluster;
	private ClusterCommandExecutor clusterCommandExecutor;
```

so,i modify application.yml,what can i do for this,can you help me ?
[pic1](https://ws4.sinaimg.cn/large/006tNc79gy1fkvgqv5jztj30fb0dmwez.jpg)
[pic2](https://ws3.sinaimg.cn/large/006tNc79gy1fkvgr19ezzj30a7061glf.jpg)

```
    @Bean
    @ConfigurationProperties(prefix = "spring.redis.poolConfig")
    public JedisPoolConfig getRedisConfig() {
        JedisPoolConfig config = new JedisPoolConfig();
        return config;
    }

    @Bean
    @ConfigurationProperties(prefix = "spring.redis")
    public JedisConnectionFactory getConnectionFactory() {
        JedisConnectionFactory factory = new JedisConnectionFactory();
        factory.setUsePool(true);
        JedisPoolConfig config = getRedisConfig();
        factory.setPoolConfig(config);
        return factory;
    }
```
