### ISSUE TITLE
OAuth2ClientPropertiesRegistrationAdapter not copying provider.userNameAttribute property

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-boot#11243]
Given the following configuration:

```
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: client-id
            client-secret: secret
        provider:
          okta:
            authorization-uri: https://dev-12345.oktapreview.com/oauth2/v1/authorize
            token-uri: https://dev-12345.oktapreview.com/oauth2/v1/token
            user-info-uri: https://dev-12345.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: https://dev-12345.oktapreview.com/oauth2/v1/keys

```

The client property `...provider.user-name-attribute` is not being copied to `ClientRegistration.ProviderDetails.UserInfoEndpoint.userNameAttributeName`.

The solution is to add the following line of code to [OAuth2ClientPropertiesRegistrationAdapter L99](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/client/OAuth2ClientPropertiesRegistrationAdapter.java#L99)

`copyIfNotNull(provider::getUserNameAttribute, builder::userNameAttributeName);`

/cc @mraible
