### ISSUE TITLE
Setting max file size for upload when running on Tomcat

### ISSUE THREAD

**Issue by fredrikwithpettersen** [spring-projects/spring-boot#11284]
Hello

Spring Boot 2.0.0.M7

When I try to upload a MultipartFile I get:
`java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.FileUploadBase$FileSizeLimitExceededException: The field files exceeds its maximum permitted size of 1048576 bytes.`

I have tried the following in application.yaml:
```
spring:
    servlet:
        multipart:
            max-file-size: 10240MB
            max-request-size: 10240MB
```

I have also tried on the controller:
```
@RestController
@RequestMapping(path = "/api/files")
@MultipartConfig(maxFileSize = 10737418240L, maxRequestSize = 10737418240L, fileSizeThreshold = 52428800)
public class FilesController {
...
}
```

None of these are working when im running a local Tomcat. 

Before I upgraded to Spring Boot 2.0.0.M7 I used the CommonsMultipartResolver (where this worked) but after upgrading I noticed that the, for some reason, DispatcherServlet took a long time processing the request. Therefore I have started using the standard Spring Boot implementation of the MultipartResolver.
