### ISSUE TITLE
Actuator CORS Support Does Not Work with Webflux

### ISSUE THREAD

**Issue by SingleShot** [spring-projects/spring-boot#11308]
CORS for Actuator endpoints does not appear to work when running Spring Boot `2.0.0.M7` and `spring-boot-starter-webflux` on Netty. 

My CORS configuration is this:
```
management:
  endpoints:
    web:
      base-path: /
      cors:
        allowed-methods: GET
        allowed-origins: http://localhost:4200
```

Hitting the `/info` endpoint with a command line client, regardless of the `Origin` header, always yields `200`. However, hitting the same endpoint from my Angular app running on `localhost:4200` always fails with a missing CORS header (I suppose Angular uses CORS by default).

If I add `spring-boot-starter-web` to my POM, the CORS configuration for Actuator works as expected in all aspects. However, doing this switches the web server from Tomcat to Netty.

Perhaps this is expected? My expectation would be I do not need to add `spring-boot-starter-web` to enable CORS support for Actuator and I can continue to run on Netty.
