### ISSUE TITLE
Cannot parse redis password with a colon

### ISSUE THREAD

**Issue by renpwhappy** [spring-projects/spring-boot#11371]
Hello, I use spring boot version is 1.5.7.RELEASE. And if there is a colon in redis password, RedisAutoConfiguration get a error redis password. I'm not sure if this is a bug. redis properties in 
application.yml like this:
```
    spring:
        redis:
            url: redis://:crs-7629154:aucyr7632@localhost:6379
            database: 0
            timeout: 1000
```
redis password is crs-7629154:aucyr7632.
