### ISSUE TITLE
SpringBoot2 ConfigurationProperties removes colon from yaml keys

### ISSUE THREAD

**Issue by balajeetm** [spring-projects/spring-boot#11386]
Until SpringBoot 1.5.9
I was using the application yaml to define a namespaced id with few properties.
eg.
```yaml
app:
    ids:
      "urn:test:id:12-34" :
        roles:
          - CREATE
          - ALLOW_ALL
      "urn:test:id:23-41" :
        roles:
          - DELETE
          - ALLOW_ALL
```

This was being read in as a Map
```java
@ConfigurationProperties(prefix = "app")
@Data
@Component
public class IdProps {
  @Data
  public static class IdProps {
    private Map<String, Id> ids = new HashMap<>();
  }

  @Data
  public static class Id {
    private List<String> roles = new ArrayList<>();;
  }
}
```

The expectation was that this worked in SpringBoot2.

However, the Map keys in SPringBoot2 were as below
"urntestid12-34" -> "IdProps.Id(roles=[CREATE, ALLOW_ALL])"

Expected behavior
"urn:test:id:12-34" -> "IdProps.Id(roles=[CREATE, ALLOW_ALL])"
