### ISSUE TITLE
Filter logs coming from a specific package

### ISSUE THREAD

**Issue by JackLehman** [spring-projects/spring-boot#11413]
In application.yml, I have the following code:
```
logging:
  file: test.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
```

I would like to ask for a feature which may not exit. I would to filter and gather all log messages of all levels (ERROR, DEBUG, INFO, etc) from only one specific package (org.hibernate). It is possible?
