### ISSUE TITLE
Unable to find Liquibase migration files

### ISSUE THREAD

**Issue by gianpaolodn** [spring-projects/spring-boot#11615]
Hi,

i've got a weird issue with spring-boot m7 and liquibase 3.5.3

Liquibase change-log file is in the default path

```
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
```

During the boot spring reads correctly the file.
Inside I have this infos:

```
databaseChangeLog:
  - includeAll:
    - path: db/changelog/changes
```

Suddenly, if the project runs inside eclipse everything works fine, the migration files are loaded and db populated, but if i run this from the console or from the dockerized image, these files are not found and the database is not populated. 

So I tried several configs:

```
databaseChangeLog:
  - includeAll:
    - path: classpath:db/changelog/changes
```

```
databaseChangeLog:
  - includeAll:
    - path: changes
    - relativeToChangelogFile: true
```

No one works outside eclipse.

Everything works if I use `include` instead of `includeAll`

```
databaseChangeLog:
  - include:
    - file: changes/v0001-init.sql
    - relativeToChangelogFile: true
  - include:
    - file: changes/v0002-questions.sql
    - relativeToChangelogFile: true
```
When i test the jar I run this command (I guess docker does the same):

`java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=development -Dspring.datasource.username=devel -Dspring.datasource.password=devel -Dspring.datasource.url=jdbc:postgresql://localhost:5433/db -jar build.jar`
