### ISSUE TITLE
Cannot create 2 DataSources when upgrading to version 1.1.2

### ISSUE THREAD

**Issue by adriffaud** [spring-projects/spring-boot#1166]
Hi,

When upgrading a batch application with two datasources from 1.1.1 to 1.1.2, application startup fail with a **_BeanCurrentlyInCreationException**_

```
Error creating bean with name 'dataSourceAutoConfigurationInitializer':
Requested bean is currently in creation:
Is there an unresolvable circular reference ?
```

The two datasources are defined in application.yml as follow :

```
datasource:
  batch:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/batch
    username: user
    password: pass
  app:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/app
    username: user
    password: pass
```

and used by beans :

```
@Configuration
public class Datasources {

    @Bean
    @Primary
    @ConfigurationProperties(prefix = "datasource.batch")
    public DataSource batchDataSource() {
        return DataSourceBuilder.create().build();
    }

    @Bean(name = "dsApp")
    @ConfigurationProperties(prefix = "datasource.app")
    public DataSource appDataSource() {
        return DataSourceBuilder.create().build();
    }

    @Bean
    public JdbcTemplate jdbcTemplate() {
        return new JdbcTemplate(exdatDataSource());
    }
}
```

Setup is STS on Linux x64 with Java 8
