### ISSUE TITLE
redis sentinel default configuration broken

### ISSUE THREAD

**Issue by zil** [spring-projects/spring-boot#11855]
https://github.com/spring-projects/spring-boot/blob/d478e9bf57b73ca84539c0e9bfa82961256e50d9/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/JedisConnectionConfiguration.java#L88

https://github.com/spring-projects/spring-data-redis/blob/2fe048bfff856012f42aed9f702334bc5b7d28fd/src/main/java/org/springframework/data/redis/connection/jedis/JedisConnectionFactory.java#L275

Using springBoot with version `2.0.0.M6` and `redis.clients:jedis:2.9.0`,with config:
```yml
spring:
  redis:
    sentinel:
      nodes: 0.0.0.0:26379,0.0.0.0:26479,0.0.0.0:26579
      master: mymaster
```

But Spring Boot not use sentinel config,but resolve to `localhost:6379`.By debugging I found the above code is the cause: **If the pool configuration is leave out,Spring Boot will resolve to `localhost:6379`**
