### ISSUE TITLE
HibernateJpaConfiguration is explicitly making a call to datasource for metadata, and not respecting properties configured in application.yml

### ISSUE THREAD

**Issue by varunmehta** [spring-projects/spring-boot#12374]
When the application starts, since we are using an ```AbstractRoutingDataSource``` and want to lazy everything on the datasource, we don't want hibernate to make any ```DataSource``` metadata related calls. In order to avoid it, we have provided all possible properties for ddl and database type. 

```
spring:
  jpa:
    generate-ddl: false    
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
```
This works great in spring-boot 1.5.9. On upgrading to spring-boot 2.0, it fails, due to ```HibernateDefaultDdlAutoProvider```, making an explicit call to check if the datasource is embedded or not. 

It is not respecting any of the properties defined to  ```setDefaulyDdlAuto```. Instead of fetching the ```DataSource``` and making an explicit call, it should pick the property as specified in the configuration file.

```
public String getDefaultDdlAuto(DataSource dataSource) {
  if (!EmbeddedDatabaseConnection.isEmbedded(dataSource)) {
    return "none";
  }
  SchemaManagement schemaManagement = getSchemaManagement(dataSource);
  if (SchemaManagement.MANAGED.equals(schemaManagement)) {
    return "none";
  }
  return "create-drop";
}
``` 

This call should not happen if the properties have been already specified, in application.yml

```
/**
 * {@link ConnectionCallback} to determine if a connection is embedded.
 */
private static class IsEmbedded implements ConnectionCallback<Boolean> {

  @Override
  public Boolean doInConnection(Connection connection)
      throws SQLException, DataAccessException {
    String productName = connection.getMetaData().getDatabaseProductName();
    if (productName == null) {
      return false;
    }
    productName = productName.toUpperCase(Locale.ENGLISH);
    EmbeddedDatabaseConnection[] candidates = EmbeddedDatabaseConnection.values();
    for (EmbeddedDatabaseConnection candidate : candidates) {
      if (candidate != NONE && productName.contains(candidate.name())) {
        return true;
      }
    }
    return false;
  }
}
```
