### ISSUE TITLE
oauth2 scope for facebook doesn't work

### ISSUE THREAD

**Issue by jjangga0214** [spring-projects/spring-boot#12429]
I am using spring boot 2.0.0 and spring-boot-starter-security (without explicit version thanks to bom).
Even though I set 
`spring.security.oauth2.client.registration.facebook.scope=public_profile,email`
, only just `name` and `id` are accessible. I wonder if this is due to a bug, or change of facebook policy or if there is an another recommendable way rather than specifying `scope` in `application.yml` in order to get other information, such as `email` and `public_profile`. 

```
spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: foo
            client-secret: bar
            scope: public_profile,email
```
