### ISSUE TITLE
Error loading template configured in an external directory

### ISSUE THREAD

**Issue by MSMTFaro** [spring-projects/spring-boot#12481]
While migrating to Spring Boot 2, the Freemarker templateLoaderPath configuration does not work when you specify a custom path outside the application.

```yaml
spring:
  freemarker:
    template-loader-path: file:./../dist
    suffix: .html
```

This same configuration worked in Spring Boot 1.5.9 but it seems something must have broken in either Spring Boot 2 or Spring MVC 5. 

Using a Thymeleaf resolver to load external files does not work either.
