### ISSUE TITLE
logging configuration not support yaml

### ISSUE THREAD

**Issue by hsoftxl** [spring-projects/spring-boot#12522]
logging.file=logs/app.log
logging.file.max-history=20
logging.file.max-size=50MB

these can not set in yaml file

```
logging:
  file:
    max-history: 20
    max-size: 50MB

logging.file can not be set
```
