### ISSUE TITLE
Cookie http-only setting has no effect when using embedded Tomcat

### ISSUE THREAD

**Issue by maku** [spring-projects/spring-boot#12580]
I am using spring boot 2.0.0.RELEASE

When I set the http-only flag to false it has no effect on the browser. I am able to inspect the session cookie in the browser -> I see the http flag is enabled. And therefore I am not able to access the cookie via javascript...

Here is the definition part in my application.yaml

```
server:
  servlet:
    session:
      cookie:
        max-age: 30m
        name: my_app_session
        http-only: false
        secure: false
      timeout: 30m
```

The reason why I do this is: I have an SPA where I would like to check the session cookie periodically to 
figure out when the session is expired (to present a certain view to the user)
