### ISSUE TITLE
logging configuration in Yaml file

### ISSUE THREAD

**Issue by yukatan** [spring-projects/spring-boot#1265]
I'm trying to configure my spring boot application with a yaml 'application.yml' file. Everything works perfect except  for the logging level configuration.

I've tried this : 

``` yaml

logging:
    file: /var/log/security.log
    level:
        org.springframework: OFF
```

and this : 

``` yaml

logging:
    file: /var/log/security.log
    level.org.springframework: OFF
```

and thousand of posibilities and nothing works.

is it a bug or maybe I'm doing something wrong???

Thanks
