### ISSUE TITLE
Setting up ssl connection with trust-store on Tomcat 8.

### ISSUE THREAD

**Issue by sh1nen** [spring-projects/spring-boot#12830]
Hey, I'm trying to make **https** calls with RestTemplate, I'm using Spring Boot 1.3.6 with embedded Tomcat. I have signed up certificate which I imported as trusted to my keystore.jks and exposed via application.yml as follows:
```
server:
  port: 8080
  contextPath: /backend
    ssl:
      enabled: true
      key-store: path-to-keystore
      key-store-password: password
      trust-store: path-to-keystore
      trust-store-password: password
```

I also added to my Dockerfile as an entrypoint :

`java -Djavax.net.debug=ssl -Djavax.net.ssl.trustStore=path-to-truststore  -Djavax.net.ssl.trustStorePassword=my-secret-password  -jar app.jar `

The only thing I'm getting right know when Rest call is fired is a following exception:
`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

Is there any workaround  ? It seems that application just can't pick up the certificate for http call to external service. I've read a lot issues with with trust-store configuration via application files and I'm running out of ideas how it could be done properly.
