### ISSUE TITLE
Empty YAML array does not override property from source with lower precedence

### ISSUE THREAD

**Issue by gautamceg** [spring-projects/spring-boot#12965]
SpringBoot version - 1.5.10.RELEASE
I'm using Spring Centralized Configuration to store my application configuration and it works fine for single valued properties but for MultiValued properties remote config is not able to override local properties.

remote config file: test-cloud-config.yml

```yaml
test:
  empty:
    strKey: 
    listKey: []
```

SpringBoot resource local: application.yml

```yaml
test:
  empty:
    strKey: local str Key
    listKey: localOne, localTwo
```

My spring boot class:-

   

```java
@Component
public class TestRemoteConfig {
    
    @Value("${test.empty.strKey}")
    private String testEmptyStrKey;
    	
    @Value("${test.empty.listKey}")
    private String[] testEmptyListKey;
    	
    @PostConstruct
    public void init(){
        System.out.println("Test override EmptyStrKey's value :- "+ testEmptyStrKey);
        System.out.println("Test override EmptyListKey's value :- "+ Arrays.asList(testEmptyListKey));
    }

}
```

Output

```
Test override EmptyStrKey's value :- 
Test override EmptyListKey's value :- [localOne, localTwo]
```

but I expect 'testEmptyListKey' to be empty.

> Note: This works when I use .properties in place of .yml as config file

**Comment by wilkinsona** [comment]
Thanks for the report. I think this is a bug in Spring Framework's `YamlPropertiesFactoryBean`. When it's flattening the runtime representation of a YAML document into `Properties`, a collection that's empty is lost. You can avoid that behaviour by using an empty value instead of an empty array value:

```yaml
test:
  empty:
    strKey: 
    listKey:
```

I've opened [SPR-16769](https://jira.spring.io/browse/SPR-16769). If the Framework team agree with my assessment, we'll pick up a fix in due course. In the meantime, please use the alternative described above.

**Comment by gautamceg** [comment]
@wilkinsona - Thanks for the quick response and advice. However I can not use empty values because there are validation for property value in my project for cron sequence and the property is array of nested objects in actual
e.g 
```
test:
  empty: 
    listKey:
     -
       name: foo
       type: fooType
       schedule: "0 0-58/2 * * * *"
       param:
         type: fooPramType
         count: 100
```
please let me know if I can use other alternative in this case

**Comment by gautamceg** [comment]
sorry for confusion, my statement-  

> This works when I use .properties in place of .yml as config file
was for the very first example in this thread where I'm trying to show the sample situation  with scalers and I will use your advise to solve issue with scalers.(refer below example)
```
test:
  empty:
    strKey: local str Key
    listKey: localOne, localTwo
```
but the main issue is when I deal with nested Objects.. (refer below example)
```
test:
  empty: 
    listKey:
     -
       name: foo
       type: fooType
       schedule: "0 0-58/2 * * * *"
       param:
         type: fooPramType
         count: 100
```
