### ISSUE TITLE
Add AutoConfiguration support for OIDC Configuration Provider

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#13210]
Spring Boot should add auto configuration support `OidcConfigurationProvider`. This will allow simplifying how an OAuth Provider is configured. For example, right now a user must create the following configuration:

```yml
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
        provider:
          okta:
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
```

By leveraging `OidcConfigurationProvider` the configuration should be able to be simplified to something like this:

```yml
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
        provider:
          okta:
            issuer: https://dev-123456.oktapreview.com/oauth2/default/
```

Then Spring Boot's Auto Configuration support can can create a `ClientRegistration` using:

```java
ClientRegistration okta = OidcConfigurationProvider.issuer(issuer)
    .clientId(clientId)
    .clientSecret(clientSecret)
    .build();
```

This should be done for Servlet environments and WebFlux based environments along with #13142

Related: https://github.com/spring-projects/spring-security/issues/4413

NOTE: You can refer to [OidcConfigurationProviderTests](https://github.com/spring-projects/spring-security/blob/master/config/src/test/java/org/springframework/security/config/oauth2/client/oidc/OidcConfigurationProviderTests.java) for sample output of the URL and how to write a test using `MockWebServer`. You can also use Google's Issuer https://accounts.google.com/ which will request https://accounts.google.com/.well-known/openid-configuration for a simple way of integration testing a sample application.
