### ISSUE TITLE
Add save save_build_info: true to maven sync job

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#13223]
Discovered when working on the Java Format pipeline. We'll need:

```
- name: sync-to-maven-central
  serial: true
  plan:
  - get: spring-boot-ci-image
  - get: git-repo
    trigger: true
  - get: artifactory-repo
    trigger: false
    passed: [promote-release]
    params:
      save_build_info: true
  - task: sync-to-maven-central
    image: spring-boot-ci-image
    file: git-repo/ci/tasks/sync-to-maven-central.yml
    params:
      BINTRAY_USERNAME: ((bintray-username))
      BINTRAY_PASSWORD: ((bintray-password))
      SONATYPE_USERNAME: ((sonatype-username))
      SONATYPE_PASSWORD: ((sonatype-password))
      BINTRAY_SUBJECT: ((bintray-subject))
      BINTRAY_REPO: ((bintray-repo))
```
