### ISSUE TITLE
Spring Boot 2 Actuator health endpoint does not work when other endpoints are enabled

### ISSUE THREAD

**Issue by sshogunn** [spring-projects/spring-boot#13503]
### **Configuration setup**
build.gradle

```
buildscript {
    ext {
        springBootVersion = '2.0.0.RELEASE'
    }
    ...
}

plugins {
    id "org.sonarqube" version "2.6.1"
}

...

dependencies {
    ext {
        spockVersion = '1.1-groovy-2.4'
        swaggerVersion = '2.8.0'
        mockServerVersion = '2.5.1'
    }

    def withoutDefaultLogging = { exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging' }
    compile('org.springframework.boot:spring-boot-starter', withoutDefaultLogging)
    compile('org.springframework.boot:spring-boot-starter-actuator')
    compile('javax.xml.bind:jaxb-api:2.3.0')
    compile('org.springframework.boot:spring-boot-starter-data-jpa')
    compile('org.springframework.boot:spring-boot-starter-data-rest')
    compile('org.springframework.boot:spring-boot-starter-hateoas')
    compile('org.springframework.boot:spring-boot-starter-web')
    compile('org.springframework.cloud:spring-cloud-starter-openfeign:2.0.0.M2')

    //metrics
    runtime("io.micrometer:micrometer-registry-prometheus")

    ...
}
```

and my application.yaml has the following configs:

```
management:
  endpoints:
    web:
      exposure:
        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,heatlh
  health:
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true
```

### **Actual behavior:**

The endpoint /actuator/health returns 404 when I have management.endpoints.web.exposure.include=.
Once I remove it, /actuator/health becomes available again.

### **Expected behavior:**
The endpoint /actuator/health should be reachable even if added management.endpoints.web.exposure.include=.

**Comment by joshiste** [comment]
you have a typo in you config `management.endpoints.web.exposure.include`. You misspelled health!

changing to:
```
management:
  endpoints:
    web:
      exposure:
        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health
```
should help
