### ISSUE TITLE
Different profile precedence introduced in Spring Boot 2.0.2 & 2.0.3 when including profile through bootstrap.yml

### ISSUE THREAD

**Issue by vivekasingh** [spring-projects/spring-boot#13513]
Hi

I have observed that starting from spring boot 2.0.2,  its giving higher priority to included profiles over active profile.

I am aware about https://github.com/spring-projects/spring-boot/issues/13151 but that did not fix the issue I am running into.

I my case I have a bootstrap.yml file which pulls configurations from config server.  The bootstrap.yml file also defines "spring.profiles.include" to include profiles. To activate a profile I am passing "spring.profiles.active" as jvm startup argument.

I am attaching a sample project to demonstrate the issue, for simplicity I did not specify spring cloud config sever properties and reading both bootstrap.yml & application.yml from classpath.

1. bootstrap.yml:
```
spring:
  profiles:
    include: shared_features
  application:
    name: profiledemo
```
2. application.yml:
```
a_sample_key: global_feature_value

---
spring:
  profiles: shared_features

a_sample_key: shared_feature_value
---
spring:
  profiles: development

a_sample_key: dev_feature_value
```

I have used a command line runner to log this property on console and using `bootRun` which also set `-Dspring.profiles.active=development`.

With Spring boot 2.0.1 & Finchley.RC1:
`
a_sample_key: dev_feature_value  // Which is what I expect, its giving me the property from active profile
`

With Spring boot 2.0.3 & Finchley.RC2:
`
a_sample_key: shared_feature_value // Which is not correct, its returning me value from included profile
`

[profiledemo.zip](https://github.com/spring-projects/spring-boot/files/2112187/profiledemo.zip)
