### ISSUE TITLE
Add AutoConfiguration support for spring-security-oauth2-resource-server

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-boot#13787]
Spring Boot should add auto configuration support for `spring-security-oauth2-resource-server`. This will allow simplifying how an OAuth 2.0 Resource Server is configured.

For example, a user could configure a resource server in the following way:

```yaml
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: https://example.org/.well-known/jwks.json
```

Then, if `spring-security-oauth2-resource-server` is present on the classpath, as attested by the presence of `org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken`, Spring Boot's auto configuration support could configure a resource server in the following way:

```java
http
    .authorizeRequests()
        .anyRequest().authenticated()
        .and()
    .oauth2()
        .resourceServer()
            .jwt();
```

And then could expose an instance of `org.springframework.security.oauth2.jwt.NimbusJwtDecoderJwkSupport(jwkSetUri)`.
