### ISSUE TITLE
i upgrade springboot from 2.0.2 to 2.0.3, missing percentiles in metrics

### ISSUE THREAD

**Issue by dragontree101** [spring-projects/spring-boot#13794]
i only upgrade springboot from 2.0.2 to 2.0.3, missing percentiles in metrics
i am not change any properties, and only percentiles metrics not data, count and timer is ok.

![image](https://user-images.githubusercontent.com/1763935/42809836-17d07a04-89e9-11e8-9571-2cbfc9c0433e.png)

i found springboot 2.0.3 upgrade micrometer to 1.0.5, 
any changed in springboot 2.0.3 or micrometer 1.0.5?

thanks!

properties is below

```
management:
  metrics:
    export:
      influx:
        uri: http://10.10.3.61:8086
        step: 5s
        db: metrics
    web:
      server:
        auto-time-requests: true
        requests-metric-name: hn_http_requests
      client:
        max-uri-tags: 1000
    binders:
      logback:
        enabled: false
      uptime:
        enabled: false
      files:
        enabled: false
      integration:
        enabled: false
    enable:
      tomcat: false
    distribution:
      percentiles:
        hn_http_requests:
          - 0.5
          - 0.75
          - 0.9
          - 0.95
          - 0.99
      percentiles-histogram:
        hn_http_requests: true
  endpoints:
    web:
      exposure:
        include: metrics
```
