### ISSUE TITLE
IllegalStateException thrown when using Spring Kafka autoconfiguration

### ISSUE THREAD

**Issue by zoltanmagyar** [spring-projects/spring-boot#13949]
Spring Boot version: 2.0.3.RELEASE
Spring Kafka version: 2.1.7.RELEASE

I have the following producer config in a yaml file:
```
kafka:
    producer:
      ssl:
        truststore-location: ${SECRET_DIR}/truststore.jks
        truststore-password: ${TRUSTSTORE_PASSWORD}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: ${KAFKA_BROKER}:${KAFKA_PORT}
      transaction-id-prefix: tx-
      acks: all
      retries: 3
    template:
      default-topic: some-topic
    properties:
      security.protocol: SSL
```

When I start my spring boot app I get the following exception in the logs:
```
{"time":"2018-07-30T17:23:18.570+01:00","@version":1,"message":"Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.kafka.KafkaAnnotationDrivenConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.kafka.KafkaAnnotationDrivenConfiguration$$EnhancerBySpringCGLIB$$80a395ef]: Constructor threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'kafkaTemplate' defined in org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration: Unsatisfied dependency expressed through method 'kafkaTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaProducerFactory' defined in org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.kafka.core.ProducerFactory]: Factory method 'kafkaProducerFactory' threw exception; nested exception is java.lang.IllegalStateException: Resource 'class path resource [Users/zma01/projects/sportsbook/secrets/truststore.jks]' must be on a file system","logger_name":"org.springframework.context.annotation.AnnotationConfigApplicationContext","thread_name":"main","level":"WARN","level_value":30000}
```
The file in question definitely exists and the application boots fine if I have the equivalent config defined in a Java class.
