### ISSUE TITLE
Included profile property taking precedence over active profile property when using config server

### ISSUE THREAD

**Issue by vivekasingh** [spring-projects/spring-boot#13965]
Hi

This is related with my earlier issue [13513](https://github.com/spring-projects/spring-boot/issues/13513). I still see an issue when using spring cloud stack.

To demonstrate the issue, I am attaching a sample project which has embedded config server. This service pulls configurations from a github repository https://github.com/vivekasingh/profile_demo.

I am including a profile (spring.profiles.include) through bootstrap.yml file named "shared_features".  And activating a profile through command line by passing "spring.profiles.active" as jvm startup argument.

My application.yml file is into an external github repo, this config file have configurations for both of these profiles.

1. bootstrap.yml:
```
spring:
  application:
    name: profiledemo
  profiles:
    include: shared_features
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vivekasingh/profile_demo.git
        default-label: master
        bootstrap: true
```

2. application.yml (In https://github.com/vivekasingh/profile_demo pulled through config server):
```
a_sample_key: global_feature_value

---
spring:
  profiles: shared_features

a_sample_key: shared_feature_value
---
spring:
  profiles: development

a_sample_key: dev_feature_value
```

For this demonstration, I am using a command line runner to log "a_sample_key" property on console and using bootRun which also set -Dspring.profiles.active=development.

With Spring boot 2.0.1 & Finchley.RELEASE:
a_sample_key: dev_feature_value // Which is what I expect, its giving me the property from active profile

With Spring boot 2.0.4 & Finchley.RELEASE:
a_sample_key: shared_feature_value // Which is not correct, its returning me value from included profile

[profiledemo.zip](https://github.com/spring-projects/spring-boot/files/2246998/profiledemo.zip)
