### ISSUE TITLE
ServletEndpoint mapped incorrect with management.endpoints.web.base-path set to "/"

### ISSUE THREAD

**Issue by Schaka** [spring-projects/spring-boot#14042]
**Affected versions: 2.0.x (as far as I can tell)**

This is an issue that exists for all `@ServletEndpoint`s. Regular `@Endpoint`s are not affected as far as I can tell. I have noticed it occuring with Spring-Boot's autoconfigured JolokiaEndpoint.

Using the following YAML config, ServletEndpoints are not being mapped correctly by `ServletEndPointRegistrar`. 

```
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/"
  endpoint:
    health:
      show-details: ALWAYS
  server:
    port: 8082
```

Endpoints are being mapped to "//<endpointname>", because the base URL is concatenated with another slash. 

Problem in line 4 (line 64 ServletEndpointRegistratr.java):
```
private void register(ServletContext servletContext,
			ExposableServletEndpoint endpoint) {
		String name = endpoint.getId() + "-actuator-endpoint";
		String path = this.basePath + "/" + endpoint.getRootPath();
		String urlMapping = path.endsWith("/") ? path + "*" : path + "/*";
		EndpointServlet endpointServlet = endpoint.getEndpointServlet();
		Dynamic registration = servletContext.addServlet(name,
				endpointServlet.getServlet());
		registration.addMapping(urlMapping);
		registration.setInitParameters(endpointServlet.getInitParameters());
		logger.info("Registered '" + path + "' to " + name);
	}
```

I have not submitted a pull request, because I am unsure whether there is a more elegant way to fix this issue. I don't think I am sufficiently familiarized with Spring-Boot 2.0 components yet.
