### ISSUE TITLE
management.endpoints.web.base-path doesn't work

### ISSUE THREAD

**Issue by dmitrysenkovich** [spring-projects/spring-boot#14133]
Hi everyone, I'm migrating Spring Boot application to Spring Boot 2 and it mostly works fine but I can't change actuator endpoints path with `management.endpoints.web.base-path` (trying to make it work with Spring Admin UI 2). Trying to set it like this with yml:

```
management:
    health:
        db.enabled: false
        hystrix.enabled: false
    security.enabled: false
    endpoints.web:
        expose: *
        base-path: /ololo
```

The property seems to be ignored and the default /actuator path is preserved. Spring Boot version is 2.0.4.RELEASE.

Thank you for any help!
