### ISSUE TITLE
Websocket SockJS and Zuul

### ISSUE THREAD

**Issue by Amraneze** [spring-projects/spring-boot#14280]
I'm trying to use websocket with Zuul, but I can't access to it. I'm getting connection lost after some ms. I was looking and I found that I need to increase the time of ribbon ConnectTimeout and ReadTimeout and it was working for some some seconds and after it's stopped. Is there any solution for this ?

I'm using Spring boot 2.0.3.RELEASE with Spring cloud Finchley.RELEASE

Here is my configuration for Zuul:

```
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 50000
  ConnectTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
```
