### ISSUE TITLE
Add Support for client_credentials Auto Configuration

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#14552]
With the changes in https://github.com/spring-projects/spring-boot/commit/f5deebf0cb2fb802bafb5ff85652ebe89e9da98d#diff-b716836901d5fea39e485e35997f2f62 the configuration below works but longer makes sense:

```yml
spring:
  security:
    oauth2:
      client:
        provider:
          idp:
            issuer-uri: https://example.com/
        registration:
          authorizationcode:
            idp:
              client-id: client-id
              client-secret: client-secret
              authorization_grant_type: client_credentials
```

Notice that a client_credentials grant type is being configured under the authorizationcode parent. 

Related #14554
