### ISSUE TITLE
Validation of Client Registration Ids

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#14555]
With the changes in https://github.com/spring-projects/spring-boot/commit/f5deebf0cb2fb802bafb5ff85652ebe89e9da98d#diff-b716836901d5fea39e485e35997f2f62 we should probably validate the client registration ids are not duplicated. For example, with the old configuration this:
```yml
spring:
  security:
    oauth2:
      client:
        provider:
          idp:
            issuer-uri: https://example.com
        registration:
          idp:
            client-id: client-id
            client-secret: client-secret
          idp:
            client-id: client-id
            client-secret: client-secret
```

 produced an error:

```
Caused by: org.yaml.snakeyaml.constructor.DuplicateKeyException: while constructing a mapping
 in 'reader', line 18, column 11:
              idp:
              ^
found duplicate key idp
 in 'reader', line 21, column 11:
              idp:
              ^

	at org.yaml.snakeyaml.constructor.SafeConstructor.processDuplicateKeys(SafeConst
```

However, the new configuration does not produce an error:

```yml
spring:
  security:
    oauth2:
      client:
        provider:
          idp:
            issuer-uri: https://example.com
        registration:
          login:
            idp:
              client-id: client-id
              client-secret: client-secret
            authorizationcode:
              idp:
                client-id: client-id
                client-secret: client-secret
```

Related: #14554
