### ISSUE TITLE
Consider Alternative to in Grant Type Hiearchy

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#14554]
The changes in https://github.com/spring-projects/spring-boot/commit/f5deebf0cb2fb802bafb5ff85652ebe89e9da98d#diff-b716836901d5fea39e485e35997f2f62 make it so that the grant type is in the hierarchy. I'm not sure if this is a good long term solution since there will likely come a time (soon) where we support multiple grant types in a registration (with one being "preferred"). When a user requests a token they would then specify which grant type if they wanted something different than the default.

With these changes in mind it is going to make configuring the code challenging because the user would need to duplicate the configuration. For example:

```
spring:
  security:
    oauth2:
      client:
        provider:
          idp:
            issuer-uri: https://example.com/
        registration:
          authorizationcode:
            idp-ac:
              provider: idp
              client-id: client-id
              client-secret: client-secret
          clientcredentials:
            idp-cc:
              provider: idp
              client-id: client-id
              client-secret: client-secret
```

One option would be to allow additional grant types property on the registration. However, this becomes ambiguous how the user should configure it. Should they place it under authorizationcode or clientcredentials? If they place it under a grant type that is missing a property for the additional grant type then, the would get an error too. For example:

```yml
spring:
  security:
    oauth2:
      client:
        provider:
          idp:
            issuer-uri: https://example.com/
        registration:
          clientcredentials:
            idp-cc:
              client-id: client-id
              client-secret: client-secret
              additional_grant_types: authorization_code
              redirect-url: /foo/bar # redirect-url is not needed for client-credentials
```

I'd like to consider going back to the original way. If the authorization_grant_type is provided, the default redirect-url is then mapped accordingly.

```yml
spring:
  security:
    oauth2:
      client:
        provider:
          idp:
            issuer-uri: https://example.com/
        registration:
          idp:
            client-id: client-id
            client-secret: client-secret
            authorization_grant_type: authorization_code
```

**Comment by mbhave** [comment]
@rwinch If there is going to be support for a "preferred" grant type, I don't see why additional_grant_types would be misleading. The default one would be the that's under the key and the additional ones would be supported if the user specifies that in the request. 

> If they place it under a grant type that is missing a property for the additional grant type then, the would get an error too

We don't have this sort of validation and when/if we do add validation we can take such factors into account.

**Comment by rwinch** [comment]
> We don't have this sort of validation and when/if we do add validation we can take such factors into account.

It was my understanding that part of the benefit of the new approach was that not all grant types need the same properties. This seemed to imply that client credentials wouldn't have a redirect uri. If it does have the redirect uri property, then this is not really an advantage of the new approach. Perhaps I am missing something?

**Comment by snicoll** [comment]
>  This seemed to imply that client credentials wouldn't have a redirect uri.

Grant types can have totally different properties with fine-tuned names and/or description. If a property is not valid for a particular grand type, it will simply not be present (and the IDE will not offer auto-completion for it and complain if you try to set it). Besides, the binder won't be able to bind it simply because it isn't there.

**Comment by rwinch** [comment]
> One of the reasons we decided to split the registration types was that although both login and authorization-code have a property named redirect-uri, they actually mean different things depending on the context

Can you expand on this? In both cases the redirect uri is where the authorization code is being sent to.

> Whilst it's very tempting to create just a single data type, I think keeping them distinct is important.

I don't think this makes sense. This is not how OAuth specification or any discussions around OAuth are conveyed. By creating our own types, we are now having to use our own terminology, definitions, and explanations. 

My fear is that this hierarchy adds complexity to the users. I've already received feedback from two users  stating that it was not very intuitive. If we go back to the previous way, all of the mappings become a one to one with existing OAuth terminology which simplifies conversations and understanding for users.

**Comment by mbhave** [comment]
> In both cases the redirect uri is where the authorization code is being sent to.

My understanding was that for the login client registrations the redirect uri needs to match the `filterProcessesUrl` for the `OAuth2LoginAuthenticationFilter` and the default for that is `/login/oauth2/code/*`. So even though the redirect uri for both login and authorization code is where the authorization code is sent, they have different requirements from an end user perspective. 

It's probably best to discuss this in person next week.

**Comment by mraible** [comment]
Hey all,

I'm creating an app that has OAuth 2.0 login and a resource server in the same app. I've found that I have to duplicate values for two keys to make it work.

```yaml
oidc.issuer-uri: https://dev-737523.oktapreview.com/oauth2/default

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: ${oidc.issuer-uri}
        registration:
          login:
            okta:
              client-id: XXX
              client-secret: YYY
              scope: openid email profile
      resourceserver:
        jwt:
          issuer-uri: ${oidc.issuer-uri}
```

As someone that knows a bit about OAuth 2.0, this makes sense. Yes, there is duplication, but I'm enabling two separate features. 

> In previous versions, I believe `@EnableOAuth2Sso` and `@EnableResourceServer` activated the different features. Will that still be a possibility in Spring Boot 2.1?

Unfortunately, I don't know that this will make sense to the average user. Is it possible to hide the complexity and have "oauth2" or "oidc" be top-level keys? That way, users could even memorize the key names! ;) 

For example:

```yaml
oidc:
  issuer-uri:
  client-id:
  client-secret:
```
