### ISSUE TITLE
All YAML profiles not validated before startup if written on different files

### ISSUE THREAD

**Issue by anandvarkeyphilips** [spring-projects/spring-boot#15302]
When using multiple yml profile files, the yml files that are active only is validated. Suppose I have `application-prod.yml` and it has a wrong indentation, it will only fail in production as no one will run it in sit or dev environments. If we define all profiles in a sinlge yml file with  yaml document seperator ("---"), it validates all properties and the error is identified. 

It would be great to provide the consistent behaviour across multiple file profile and single yml profile configuration. This is my first major issue ticket. Please bear with me.

Tested with 2.0.4.RELEASE.

application.yml (main application file which ignores dev yml configuration errors)
```
# This is the base Spring boot configuration properties file which is inherited in all the environments.
spring:
    profiles:
        active: prod
    main:
        banner-mode: "off"
```

application-dev.yml (incorrect indentation of profiles key)
```
#This section contains the properties that will be over-written for the development environment;
spring:
  profiles: dev
    output.ansi.enabled: always
``` 

application-prod.yml (correct indentation of profiles key)
```
#This section contains the properties that will be over-written for the development environment;
spring:
    profiles: prod
    output.ansi.enabled: always
```
