### ISSUE TITLE
Provide the ability to preset properties from META-INF/spring.factories

### ISSUE THREAD

**Issue by symphony-thibault** [spring-projects/spring-boot#15730]
It should be possible to preset or preconfigure some Spring Boot properties from a custom stater library through its `META-INF/spring.factories`. 
For example, a custom starter library may be able to preset defaults ports like : 
```yml
server:
   port: 8443
management:
   server: 
      port: 9443
``` 
As a main use-case, this feature could be useful for a library shared across multiple micro-services written in Spring Boot.
