### ISSUE TITLE
The resolvedMethods property is not set correctly when configuring CorsConfiguration with @ConfigurationProperties

### ISSUE THREAD

**Issue by JiaRG** [spring-projects/spring-boot#15796]
**SpringBoot Version:**  **1.5.19.RELEASE**

application.yml
```yml
cors:
  allowed-headers: "*"
  allowed-methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
  allowed-origins: ["http://localhost:3000", "http://127.0.0.1:3000"]
  allow-credentials: true
  maxAge: 1800
```

JavaConfig
```java
@Configuration
public class AppConfig {

    @ConfigurationProperties(prefix = "cors")
    @Bean
    public CorsConfiguration corsConfiguration() {
        return new CorsConfiguration();
    }

    @Bean
    public CorsFilter corsFilter(CorsConfiguration corsConfiguration) {
        UrlBasedCorsConfigurationSource corsConfigurationSource = new UrlBasedCorsConfigurationSource();
        corsConfigurationSource.registerCorsConfiguration("/**", corsConfiguration);
        return new CorsFilter(corsConfigurationSource);
    }
}
```
Result:
![image](https://user-images.githubusercontent.com/31472350/51832415-944cb180-232f-11e9-8a13-c32577344d9d.png)

But when I try to use the **2.x version** it works fine：
![image](https://user-images.githubusercontent.com/31472350/51832643-39678a00-2330-11e9-8ef0-f79bbdecedbc.png)
