### ISSUE TITLE
Optional nested configuration property not assigned

### ISSUE THREAD

**Issue by mamachanko** [spring-projects/spring-boot#15999]
Hi, if I understood #5110 correctly then one should expect optional configuration properties to be assigned.

Find a sample application prepared here: https://github.com/mamachanko/optional-nested-configuration-property

Assuming a config classes like so:
```java
@Component
@ConfigurationProperties(prefix = "config")
@Data
@Validated
class Config {

	@NotBlank
	private String requiredProperty;
	private Optional<String> optionalProperty = Optional.empty();

	@NotNull
	private MoreConfig moreRequiredConfig;
	private Optional<MoreConfig> moreOptionalConfig = Optional.empty();
}

@Data
class MoreConfig {
	private String property;
}
```

# Running w/ full configuration
```yaml
spring:
  profiles: full
config:
  required-property: this-is-required
  optional-property: this-is-optional
  more-required-config:
    property: this-is-required
  more-optional-config:
    property: this-is-optional
``` 
```bash
$ ./mvnw clean spring-boot:run -Dspring.profiles.active=full
...
2019-02-19 21:08:16.288  INFO 28484 --- [main] i.g.m.o.ConfigLogger: Config(requiredProperty=this-is-required, optionalProperty=Optional[this-is-optional], moreRequiredConfig=MoreConfig(property=this-is-required), moreOptionalConfig=Optional.empty)
```
* The field `optionalProperty` of type `Optional<String>` gets assigned as expected.
* The field `moreOptionalConfig` of type `Optional<MoreConfig>` remains `Optional.empty`. This is not expected. It is expected to be `MoreConfig(property=this-is-optional)`.

Does that make sense?
