### ISSUE TITLE
Cannot read properties when use profiles

### ISSUE THREAD

**Issue by wamaco** [spring-projects/spring-boot#16259]
I have defined AutoDatasourceConfiguration which use EnumerablePropertySource read application.yml, but cannot read `spring.datasource.*` properties when add profiles.

```yml
spring:
  profiles: development   #  all works if remove this configuration
  datasource:
    demo:
      url: "jdbc:mysql://localhost:3306/test"
      username: wa
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
```

AutoDatasourceConfiguration code :
```java
@Override
    public void setEnvironment(@Nonnull Environment environment) {
        if (!(environment instanceof ConfigurableEnvironment)) {
            return;
        }
        for (PropertySource<?> propertySource : ((ConfigurableEnvironment) environment).getPropertySources()) {
            if (!(propertySource instanceof EnumerablePropertySource)) {
                continue;
            }
            for (String key : ((EnumerablePropertySource) propertySource).getPropertyNames()) {
                // no spring.datasource.demo property when add spring.profiles config
                properties.put(key, environment.getProperty(key));
            }
        }
    }
```
