### ISSUE TITLE
Duplicate keys in YAML cause some unexpected results

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#1683]
If user puts this in `application.yml`:

```
spring:
  datasource:
    url: jdbc:mysql://localhost/test
spring:
  main:
    headless: true
```

They might expect to be able to bind to MySQL and be surprised that the `PropertySource` only contains the `spring.main.*` entries. The reason is that there are 2 map keys "spring" and the 2nd one to be parsed wins.

We could fix this by using a custom `Constructor` in Snake YAML (appending to existing maps instead of overwriting them).
