### ISSUE TITLE
YAML configuration polymorphism misbehavior

### ISSUE THREAD

**Issue by smedelyan** [spring-projects/spring-boot#16900]
I want to get a `List<Base>` from `application.yaml`.
Classes are (removed getters/setters for readability):
```java
@JsonTypeInfo(use= JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "type")
public class Base {
}

public class Donkey extends Base {
    private String speech;
    private String moto;

    /* ... */
}

public class Shrek extends Base {

    private float weight;
    private String moto;

    /* ... */
}
```
I expect both of the following to be valid configuration files, but I get `Failed to bind properties under 'app.bases' to java.util.List<com.example.dynamic.Base> ...weight, ...moto properties were left unbound` error when trying to bind that to `List<Base>`:
```yaml
app:
  bases:
    - type: com.example.dynamic.Shrek
      weight: 20
      moto: I hate Donkey!
```
and
```yaml
app:
  bases:
    - !<com.example.dynamic.Shrek>
      weight: 20
      moto: I hate Donkey!
```

Both of the above are successfully loaded with manual use of `ObjectMapper`.

I double-checked I've formatted `.yaml` file right:
```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = MainConfig.class)
public class Tests {

    @Test
    public void outputs() throws IOException {
        ObjectMapper mapper = new YAMLMapper();
        Donkey d = new Donkey();
        d.setMoto("hey");
        d.setSpeech("speech");

        Shrek s = new Shrek();
        s.setWeight(20.0f);
        s.setMoto("shrek");

        List<Base> list = new ArrayList<>();
        list.add(d);
        list.add(s);

        File out = new File("yaml.yaml");
        mapper.writerFor(new TypeReference<List<Base>>() {
        }).writeValue(out, list);

        CollectionType javaType = mapper.getTypeFactory().constructCollectionType(List.class, Base.class);
        List<Base> in = mapper.readValue(out, javaType);

        assertTrue(in.get(0) instanceof Donkey);
        assertTrue(in.get(1) instanceof Shrek);
    }
}
```
```yaml
# yaml.yaml contents:
---
- !<com.example.dynamic.Donkey>
  speech: "speech"
  moto: "hey"
- !<com.example.dynamic.Shrek>
  weight: 20.0
  moto: "shrek"

```

# Current work-around

Manual parsing:
```java
// Base.java
@JsonTypeInfo(use= JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "type")
public class Base {

    public final void parse(String jsonConfig) {
        ObjectMapper mapper = new ObjectMapper();
        Object self;
        try {
            self = mapper.readValue(jsonConfig, getClass());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        MapperFacade orikaMaper = new ConfigurableMapper();
        orikaMaper.map(self, this);
    }
}
```
```java
// Donkey.java
public class Donkey extends Base {
    
    // ...

    public Donkey(String jsonConfig) {
        parse(jsonConfig);
    }
}
```
```java
// Shrek.java
public class Shrek extends Base {
    
    // ...

    public Shrek(String jsonConfig) {
        parse(jsonConfig);
    }
}
```
And configuration file:
```yaml
app:
  bases:
    - !!com.example.dynamic.Donkey |
      {
        "type": "com.example.dynamic.Donkey",
        "speech": "I'm Donkey!",
        "moto": "I love talking!"
      }

    - !!com.example.dynamic.Shrek |
      {
        "type": "com.example.dynamic.Shrek",
        "weight": 20,
        "moto": "I hate Donkey!"
      }
```

This one obviously works but that looks nasty and I lose syntax highlighting and formatting in the IDE

**EDIT**
Actually, I think we don't even need the `type` field then since we call a particular constructor. 
We may achieve the same in a bit less lines of code:
```java
// Base.java
// Removed annotation here
public class Base {

    public final void parse(String jsonConfig) {
        ObjectMapper mapper = new ObjectMapper();
        Object self;
        try {
            self = mapper.readValue(jsonConfig, getClass());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        MapperFacade orikaMaper = new ConfigurableMapper();
        orikaMaper.map(self, this);
    }
}
```
```java
// Donkey.java and Shrek.java are the same
```
And configuration file:
```yaml
app:
  bases:
    - !!com.example.dynamic.Donkey |
      {
# removed "type" field
        "speech": "I'm Donkey!",
        "moto": "I love talking!"
      }

    - !!com.example.dynamic.Shrek |
      {
# removed "type" field
        "weight": 20,
        "moto": "I hate Donkey!"
      }
```
P. S. Didn't test the latter case, but it should work
