### ISSUE TITLE
actuator /env issue

### ISSUE THREAD

**Issue by anuraram12345** [spring-projects/spring-boot#17458]
I am trying to access the spring boot http://localhost:8080/actuator

I the below URLs are working

http://localhost:8080/actuator/info
http://localhost:8080/actuator/health
I needed to access the env properties

I gave the below config in yml. But still, I could not access the env

```yaml
spring:
  management:
    endpoint:
      env:
        enabled: true
    endpoints:
      web:
       base-path: /
       exposure:
        include: env, info, metrics
```
