### ISSUE TITLE
It is unclear that the RSocket websocket transport requires Reactor Netty and is not supported with other web servers

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-boot#17494]
When using the `spring-boot-starter-web` and `spring-boot-starter-rsocket` and using these settings:
```yml
spring:
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket
```

Connecting with an RSocket client yields this error:
```
21:33:13.910 WARN [reactor-http-nio-4] [id: 0x2d4c451e, L:/127.0.0.1:60219 - R:localhost/127.0.0.1:8080] The connection observed an error
io.netty.handler.codec.http.websocketx.WebSocketHandshakeException: Invalid handshake response getStatus: 404
```

I'd expect it to work as it with `spring-boot-starter-webflux` does or at least some hint in the documentation (for the RSocketProperties) or an exception at startup.
