### ISSUE TITLE
spring boot All version log output to file contents are incomplete at windows system

### ISSUE THREAD

**Issue by pog2g** [spring-projects/spring-boot#17629]
The console print log content is inconsistent with the file record, and the file record log content is missing a lot, or even not output to a file

The log configuration:

```yml
logging:
  level:
    root: ${app.log-root-level:debug}
  file: logs/${spring.application.name}.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
debug: true
```
