### ISSUE TITLE
Compression threshold does not work

### ISSUE THREAD

**Issue by zhaoyunxing92** [spring-projects/spring-boot#17633]
version: 2.1.6.RELEASE
my configuration
```yml
server:
  compression:
    enabled: true
    min-response-size: 50MB
```
my understanding is that it compresses when the threshold is exceeded, but it compresses me no matter how much I adjust the threshold.How to use it(`min-response-size`)
