### ISSUE TITLE
Document need to exactly match Hibernate's property format when configuring spring.jpa.properties.hibernate.* properties

### ISSUE THREAD

**Issue by TheElk205** [spring-projects/spring-boot#17975]
I just figured that the yaml parser is not working as intended. I have this part in my `application.yaml`

```
spring:
  profiles: development
  jpa:
    show_sql: true
    database: default
    generate-ddl: false
    properties:
      hibernate:
        order_inserts: true
        generate_statistics: true
        ddl_auto: validate
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
```

If I start my applciation now, everything is fine, sql statements are printed and batching is working.
![image](https://user-images.githubusercontent.com/11997909/63790915-96ddac80-c8fa-11e9-9079-4847e466fc63.png)

If I now change `show_sql` to `showSql` everything still works as expected. (double checked it by setting it to false as well, to be sure that it does not get overwritten)

**BUT**
If I change `batch_size` to `batchSize`, sql statements are not batched any more.
![image](https://user-images.githubusercontent.com/11997909/63790995-c12f6a00-c8fa-11e9-8001-b18eac52284c.png)

I am inserting 51 values at a time here.
