### ISSUE TITLE
Server Side Compression not working when sending Accept-Encoding with multiple values separately

### ISSUE THREAD

**Issue by patan12** [spring-projects/spring-boot#18176]
Server Side Compression not working when sending Accept-Encoding with multiple values separately

Here is my application yml

```
server:
  port: 8193
  servlet:
    context-path: /web
  compression:
    enabled: true
    min-response-size: 1024
```

When sending request as like this server compress response 

```
	Url: http://localhost:8193/web/demo/1

	Request Headers:
	Accept-Encoding:deflate, gzip, br


	Response Headers:
		
	KEY: VALUE
	Content-Type: application/json;charset=UTF-8
	Transfer-Encoding: chunked
	Content-Encoding: gzip
	Vary: Accept-Encoding
```

**But when sending request as separate gzip headers, then response is not compressed**

```
	Url: http://localhost:8193/web/demo/1

	Headers:
	Accept-Encoding:deflate
	Accept-Encoding:gzip

	Response Headers:

	KEY:VALUE
	Content-Type:application/json;charset=UTF-8
	Content-Length:8540
	Vary:Accept-Encoding

```

I have also attached sample project

Refer Here

[muzwebdemo.zip](https://github.com/spring-projects/spring-boot/files/3586668/muzwebdemo.zip)
