### ISSUE TITLE
Misleading exception for ConfigurationProperties when map key is handled by custom converter

### ISSUE THREAD

**Issue by zeldigas** [spring-projects/spring-boot#18509]
## Context
Spring boot version - 2.1.9

I've bumped into a problem with very misleading exception for `ConfigurationProperties` class.
Setup (for brevity, all getters and setters are omitted)

```java
@Validated
public class AppProperties {

    @Valid
    private Map<KeyType, NestedProperty> myMap;

}
```

```java
public interface KeyType {

}
```

```java
public enum MyEnum implements KeyType {

    ONE, TWO

}
```

```java
public class NestedProperty {

    @NotEmpty
    private String first;

    @NotEmpty
    private String second;

}
```

```java
@ConfigurationPropertiesBinding
@Component
public class KeyTypeConverter implements Converter<String, KeyType> {

    @Override
    public KeyType convert(String s) {
        return MyEnum.valueOf(s);
    }

}
```

Configuration that fails validation, e.g. `second` is empty

```
test.my-map.ONE.first=hello
test.my-map.ONE.second=
```

## Expected result
Message about nested property and it's failed constraint
```
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'test' to com.example.conversionproblem.AppProperties failed:

    Property: test.myMap[ONE].second
    Value: 
    Reason: must not be empty

```
## Actual Result
I got this one:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'test' to com.example.conversionproblem.AppProperties:

    Property: test.my-map.one.second
    Value: 
    Origin: class path resource [application.properties]:3:0
    Reason: Cannot convert value of type 'java.lang.String' to required type 'com.example.conversionproblem.KeyType': no matching editors or conversion strategy found

Action:

Update your application's configuration
```

## Extra info

I've create a sample project for you to look at the problem: https://github.com/zeldigas/spring-boot-conversion-problem

Also worth mentioning that I observe this behavior only with boot 2, boot 1.5 correctly reported issue about validation failure on `second` due to it's empty.

**Comment by philwebb** [comment]
With Spring Boot 2.2 the correct message is displayed:

```
Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'test' to com.example.conversionproblem.AppProperties failed:

    Property: test.myMap[ONE].second
    Value: null
    Reason: must not be empty


Action:

Update your application's configuration
```

This is due to the changes we made for #17424. Those changes are quite involved so I'm not keen to back-port them to 2.1.x given the risk.

@zeldigas Can you try 2.2 with your real application and let me know if you still see the problem.
