### ISSUE TITLE
Mention keys with dots for yaml in "Spring Boot Configuration Binding" wiki

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-boot#18690]
It is mentioned in https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding#map-based-binding for properties.

I found the answer here https://stackoverflow.com/questions/34070987/escaping-a-dot-in-a-map-key-in-yaml-in-spring-boot

See https://github.com/spring-cloud-incubator/spring-cloud-rsocket/issues/1 for origin. The quote/bracket notation is shown below.

```
spring:
  cloud:
    gateway:
      rsocket:
        client:
          forwarding:
            "[create.reservation.{version}]":
              service_name: reservation-service
              canary: false
```
