### ISSUE TITLE
SpringBoot parsed yaml incorrectly

### ISSUE THREAD

**Issue by hanlifei** [spring-projects/spring-boot#18708]
```
map:
  data:
    - id: 0
      points:
        - x: 0
          y: 0
          place:
            place_type: table
            place_id: 0
            place:
              place_type: prop
              place_id: 1
```
**Above is my yml configuration**
**The following is the corresponding configuration class**
```
@PropertySource(value = {"classpath:floor_plan.yml"}, factory = YamlSourceFactory.class)
@ConfigurationProperties(prefix = "map")
@Component
@Getter
@Setter
public class FloorPlan implements Serializable {

	private static final long serialVersionUID = 7889511292813486341L;
	private List<Graph> data;

	@Setter
	@Getter
	public static final class Graph implements Serializable {
		private static final long serialVersionUID = 8165584398823841393L;
		private int id;
		private List<Point> points;
	}

	@Setter
	@Getter
	public static final class Point implements Serializable {
		private static final long serialVersionUID = -3447034248118033017L;
		private int x;
		private int y;
		private PlaceItem place;
	}

	@Setter
	@Getter
	public static final class PlaceItem implements Serializable {
		private static final long serialVersionUID = -8200048504444500019L;
		private String placeType;
		private int placeId;
		private PlaceItem place;
	}
}
```

PlaceItem is a recursive reference class. 
The place attribute in the PlaceItem gets null.
Automatic configuration cannot be injected into the place attribute in the PlaceItem
Is there a problem with my configuration? Or can't it be done?
Is there any way to do this configuration?
