### ISSUE TITLE
DataSource initialization can be invoked after the wrong EntityManager has initialized

### ISSUE THREAD

**Issue by mrifni** [spring-projects/spring-boot#18829]
I have configured my application to use two data sources. And I want data.sql to run on my primary datasource. But everytime I start the application I can see data.sql is executed on wrong datasource ( not primary ) and even before any model classes are initiated ( so it can create the tables, columns first ).

See my codes below.

data.sql is run for this wrong data source.

```java
import org.springframework.beans.factory.annotation.Qualifier
import org.springframework.boot.context.properties.ConfigurationProperties
import org.springframework.boot.jdbc.DataSourceBuilder
import org.springframework.boot.orm.jpa.EntityManagerFactoryBuilder
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.data.jpa.repository.config.EnableJpaRepositories
import org.springframework.orm.jpa.JpaTransactionManager
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean
import org.springframework.transaction.PlatformTransactionManager
import org.springframework.transaction.annotation.EnableTransactionManagement
import javax.persistence.EntityManagerFactory
import javax.sql.DataSource

@Configuration
@EnableTransactionManagement
@EnableJpaRepositories(entityManagerFactoryRef = "organisationServiceEntityManagerFactory", transactionManagerRef = "ost")
class OrganisationServiceDataConfig {

    @Bean(name = ["organisationServiceEntityManagerFactory"])
    fun organisationServiceEntityManagerFactory(
        builder: EntityManagerFactoryBuilder,
        @Qualifier("organisationServiceDataSource") dataSource: DataSource
    ): LocalContainerEntityManagerFactoryBean {
        return builder
            .dataSource(dataSource)
            .packages("com.dovetaillab.consentapi.adminwebservice.model.organisationservice")
            .persistenceUnit("organisationservice")
            .build()
    }

    @Bean(name = ["organisationServiceDataSource"])
    @ConfigurationProperties(prefix = "spring.datasource-organisationservice")
    fun organisationServiceDataSource(): DataSource {
        return DataSourceBuilder.create().build()
    }

    @Bean
    fun ost(@Qualifier("organisationServiceEntityManagerFactory") organisationServiceEntityManagerFactory: EntityManagerFactory): PlatformTransactionManager {
        return JpaTransactionManager(organisationServiceEntityManagerFactory)
    }
}
```

My primary datasource

```java
package com.dovetaillab.consentapi.adminwebservice.config.datasources

import org.springframework.beans.factory.annotation.Qualifier
import org.springframework.boot.context.properties.ConfigurationProperties
import org.springframework.boot.jdbc.DataSourceBuilder
import org.springframework.boot.orm.jpa.EntityManagerFactoryBuilder
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.Primary
import org.springframework.data.jpa.repository.config.EnableJpaRepositories
import org.springframework.orm.jpa.JpaTransactionManager
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean
import org.springframework.transaction.PlatformTransactionManager
import org.springframework.transaction.annotation.EnableTransactionManagement
import javax.persistence.EntityManagerFactory
import javax.sql.DataSource

@Configuration
@EnableTransactionManagement
@EnableJpaRepositories(entityManagerFactoryRef = "primaryEntityManagerFactory", transactionManagerRef = "pt")
class PrimaryDataConfig {

    @Bean(name = ["primaryEntityManagerFactory"])
    @Primary
    fun primaryEntityManagerFactory(
        builder: EntityManagerFactoryBuilder,
        @Qualifier("primaryBaseDataSource") dataSource: DataSource
    ): LocalContainerEntityManagerFactoryBean {
        return builder
            .dataSource(dataSource)
            .packages("com.dovetaillab.consentapi.adminwebservice.model.primary")
            .persistenceUnit("primary")
            .build()
    }

    @Primary
    @Bean(name = ["primaryBaseDataSource"])
    @ConfigurationProperties(prefix = "spring.datasource")
    fun primaryBaseDataSource(): DataSource {
        return DataSourceBuilder.create().build()
    }

    @Primary
    @Bean
    fun pt(@Qualifier("primaryEntityManagerFactory") primaryEntityManagerFactory: EntityManagerFactory): PlatformTransactionManager {
        return JpaTransactionManager(primaryEntityManagerFactory)
    }
}

```

Application.properties

```
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/maindb
    username: main_user
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: false

  datasource-organisationservice:
    jdbc-url: jdbc:postgresql://localhost:5432/organisationservice
    username: organisationservice_user
    password: admin
    driver-class-name: org.postgresql.Driver
```

Any idea why ?
