### ISSUE TITLE
Empty yaml objects are not injected as properties

### ISSUE THREAD

**Issue by jntakpe** [spring-projects/spring-boot#19095]
Spring Boot version: 2.2.1.RELEASE

Having the following properties
```yml
prefix:
  obj:
    foo:
      firstName: John
      lastName: Doe
    bar: {}
```

And given the following properties class 

```kotlin
@ConstructorBinding
@ConfigurationProperties("prefix")
data class ObjProperties(val obj: Map<String, FooBarProperties>)

@ConstructorBinding
data class FooBarProperties(val firstName: String? = "", val lastName: String? = "")
```

I was expecting that injecting ObjProperties bean will result in having both `foo` property and `bar` property in `obj` map. Unfortunately, `bar` property is missing from the `obj`map.
