### ISSUE TITLE
endpoints.env.keys-to-sanitize not working

### ISSUE THREAD

**Issue by PeterLaiAndDigital** [spring-projects/spring-boot#19206]
We're using Actuator 2.1.2 Release. 

We've tried 3 ways of writing our configuration. 

```yaml
endpoints:
  env:
    keys-to-sanitize: password,username,secret,key,token,.*credentials.*,vcap_services
```

```yaml
endpoints:
  env:
    keys-to-sanitize: 
      - password
      - username
      - secret
      - ke
      - token
      - .*credentials.*
      - vcap_services
```

```yaml
endpoints.env.keys-to-sanitize: password,secret,key,token,.*credentials.*,vcap_services,username
```

But the username is never sanitized, e.g. 

```javascript
"xxxxxx.authentication.username": {
    "value": "admin"
}
```
