### ISSUE TITLE
Add Kafka `security.protocol` key to SpringBoot autoconfig

### ISSUE THREAD

**Issue by Woodz** [spring-projects/spring-boot#19220]
Having some Kafka properties defined in SpringBoot autoconfig vs some Kafka properties having to be set in a separate "properties" map is not intuitive and is therefore confusing to junior devs. I propose that "security.protocol" is added to SpringBoot auto-configuration to avoid the separate "properties" key.

Spring Boot version: 2.1.9.RELEASE
Kafka version: 2.0.1

Example application.yml:
```
kafka:
  consumer:
    bootstrap-servers: <server>
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    ssl:
      truststore-location: <trust store location>
      truststore-password: <password>
    properties:
      security.protocol: SSL
```
