### ISSUE TITLE
Reactive OAuth 2 with Public Key Value doesn't work 

### ISSUE THREAD

**Issue by Thinkenterprise** [spring-projects/spring-boot#19457]
I use Spring Boot 2.2 with WebFlux and OAuth 2 and implement a Resource Server with a **Public Key Value** Configuration. 

```
 security:
    oauth2:
      resourceserver:
        jwt: 
          public-key-location: public-key.txt
```
It works in a Non-Reactive Environment. In a Reactive Environment 
the method ```readPublicKey()``` of the ```OAuth2ResourceServerProperties``` throws an Exception because the method  ```exists()```of the  ```FilteredReactiveWebContextResource``` returns always false. 

In the comment of the class ```FilteredReactiveWebContextResource``` this behaviour is described. But then how can I use the Public Key Value in a Reactive OAuth 2 Environment? 

Regards 
Michael
