### ISSUE TITLE
HikariDataSource cannot be initialized at application startup

### ISSUE THREAD

**Issue by MrXionGe** [spring-projects/spring-boot#19596]
### HikariCP version: 3.4.1
**Now, I only initialize the database connection when the application is accessed.
If the database connection has errors, I can't find the problem quickly.
I tried some methods and still can't solve it.**
E.g
```
    @Bean
    public LazyInitializationExcludeFilter excludeFilter() {
        return LazyInitializationExcludeFilter.forBeanTypes(HikariDataSource.class);
    }
```
E.g
```
spring:
  main:
    lazy-initialization: false
```
**I have two apps with this problem now. One of them runs on JDK8 and the other runs on JDK13.**

**Comment by MrXionGe** [comment]
### This is part of the configuration file
```
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demos?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: *****************
    hikari:
      pool-name: HikariCP
      minimum-idle: 4
      maximum-pool-size: 16
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 600000
      connection-init-sql: SET NAMES utf8mb4
```

**Comment by MrXionGe** [comment]
I try to switch to another version (2.2.0/2.2.1). This problem also occurs.
Maybe the reason for lazy loading.

**Comment by snicoll** [comment]
@MrXionGe thanks for the report but I am afraid we can't help you with partial code snippet and no stacktrace. Can you please provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem?

**Comment by MrXionGe** [comment]
@snicoll 
https://gitee.com/MrXionGe/SimpleWeb.git
Compile and run directly. And it will not try to connect to MySQL.
Normally, when the application is started, we can see the log like "HikariCP Starting...". But this won't print now. Now, we can only connect to MySQL when the application is accessed and the SQL logic code is triggered for the first time.
In this example, there is no configuration for lazy loading. I added it yesterday and it didn't work, so I deleted it.

**Comment by snicoll** [comment]
@MrXionGe sorry but your complete application does not make a minimal sample. If the problem is with Hikari and MySQL, a small sample should only use that (and your pom should only have dependency to those and remove everything that's unrelated).

I am not sure I understand the problem either. It looks like you're using lazy initialization and you report that the database does not initialize on startup but only when used (which is working as designed and exactly the purpose of lazy initialization). I don't see any use of lazy initialization in your sample so I am confused.

Can you please share a small sample with only what's necessary to reproduce the problem please? Step by step instructions would be appreciated as well.

**Comment by MrXionGe** [comment]
[https://www.mrxionge.cn/file/lazydemo.zip](https://www.mrxionge.cn/file/lazydemo.zip)
#### I created a simple application.
#### I try to turn off lazy initialization. Doesn't seem to work.
#### May be my configuration is wrong.
#### If you can help me, that would be great.

**Comment by MrXionGe** [comment]
@snicoll I uploaded a new example. Hard viewing.

**Comment by snicoll** [comment]
@MrXionGe thanks for the feedback and the sample but I don't understand what you mean by

> I try to turn off lazy initialization. Doesn't seem to work.

Lazy initialization is off by default so the following is useless:

```yml
spring:
  main:
    lazy-initialization: false
```

This can be removed as this is the default behaviour. Can you please describe the actual problem (or how I can reproduce that with your sample) and what you're trying to achieve.
