### ISSUE TITLE
when I use spring_profiles_active in environment, springboot starts with 2 profiles

### ISSUE THREAD

**Issue by hetianyi** [spring-projects/spring-boot#19663]
- Spring Boot version : v2.2.2.RELEASE

##### application.yml
```yaml

spring:
  application:
    name: config-server
  profiles:
    active: dev

---
spring:
  profiles: dev
---
spring:
  profiles: test
```

before start, I set envronment by
```
export SPRING_PROFILES_ACTIVE=test
```
,then I start my app by ```java -jar app.jar```

I got a boot log:

```shell
2020-01-13 17:21:17,614 INFO  xxx.ConfigServerApplication:655 - The following profiles are active: test,dev      
```

But I expect only ```test``` profile.

I have tried 2.0.1.RELEASE which works fine.
