### ISSUE TITLE
Actuator triggers an early post processor initialization

### ISSUE THREAD

**Issue by cubita-io** [spring-projects/spring-boot#20128]
springboot 2.2.4-RELEASE
* pom.xml
```
<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- database start -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <!-- database end -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

    </dependencies>
```
* application.yml
```
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth8?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
````
* bootstrap.java
```
@SpringBootApplication
public class SessionBootstrap {

    public static void main(String[] args) {
        SpringApplication.run(SessionBootstrap.class, args);
    }
}
```
* But why ???
```
2020-02-12 00:54:42.986  INFO 95047 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-12 00:54:43.359  INFO 95047 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
```
