### ISSUE TITLE
Sprig boot Custom datasource is using the default configuration of Hikari rather than the properties defined in the property file.

### ISSUE THREAD

**Issue by sohailashraf003** [spring-projects/spring-boot#20228]
Custom datasource is not using the hikari configuration from the property file and using the default configuration.

**Config:**
```
spring:
    profiles:
        active: "dev"
    datasource:
        hikari:
            maxLifetime: 30000
            maximumPoolSize: 1
            idleTimeout: 10000
            poolName: IPDS-DB-POOL-1
```
**Logs**

```
**maximumPoolSize.................10**
metricRegistry..................none
metricsTrackerFactory...........none
minimumIdle.....................10
password........................<masked>
**poolName........................"HikariPool-1"**
readOnly........................false
registerMbeans..................false
scheduledExecutor...............none
schema..........................none
threadFactory...................internal
transactionIsolation............default
```
