### ISSUE TITLE
Support configuration of localEntityIdTemplate for a SAML Relying Party

### ISSUE THREAD

**Issue by picpicpic** [spring-projects/spring-boot#20352]
Add **localEntityIdTemplate** in saml2 autoconfiguration.

## Current configuration
```yaml
    saml2:
      relyingparty:
        registration:
          mysso:
            signing:
              credentials:
              - certificate-location: classpath:my-public.cer
                private-key-location: classpath:my-private.cer
            identityprovider:
              entity-id: entity-idp
              sso-url: https://mysso/public/saml2sso
              verification:
                credentials:
                - certificate-location: classpath:saml-signing-cert.pem
```

## Expected configuration
```yaml
    saml2:
      relyingparty:
        registration:
          mysso:
            signing:
              credentials:
              - certificate-location: classpath:my-public.cer
                private-key-location: classpath:my-private.cer
            identityprovider:
              entity-id: entity-idp
              sso-url: https://mysso/public/saml2sso
              verification:
                credentials:
                - certificate-location: classpath:saml-signing-cert.pem
            spprovider:
              local-entity-id: mylocalentityid
```
The 2 last lines allows to configure the local-entity-id.

## Proposal 
Add an internal class Spprovider in : ```org.springframework.boot.autoconfigure.security.saml2.Saml2RelyingPartyProperties```
Use builder in : ```org.springframework.boot.autoconfigure.security.saml2.Saml2RelyingPartyRegistrationConfiguration```

If needed, I can provide PR

Thx!
