### ISSUE TITLE
ConfigurationProperties list Attribute is missing

### ISSUE THREAD

**Issue by lnfdxwl** [spring-projects/spring-boot#20353]
When I have two remote profiles
my version is 2.1.2
application.yaml:
```spring:
  cloud:
    gateway:
      routes:
        - id: cf_admin_route
          predicates:
            - Path=/admin/privilege/permission-tree/get-permission-tree
          uri: lb://cf-admin-api
        - id: sea_admin_route
          predicates:
            - Path=/admin/privilege/**
          uri: lb://sea-api
        - id: swagger_route
          predicates:
            - Path=/swagger/{segment}/**
          uri: lb://{segment}
          filters:
            - StripPrefix=2
            - SetUri=lb://{segment}
        - id: health_route
          uri: forward:///actuator/health
          predicates:
            - Path=/health
```

application-test.yaml:
```
spring:
  cloud:
    gateway:
      routes:
        - id: im-server-socket
          predicates:
            - Path=/ws/cs-im
          uri: ws://im-server:9008
        - id: kratos-api-web-socket
          predicates:
            - Path=/api/kratos/socketIo/wwChat
          uri: ws://kratos-api.zelda:9008
```

I will lose the following configuration：
```
        - id: swagger_route
          predicates:
            - Path=/swagger/{segment}/**
          uri: lb://{segment}
          filters:
            - StripPrefix=2
            - SetUri=lb://{segment}
        - id: health_route
          uri: forward:///actuator/health
          predicates:
            - Path=/health
```
