### ISSUE TITLE
Ambiguous description of server.ssl.ciphers in documentation

### ISSUE THREAD

**Issue by ricsil** [spring-projects/spring-boot#20406]
We're writing an application using Spring Boot Webflux and trying to configure SSL.

In ```application.yml```, we have:

```
server:
  port: 8443
  ssl:
    enabled: true
    key-store: file: fakecert.p12
    key-store-type: PKCS12
    key-store-password: ${}
    key-password: ${}
    protocol: TLS
    enabled-protocols: TLSv1.2
    ciphers: CIPHER_1,CIPHER_2
```

What is really ambiguous in docs is that ciphers property is not used by all embedded servers (default ```netty``` sure doesn't, apparently looking at provided certificate to pick a cipher). 

If we switch to tomcat we see it pick up the cipher list but we didn't see it mentioned anywhere.

Questions I had about documentation of SSL:
* Should that info (embedded servers that use this field) be in `Description` field in `Server Properties` reference?
* Should `server.ssl.protocol` and `server.ssl.enabled-protocols` have a list of supported options?
* Should `server.ssl.ciphers` specify a preferred naming convention for ciphers? Should we specify IANA name, OpenSSL, GnuTLS?
* Should `Description` field specify variable type? For example, I wasn't sure whether `ciphers` should be a comma-separated string or a list.

I understand that this is server-dependent and you can't specify everything but it would sure be nice.
