### ISSUE TITLE
Hikari CP actuator metrics

### ISSUE THREAD

**Issue by mshetty794** [spring-projects/spring-boot#20605]
I have been trying to get actuator metrics for Hikari CP.  Let me know if it has to be custom implemented.

Looking for basic metrics like no active connection used etc. 

Below are the Hikari configuration  and actuator set in application.yml 

```yaml
spring:
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
       jdbc.batch_size: 5000
       default_schema: xxxx
       jdbc.fetch_size: 100
       jdbc.time_zone: UTC
       generate_statistics: true
  datasource:
    hikari:
      data-source-properties:
        oracle.net.encryption_client: REQUIRED
        oracle.net.encryption_types_client: ( AES256 )
    platform: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@x.x.x.x:1521:orcl
    username: xxxx
    password:xxxx$
    registerMbeans: true
    poolName: hikari-1

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
```
