### ISSUE TITLE
Provide a property or environment variable to enable DevTools' restarter irrespective of how the application was launched

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#21424]
This workflow used to work, but now doesn't:

```yaml
apiVersion: skaffold/v2alpha4
kind: Config
build:
  artifacts:
    - image: localhost:5000/apps/demo
      custom:
        buildCommand: ./mvnw spring-boot:build-image -D spring-boot.build-image.imageName=$IMAGE && docker push $IMAGE
        dependencies:
          paths:
            - pom.xml
            - src/main/resources
            - target/classes
      sync:
        manual:
          - src: "src/main/resources/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: src/main/resources/
          - src: "target/classes/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: target/classes/
```

The problem is that `Skaffold` still notices changes and syncs them with the running container, but Spring Boot is now running from the `JarLauncher` (because of a change in the default buildpack), so the changes are ignored by the app. You can see from the logs that the main thread is "main" not "restartedMain" so you know it's not going to work.

To fix it you would need a system property or something that could be set to force the "restartMain" thread to be created even though the class loader is a `JarLauncher`. Or alternatively, a way to build the image with a different `Main-Class`.
