### ISSUE TITLE
Removal of logging.file and logging.path is missing from the configuration changelog

### ISSUE THREAD

**Issue by jamesdbaker** [spring-projects/spring-boot#21479]
On upgrading to Spring Boot 2.3.0 (from 2.2.6), my application stopped logging to a file. No configuration changes were made. If I downgrade back to 2.2.7, with no change of configuration, then it starts logging again correctly.

I have, in my `application.yml`, the following configuration:

```
logging:
  level:
    root: WARN
    my.package: INFO
  file: portal.log
```
