### ISSUE TITLE
There are some problems in configuring mongodb with yaml in Spring Boot 2.3.0

### ISSUE THREAD

**Issue by MoncyXu** [spring-projects/spring-boot#21800]
**The version**
Spring Boot:2.3.0
MongoDB:4.2.7

**The configuration for mongodb**
```yaml
spring:
  data:
    mongodb:
      uri: mongodb://root:12345678@localhost:27017/springboot?authSource=admin
```
I can run my unit test normally by using above configuration.But when I change it to:
```yaml
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springboot
      username: root
      password: 12345678
      authentication-database: admin
```
my unit test throws exception like this:
```
org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-256, userName='root', source='admin', password=<hidden>, mechanismProperties=<hidden>}; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-256, userName='root', source='admin', password=<hidden>, mechanismProperties=<hidden>}
```
So, are there any differences between these two configurations? Shouldn't it be equivalent?
Plz help me out.

-------
**The code**
```java
@SpringBootTest
public class MongodbTest {
    @Autowired
    private MongoTemplate mongoTemplate;

    @Test
    public void test() {
        List<UserTest> insertList = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            UserTest userTest = new UserTest();
            userTest.setId(Long.valueOf(i));
            userTest.setName("name" + i);
            userTest.setAge(new Random().nextInt(30));
            userTest.setPhone("1000000" + i);
            insertList.add(userTest);
        }
        mongoTemplate.insertAll(insertList);
    }
}
```
```java
@Document
@Data
public class UserTest implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    private Long id;

    @Field
    private String name;

    @Field
    private Integer age;

    @Field
    private String phone;
}
```

**Comment by wilkinsona** [comment]
You haven't quoted the value of `password` so the YAML spec dictates that it be parsed it as a numeric value. This then gets turned into a `char[]` containing a single character rather than the characters 1, 2, 3, 4, 5, 7, 8. You can avoid the problem by quoting the value of `password` to indicate that it should be parsed as a string:

```yaml
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springboot
      username: root
      password: "12345678"
      authentication-database: admin
```

If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
