### ISSUE TITLE
Allow exclude only health groups

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#22053]
Currently `IncludeExcludeGroupMemberPredicate` required a `*` if all groups are to be included. It would be nice if instead you could write:

```yaml
management:
  endpoint:
    health:
      group:
        mygroup:
          exclude:
          - db
```
