### ISSUE TITLE
Mapping YAML properties to list of objects

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-boot#22393]
We have a configuration of list of objects
```
elastic:
  mappings:
    dynamic_templates:
    - longs_as_strings:
        match_mapping_type: string
        match: long_*
        unmatch: "*_text"
        mapping:
          type: long
```
This is mapped to 
```
@Configuration
@ConfigurationProperties(prefix = "elastic")
public class ElasticProperties {
    private Map<String, ?> mappings;
    // ...
}
```
When we verify the type of `dynamic_templates` value, it is `HashMap`, however in the yaml we declared that it is a list, and Elasticsearch client expects a `List`.
Is it expected behavior?
