### ISSUE TITLE
Provide a property for configuring the base path of the Actuator's endpoints when using WebFlux

### ISSUE THREAD

**Issue by ferblaca** [spring-projects/spring-boot#22906]
Spring Boot 2.3.2.RELEASE

The settings for customization of monitoring endpoints described at this [link](https://docs.spring.io/spring-boot/docs/2.3.2.RELEASE/reference/html/production-ready-features.html#production-ready-customizing-management-server-context-path) do not work for Webflux applications.

According to the following configuration:

```
spring:
  webflux:
    base-path: /demowebflux
management:
  server:
    port: 9081
    servlet:
      context-path: /management
  endpoints:
    web:
      base-path: /manage
server:
  port: 9080
```

should display the monitoring at "http://localhost:9081/management/manage" but does so at "http://localhost:9081/manage", seems to disregard the "management.server.servlet.context-path" property.

For this other configuration:
```
spring:
  webflux:
    base-path: /demowebflux
management:
  endpoints:
    web:
      base-path: /manage
server:
  port: 9080
```
works correctly the endpoint "http://localhost:9080/demowebflux/manage".

attached demo reproducing the problem.

[demoWebflux.zip](https://github.com/spring-projects/spring-boot/files/5062139/demoWebflux.zip)
