### ISSUE TITLE
Can not set Jackson DEFAULT_VIEW_INCLUSION using application properties YAML file

### ISSUE THREAD

**Issue by monstrfolk** [spring-projects/spring-boot#22977]
Using Spring Boot Webflux 2.2.5 and JsonViews can not set Jackson DEFAULT_VIEW_INCLUSION  to true using application properties YAML file.

```
spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
```
