### ISSUE TITLE
configuration properties `R2dbcProperties.pool` are not bound

### ISSUE THREAD

**Issue by serajin00** [spring-projects/spring-boot#23069]
With this application.yaml ...
```
spring:
  r2dbc:
    url: "..."
    pool:
      initial-size: 5
      validation-query: "SELECT 1"
```

the actual `R2dbcProperties.pool` fields are not bound. (all values remains as defaults)

![image](https://user-images.githubusercontent.com/8372905/91125977-ec02f880-e6dd-11ea-9675-e6f3e427382d.png)

tested spring boot versions: `2.3.2.RELEASE`, `2.3.3.RELEASE`
