### ISSUE TITLE
Sort dependency upgrades in changelog

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#23484]
Now that https://github.com/spring-io/github-changelog-generator/issues/34 is implemented, It would be great if dependency upgrades were sorted in the changelog as I feel it would be easier for folks to identify dependency upgrades they're interested in.

**Comment by snicoll** [comment]
Unfortunately we can't just ask the changelog generator to sort the dependency upgrades section. As soon as we have an opinion, we lost the default sections and we have to copy over [the defaults](https://github.com/spring-io/github-changelog-generator/blob/167cc5d986d87be4a9781bb6e3489044bdcae163/src/main/java/io/spring/githubchangeloggenerator/ChangelogSections.java#L44-L47). I guess it's not so bad to have our own configuration file for this but flagging for team attention to get some more feedback.

**Comment by snicoll** [comment]
For the record, the following file does the trick:

```yaml
changelog:
  repository: spring-projects/spring-boot
  sections:
    - title: ":star: New Features"
      labels:
        - "type: enhancement"
    - title: ":beetle: Bug Fixes"
      labels:
        - "type: bug"
        - "type: regression"
    - title: ":notebook_with_decorative_cover: Documentation"
      labels:
        - "type: documentation"
    - title: ":hammer: Dependency Upgrades"
      sort: "title"
      labels:
        - "type: dependency-upgrade"
```
