### ISSUE TITLE
How to load sub yml config file use spring.profiles.group property?

### ISSUE THREAD

**Issue by blling** [spring-projects/spring-boot#24309]
Spring-Boot Version: 2.4.0

When migrate from spring.profiles.include to spring.profiles.group, Spring-Boot no longer load sub `yml` configs from the classpath.

application.yml
```yml
spring:
  profiles:
    group:
      - base-db
      - base-quartz
      - base-app
```
main resource:
![image](https://user-images.githubusercontent.com/26540808/100832481-ee29df80-34a2-11eb-9655-1ec4d63bf498.png)

application-test.yml
```
spring:
  profiles:
    group:
      - test-db
      - test-quartz
      - test-app
```
test resource:
![image](https://user-images.githubusercontent.com/26540808/100832436-d2263e00-34a2-11eb-95c2-5c23b6856e90.png)

log shows Spring-Boot only load `application.yml` and `application-test.yml`, but no `base-db`, `base-quartz`, `base-app`,`test-db`, `test-quartz`, `test-app`：
```text
2020-12-02 13:22:07.463 TRACE  [main] org.springframework.boot.context.config.ConfigDataEnvironment Adding imported property source 'Config resource 'classpath:/application-test.yml' via location 'optional:classpath:/''
2020-12-02 13:22:07.463 TRACE  [main] org.springframework.boot.context.config.ConfigDataEnvironment Adding imported property source 'Config resource 'classpath:/application.yml' via location 'optional:classpath:/''
```

If run with `--spring.profiles.active=test`, Spring-Boot should also load `base-db`, `base-quartz`, `base-app`,`test-db`, `test-quartz`, `test-app` too, am i right?

**Comment by philwebb** [comment]
You need to include the source profile as part of the group property (see https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-profiles-groups). For example:

```yaml
spring:
  profiles:
    group:
      test:
      - test-db
      - test-quartz
      - test-app
```

For the `base-` profiles you probably want the following since they're always active:

```yaml
spring:
  profiles:
    include:
    - base-db
    - base-quartz
    - base-app
```

**Comment by blling** [comment]
Thanks，how does test-* inherit base-*?

**Comment by philwebb** [comment]
I think the example I included should so that. If not, please ask the question on stackoverflow.com with a small sample app. If you post a link to the question here, I'll try to answer it on stackoverflow. We prefer to keep the issue tracker just for bugs.

**Comment by blling** [comment]
@philwebb Thinks!
Finally, `application-test.yml` worked use the config as follows:
```yml
spring:
  profiles:
    group:
      test:
        - base-app
        - base-db
        - base-quartz
      base-app: test-app
      base-db: test-db
      base-quartz: test-quartz
```
The inheritance relationship on the configuration looks a bit strange, but it works.
