### ISSUE TITLE
Spring Boot 2.4.0 not using Spring Cloud Config properties

### ISSUE THREAD

**Issue by mrksph** [spring-projects/spring-boot#24312]
I have a Spring Boot app that I just migrated from 2.3.6 to 2.4.0. After deploying my app to my DEV environment I don't see it pulling its configuration from my Spring Cloud Config Server (Git repo). After searching I find that with the new release I have to add a new dependency (spring-cloud-starter-bootstrap). Now it reads from the Spring Cloud Config Server but it's not using the properties from the file.

I have 2 resources files a application.yml and a bootstrap.yml

This is my bootstrap.yml:

```
spring:
  application:
    name: jquest
  cloud:
    config:
      enabled: true
      fail-fast: false
      uri: http://config-service:8080
      retry:
        max-interval: 6000
        max-attempts: 10
        initial-interval: 6000

```

Do I have to add something to my application.yml file so my Spring Boot app uses the properties from the fetched configuration??

Thanks
