### ISSUE TITLE
Cloud Config issue after upgrade to Springboot 2.4.2 and Cloud 2020.0.0

### ISSUE THREAD

**Issue by ankitkhujneri** [spring-projects/spring-boot#25494]
I am facing an issue with Cloud Config after Springboot upgrade. I am using native search locations for loading various properties and yamls. This configuration has stopped working after upgrade. 
```
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      use-legacy-processing: true
      server:
         native:
            searchLocations:  
               - classpath:/config
               - /filesystem_path1/
               - /filesystem_path1/
```
             
When a Cloud config client sends the request to fetch resources from Config Server, I see the following error on Config server
`Resolved [org.springframework.cloud.config.server.environment.FailedToConstructEnvironmentException: Could not construct context for config=eureka_client,propfile1,propfile2 profile=local label=null includeOrigin=true; nested exception is java.lang.NullPointerException]`
