### ISSUE TITLE
Provide SNI functionality for ssl autoconfiguration

### ISSUE THREAD

**Issue by sokomishalov** [spring-projects/spring-boot#26022]
It would be great and useful to have such functionality out-of-box. 
I'm not sure if all web-server implementations support SNI, but [tomcat](https://stackoverflow.com/a/60555197/5843129) and [reactor-netty](https://github.com/reactor/reactor-netty/pull/1278) support it.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, @sokomishalov. How would you expect to configure the auto-configuration if it supported SNI? I'm wondering what you had imagined the configuration properties would be so that you can provide multiple key stores and map each to a host pattern.

**Comment by sokomishalov** [comment]
Thanks for the quick reply, @wilkinsona!
Well, I suppose it could be looked like that:

```yaml
server:
  ssl:
    enabled: true
    key-store: /path/to/key-store
    key-store-password: foobar
    sni:
      - mapping: foo.example.com
        ssl:
          key-store: ${server.ssl.key-store}
          key-store-password: ${server.ssl.key-store-password}
          key-alias: foo
      - mapping: bar.example.com
        ssl:
          key-store: ${server.ssl.key-store}
          key-store-password: ${server.ssl.key-store-password}
          key-alias: bar
```

If you'd want to use SNI, you still have to set up a fallback SSL context in that rare case when the user's client does not support SNI.
I'm not sure if it's ok to reuse SSL properties in that recursive way or just to provide new higher-level property for SNI mappings inside `ServerProperties`, but I think it could be possible to reuse `Ssl`-properties POJO somehow.
