### ISSUE TITLE
"spring.profiles.include" bug in spring boot 2.4

### ISSUE THREAD

**Issue by LichKing-lee** [spring-projects/spring-boot#26204]
hello.

migration guide
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide#profile-activation

sample 1 - normal case
```
spring:
  config:
    activate:
      on-profile: local
  profiles:
    include: kakaopay1,kakaopay2
```

The sample 1 throw `InactiveConfigDataAccessException`

sample 2 - bug case
```
spring:
  config:
    activate:
      on-profile: local
  profiles:
    include:
      - kakaopay1
      - kakaopay2
```

The sample 2 dose not throw `InactiveConfigDataAccessException`
sample 2 has active profiles. `local,kakaopay1,kakaopay2`

I found it in spring boot 2.4.3. it is also in 2.4.5.

thank you.
