### ISSUE TITLE
Support for Mongo Replica Set

### ISSUE THREAD

**Issue by lazee** [spring-projects/spring-boot#2624]
The spring data project has support for setting `ReplicaSetSeeds` via the `MongoFactoryBean`.

It would be nice to be able to configure this via the mongo-autoconfigurer in the properties file along with the other mongo stuff.

http://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/core/MongoFactoryBean.html#setReplicaSetSeeds-com.mongodb.ServerAddress:A-

http://docs.mongodb.org/manual/replication/

**Comment by aheusingfeld** [comment]
@lazee I had the same request and was actually going to prepare a pull-request until I saw that apparently you can configure a replicaSet via the "uri" parameter. See https://github.com/spring-projects/spring-boot/blob/3048f44a964ab2390dff26f0818c941ba40bdc56/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/mongo/MongoPropertiesTests.java#L109

**Comment by lazee** [comment]
@aheusingfeld Nice! I will test that now.

If this works the mongodb documentation in boot should be updated with info about this I think. A common scenario.

**Comment by aheusingfeld** [comment]
I tested it yesterday and it worked right away with a local replicaset.

**Comment by lazee** [comment]
Thank you

**Comment by lazee** [comment]
Then its just a matter of documenting this

**Comment by lazee** [comment]
@aheusingfeld Do you have an example on how you did this? I have tried to configure uri instead of port and host, but I can't get it to work.

**Comment by aheusingfeld** [comment]
I had to modify the domain names but this is what I am using:
```
spring:
  profiles: production
  data:
    mongodb:
      uri: mongodb://vgm37.dc1-example.com:27017,vgm38.dc1-example.com:27017,vgm19.dc2-example.com:27019,vgm20.dc2-example.com:27020,vgm20.dc2-example.com:27021/test-db
```
