### ISSUE TITLE
Add supports for log4j2 composite configuration

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#27110]
https://logging.apache.org/log4j/2.x/manual/configuration.html#CompositeConfiguration

Here is my use case, I want output logs to ELK in production, so I add extra `log4j2-kafka-appender.xml` beside `log4j2.xml`.
I need merge two files without composite configuration supports, which will make configuration redundant.

```yaml
logging:
  config: classpath:log4j2.xml

---
spring:
  config.activate.on-profile: prod
logging:
  config: classpath:log4j2.xml,classpath:log4j2-kafka-appender.xml
```
