### ISSUE TITLE
Regarding disabling AopAutoConfiguration when using @EnableAspectJAutoProxy

### ISSUE THREAD

**Issue by hongji3354** [spring-projects/spring-boot#27375]
While testing Spring proxy, an incomprehensible problem appeared.

To test JDK Dynamic proxy, we used @EnableAspectJAutoProxy's proxyTargetClass as false, but we still used CGLIB.

When I looked up the data, I found out that the following properties should be added to the application.yml for normal operation.

```yaml
spring:
  aop:
    auto: false
    proxy-target-class: false
```

I used @EnableAspectJAutoProxy, but I think it should be disabled when using @EnableAspectJAutoProxy because it can be confusing to manually turn off auto settings.
