### ISSUE TITLE
Provide a configuration property for configuring a distribution statistic's expiry

### ISSUE THREAD

**Issue by hadjiski** [spring-projects/spring-boot#27477]
This is a way to auto-configure client percentiles
```
management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.9
```
which ends up in [this place](https://github.com/spring-projects/spring-boot/blob/47516b50c39bd6ea924a1f6720ce6d4a71088651/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/PropertiesMeterFilter.java#L83), without capability to set `expiry`.

Why not adding the capability to configure also the sliding window of the quantile, which currently seems to be [defaulting to 2m](https://github.com/micrometer-metrics/micrometer/blob/b36be492f8a77a857e0be2f6d4443a5abcf44ffc/micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java#L42)
