### ISSUE TITLE
Using spring cloud config, Profile groups not working

### ISSUE THREAD

**Issue by han1448** [spring-projects/spring-boot#27530]
# Overview
I'm using spring boot application with cloud config.
I tried to use profile groups but it doest not work that i expected. (I'm not sure it is a correct behavior or not)

- SpringBoot : 2.4.5
- Spring Cloud : 2020.0.2

# Case 
### Application Config
`bootstrap.yaml`
```yaml

spring:
  application:
    name: my-app

  cloud:
    config:
      uri: http://localhost:8080
      username: test
      password: test
      fail-fast: true
      label: dev

---
spring:
  cloud:
    config:
      label: dev
  config:
    activate:
      on-profile: default,test


---
# Stage profile
spring:
  cloud:
    config:
      label: stage
  config:
    activate:
      on-profile: stg

---
# Production profile

spring:
  cloud:
    config:
      label: master
  config:
    activate:
      on-profile: prod

```

### Cloud Config
When I use `spring.profiles.include`, it works fine but group does not work for me.
`application.yaml`
```yaml
spring:
  application:
    name: my-app

  profiles:
#    include: "profileA,profileB,profileC".  => This works!
    group:  => This does not work!
      default:
        - "profileA"
        - "profileB"
        - "profileC"
```

`application-default.yaml`
```yaml
my: value
```

```
// Result
The following profiles are active: default

// my expectation!
The following profiles are active: default,profileA,profileB,profileC
```

FYI, When I added `spring.profiles.group` in `bootstrap.yaml` in my application side, then it works.
`bootstrap.yaml`
```yaml

spring:
  application:
    name: my-app

  profiles:
    group:
      default:
        - "profileA"
        - "profileB"
        - "profileC"

```
But I would like to separate the code and configuration.
How can i use `spring.profiles.gruop` in my cloud config?
