### ISSUE TITLE
cannot config multiple eureka urls for multiple profiles in one file

### ISSUE THREAD

**Issue by m1well** [spring-projects/spring-boot#27548]
I want to call my config-server named-base via my eureka. For that I need the eureka url in the default part to start the app.

But then if I want to provide different URLs for different profiles, I get an error.

```
Failed to bind properties under 'eureka.client.serviceurl.defaultzone' to java.lang.String:

    Property: eureka.client.serviceurl.defaultzone
    Value: http://other-host:8760/eureka/
    Origin: class path resource [application.yml] - 53:20
    Reason: org.springframework.boot.context.config.InactiveConfigDataAccessException: Inactive property source 'Config resource 'class path resource [application.yml]' via location 'optional:classpath:/' (document #2)' imported from location 'class path resource [application.yml]' cannot contain property 'eureka.client.serviceurl.defaultzone' [origin: class path resource [application.yml] - 51:20]

Action:

Update your application's configuration
```

this is my application.yml

```yaml
spring:
  application:
    name: app
  cloud:
    config:
      discovery:
        enabled: true
        service-id: common-cloud-config
      fail-fast: true
      retry:
        max-attempts: 5

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: false
    hostname: 127.0.0.1

application:
  value: app-default

security:
  value: app-sec-default

---

spring:
  config:
    activate:
      on-profile: dev
    import: "configserver:"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

---

spring:
  config:
    activate:
      on-profile: qa
    import: "configserver:"

eureka:
  client:
    serviceUrl:
      defaultZone: http://other-host:8760/eureka/ # this is line 53 in the exception 

```

before the spring boot 2.4 update, I did this in my `bootstrap.yml` without any problems....

does my file have any mistakes or is this just not possible any more??
