### ISSUE TITLE
Provide a way to share default properties between applications

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#27544]
Assume there are two applications "foo" and "bar", both have dependency "core", I want extract the common properties for better maintainability.
current:
```yaml
--- #application.yml from foo
spring.application.name: foo
spring.datasource.url: jdbc:mysql://${mysql.host}:${mysql.port}/${spring.application.name}
mysql:
  host: localhost
  port: 3306

--- #application.yml from bar
spring.application.name: bar
spring.datasource.url: jdbc:mysql://${mysql.host}:${mysql.port}/${spring.application.name}
mysql:
  host: localhost
  port: 3306
``` 
expected:
```yaml
--- #default.yml from core
spring.application.name: bar
spring.datasource.url: jdbc:mysql://${mysql.host}:${mysql.port}/${spring.application.name}
mysql:
  host: localhost
  port: 3306

--- #application.yml from foo
spring.application.name: foo

--- #application.yml from bar
spring.application.name: bar
```

above `default.yml` should override spring boot (including devtools) defaults and could be overridden by `application.yaml`

My solution:
```java
public class DefaultPropertiesPostProcessor implements EnvironmentPostProcessor, Ordered {

	private static final String FILE_NAME = "default.yml";

	public static final int ORDER = Ordered.HIGHEST_PRECEDENCE + 11; // after ConfigDataEnvironmentPostProcessor

	@Override
	public int getOrder() {
		return ORDER;
	}

	@Override
	public void postProcessEnvironment(ConfigurableEnvironment environment, SpringApplication application) {
		try {
			List<PropertySource<?>> list = new YamlPropertySourceLoader()
					.load(FILE_NAME, new ClassPathResource(FILE_NAME)).stream().filter(ps -> {
						String onProfile = (String) ps.getProperty("spring.config.activate.on-profile");
						return onProfile == null || environment.acceptsProfiles(Profiles.of(onProfile));
					}).collect(Collectors.toList());
			Collections.reverse(list);
			list.forEach(environment.getPropertySources()::addLast);
		} catch (IOException e) {
			throw new RuntimeException(e.getMessage(), e);
		}
	}

}

```
I'm not sure it's the best practice, I wish spring boot will provide equivalent.
