### ISSUE TITLE
Document the scalar types supported by MapBinder

### ISSUE THREAD

**Issue by polarbear567** [spring-projects/spring-boot#27581]
When the value of the map is of type java.time.Duration(According to the source code, it seems that this problem exists for non Java.lang class types), it will not be mapped correctly if "[]" is not used on the key which has the dot in the yaml file.
Just like this:
```
leo:
  yyy:
    expiry: #Map<String, Duration>
      "[http.server.requests]": 5ms   # it's fine
      http.server.request: 5ms    # don't work
    integer-test:
      "[http.server.requests]": 3   # it's fine
      http.server.request: 4    # it's fine
```
If the value type in map is Integer or Boolean or other types of java.lang, their keys can be mapped correctly without brackets.
If it is confirmed that it is a bug and can make relevant suggestions, I will be very happy to fix it.
Here is the test case:
[Case](https://github.com/polarbear567/for-springboot-test)
