### ISSUE TITLE
Add quantile calculation for requests with @PathVariable

### ISSUE THREAD

**Issue by VovkaSOL** [spring-projects/spring-boot#27630]
Hi, i have problem with configure percentiles(quantiles) for actuator/metrics/prometheus endpoint for http requests **with @PathVariable**

if i enable 

```yaml
management:
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: 0.5,0.75,0.95,0.99,0.999
```

i see this:
![image](https://user-images.githubusercontent.com/52788297/129039578-113cd5d2-4a20-4d82-9248-938dca46f2d9.png)
(quantiles calculated only for requests without @PathVariable, not calculated for /matching). If i create custom WebMvcTagsProvider, quantile not calculated too.
Please add quantile calculation for requests with @PathVariable. Thanks
