### ISSUE TITLE
Support autoconfigure additional redis instances

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#27834]
It's common to connect multiple redis servers in the sample application, currently It's not easy to reuse `RedisAutoConfiguration` and `LettuceConnectionConfiguration` to create multiple redis related beans, I hope spring-boot could handle this just by adding a few properties, for example:
```yaml
# primary redis
spring.redis:
  host: localhost
  port: 6379

# additional redis instances
spring.redis.additional-instances: foo,bar
foo.redis:
  host: localhost
  port: 6379
  database: 1
bar.redis:
  host: localhost
  port: 6379
  database: 2
```
default redis related beans should be `@Primary`
```java
// default redis
@Autowired RedisTemplate redisTemplate;
@Autowired RedisTemplate stringRedisTemplate;

// foo redis
@Autowired RedisTemplate fooRedisTemplate;
@Autowired RedisTemplate fooStringRedisTemplate;

// bar redis
@Autowired RedisTemplate barRedisTemplate;
@Autowired RedisTemplate barStringRedisTemplate;
```
