### ISSUE TITLE
can not get the merged configuration for List type from  multiple yml properties file

### ISSUE THREAD

**Issue by crazylulululu** [spring-projects/spring-boot#27936]
I have multiple datasource , so the type is list , the original configuration is OK , as follows:

**the application.yml ：**

```yaml
test:
  db:
    datasources:
      - url: jdbc:mysql://localhost:3306/writedb
        username: root
        password: root
      - url: jdbc: mysql://localhost:3306/readdb
        username: root
        password: root
```

Now ,we must extract username/password to special documents, as follows , I can not get the merged Information

**change the the application.yml ：**

```yaml
test:
  db:
    datasources:
      - url: jdbc:mysql://localhost:3306/writedb
      - url: jdbc:mysql://localhost:3306/readdb
```

**the application-secrets.yml :**

```yaml
test:
  db:
    datasources:
      - username: root
        password: root
      - username: root
        password: root
```

```java
@ConfigurationProperties(prefix = "test.db")
@Configuration
public class AutoLoadDataSourceProperties {

    private List<DataSourceCommonProperties> datasources;	
	
	// get
        // set
}
```

when start the application , the url is null (but through the Environment.getProperty("test.db.datasources[0].url")  ,can get the value ) ,  How to solve this problem ,Thanks

**Comment by wilkinsona** [comment]
@crazylulululu I have updated your comment to improve the formatting. You can learn how to do so yourself in [GitHub's Markdown guide].

**Comment by wilkinsona** [comment]
The lack of merging is [intentional](https://docs.spring.io/spring-boot/docs/2.5.x/reference/htmlsingle/#features.external-config.typesafe-configuration-properties.merging-complex-types). I would recommend that you use property placeholders instead:

```yaml
test:
  db:
    datasources:
      - url: jdbc:mysql://localhost:3306/writedb
        username: ${test.db.datasources.write.username}
        password: ${test.db.datasources.write.password}
      - url: jdbc: mysql://localhost:3306/readdb
        username: ${test.db.datasources.read.username}
        password: ${test.db.datasources.read.password}
```

```yaml
test:
  db:
    datasources:
      write:
        username: root
        password: root
      read:
        username: root
        password: root
```

If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
