### ISSUE TITLE
Allow embedded Mongo to be used at runtime, backing off when spring.data.mongodb.uri is set

### ISSUE THREAD

**Issue by SujanKumarMitra** [spring-projects/spring-boot#28149]
**Context**:
We can use the H2 database if we don't want to connect to a real DB during developments. I want the same functionality for Embedded MongoDB as well.

**Problem**:
If we add embedded MongoDB dependency, but remove the test scope, then even if a real database URI value is given in `spring.data.mongodb.uri`, the `EmbeddedMongoAutoConfiguration` ignores that and connects to the embedded one

**Proposal**:
Allow EmbeddedMongoAutoConfiguration to back-off, when `spring.data.mongodb.uri` property is present

**Comment by odrotbohm** [comment]
Moved to Boot as per @christophstrobl's request.

**Comment by ztomic** [comment]
You can disable EmbeddedMongoAutoConfiguration with application configuration for workaround:

```yaml
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
```
