### ISSUE TITLE
MeterValue with "d" suffix not parsed as Duration for timer

### ISSUE THREAD

**Issue by bespaltovyj** [spring-projects/spring-boot#28302]
Spring Boot Version 2.4.8

If you specify a value with the suffix `d` for the timer when setting slo, then it is parsed as a number, not a duration.

Example:

```yaml
management:
  metrics:
    distribution:
      slo:
        <YOUR_TIMER_NAME>: 1d, 2d, 3d
```

The values of the baskets will be `1, 2 ,3`, but required `86400s, 172800s, 259200s`.

[test example](https://github.com/bespaltovyj/spring-boot/commit/a3b435831c3eb80de88ff568b4431e771a16b513)

To work around this problem, I specify the duration in hours.
