### ISSUE TITLE
Add AutoConfiguration to Spring Kafka's Retry Topic Feature

### ISSUE THREAD

**Issue by tomazfernandes** [spring-projects/spring-boot#28450]
This is a proposal for enabling auto configuration for the delayed non-blocking retries using topics feature that we introduced earlier this year on Spring for Apache Kafka 2.7.0.

More details on the feature can be found in the documentation: https://docs.spring.io/spring-kafka/docs/current/reference/html/#retry-topic

I already have a working draft with tests and should open a PR shortly so we can discuss it in more details if necessary.

The minimal configuration would be as simple as adding `spring.kafka.retry-topic-enabled=true` to the application yaml or properties configurations file, which would apply a default global retry configuration to all topics.

```
spring:
  kafka:
    retry-topic-enabled: true
```

With that minimal configuration, the framework would set up topics and consumers with the following defaults:

- Retries for all topics
- 3 processing attempts before sending the message to the DLT
- FixedBackOffPolicy of 1 second between attempts
- Default topic suffixes of "-retry-1", "-retry-2", "-dlt"
- Create the retry topics and dlts automatically via NewTopic instances
- Retry on all exceptions
- Use a dedicated default ConcurrentKafkaListenerContainerFactory instance provided by the auto configuration specifically for creating the retry topics and dlt consumers
- Use the default Spring Kafka's KafkaTemplate from auto configuration for forwarding the messages to the topics

More specific configurations could also be provided in the configuration files, such as:

```
spring:
  kafka:
    retry-topic-enabled: true
    retry-topic:
      myGlobalConfiguration:
        attempts: 4
        back-off:
          delay: 300s
          multiplier: 2
          max-delay: 1200s
        topic-suffixing-strategy: suffix-with-index-value
        dlt-strategy: fail-on-error
```

Optionally, more than one configuration could be provided for more fine-grained control over the configuration:
```
spring:
  kafka:
    retry-topic-enabled: true
    retry-topic:
      myGlobalConfiguration:
        attempts: 4
        back-off:
          delay: 300s
          multiplier: 2
          max-delay: 1200s
        topic-suffixing-strategy: suffix-with-index-value
        dlt-strategy: fail-on-error
        exclude-topics: my-specific-topic
     mySpecificConfiguration:
        include-topics: my-specific-topic
        attempts: 5
        back-off:
          delay: 5s
        not-retry-on:
          - com.mycompany.myproject.mypackage.exceptions.MyException
          - com.mycompany.myproject.mypackage.exceptions.MyOtherException
        topic-suffixing-strategy: suffix-with-index-value
        dlt-strategy: fail-on-error
```

Note: If it gets too verbose for many topic configurations the user should be able to provide that in one or more separate configuration files using standard spring boot configuration features such as `spring.config.import`.

I'd appreciate any feedback you may have on this. Also please let me know if there are any questions or anything I can help with.

@garyrussell and @artembilan, I'd much appreciate your feedback too if and when possible.

Thank you all for the hard work you put into the awesome Spring projects!

**Comment by tomazfernandes** [comment]
> I'm not sufficiently familiar with Spring Kafka's programming model to know which of these would be more aligned with the rest of its API, but I think either would be preferable to defining multiple `RetryTopicConfiguration` beans, both from the perspective of Spring Boot's auto-configuration and of users who are configuring things themselves programatically.

Spring Kafka uses the Configurer / Registrar / Registry approach for processing the `@KafkaListener` annotations, and then registering the endpoints and creating the containers. The other way you can create and configure listeners is by manually creating them, instantiating either the container or a `ListenerContainerFactory` directly.

If I understand correctly, in this pattern the Registry does the actual processing, with the Configurer using a Visitor pattern to apply customizations to the Registry before processing begins.

For the RetryTopic setup, when the `KafkaListenerAnnotationBeanPostProcessor` is processing an `@KafkaListener`  bean, the `RetryTopicConfigurationProvider` tries to provide a configuration instance for the topics currently being processed, either from those registered in the application context or from a `@RetryableTopic` annotation in the `@KafkaListener` annotated method. If a configuration for the given topics is found, it will then be processed by a different class that orchestrates the retry and dlt endpoints registration.

Considering the RT configuration processing itself is already being handled by a separate class that expects to receive the proper RTC instance, it might make more sense to go with the repository approach, having a repository bean that would be looked up by the RTCProvider when attempting to provide the configuration. Makes sense?

Following the pattern in ClientConfigurationRepository, we might have:

```
public interface RetryTopicConfigurationRepository {

    @Nullable RetryTopicConfiguration findByTopicNames(Collection<String> topics)

}
```

**Comment by tomazfernandes** [comment]
Actually, I see there are cases in which the registry seems to have a more active role (KafkaListenerEndpointRegistry, LoggingMeterRegistry) and cases when it has more of a passive role (InterceptorRegistry, ResourceHandlerRegistry). I'm not really familiar with these configuration approaches, I'll keep looking into them.

**Comment by tomazfernandes** [comment]
Thanks a lot @wilkinsona for the examples, I've drafted how the solution would be with each of them and they both lead to solid designs!

After considering what's been presented, I'd like to propose a different approach for the auto configuration. If we decide to proceed with this, we can extend this approach to users who prefer to do it programmatically in Spring Kafka, which would also help to keep the bulk of the configuration logic there.

As @garyrussell suggested, I'll start with the simplest example and work my way up from there.

The simplest one would still be:
```
spring:
  kafka:
    retry-topic-enabled: true
```

This would set up the feature with sensible defaults that would be applied to all topics. We can discuss those defaults later if the current ones are not ideal.

The user would be able to override the defaults with, for example:
```
spring:
    kafka:
        retry-topic-enabled: true
        attempts: 5
        back-off:
            delay: 1s
            multiplier: 2
            max-delay: 3s
```

Gone are the groups as @artembilan suggested - these overrides would apply to all topics.

If the user wants to override configurations for specific topics, we could have:

```
spring:
    kafka:
        retry-topic-enabled: true
        attempts: 5
        back-off:
            delay: 1s
            multiplier: 2
            max-delay: 3s
        topic-overrides:
            my-specific-topic:
                dlt:
                    class: com.mycompany.myproject.mypackage.MyOtherDltHandlerClass
                    method: otherXyz
            my-specific-topics:
                matching: *-specific-topics-suffix   
                back-off:
                    delay: 2s
```

This way I think we get a smaller and more intuitive contract.

How do you guys feel about that, does it look like a good fit for auto configuration?

Thanks!
