### ISSUE TITLE
How can I rewrite connectionfactory correctly

### ISSUE THREAD

**Issue by wang-xiaowu** [spring-projects/spring-boot#28587]
- ConnectionFactoryConfig
```
@Bean
    public ConnectionFactory connectionFactory(@Autowired MyR2dbcProperties r2dbcProperties) {
    ...
    return connectionFactory;
}
```
- application.yml
```
behappy:
  r2dbc:
    host: localhost
    username: root
    password: root
    port: 3306
    database: bin-springreactive
    pool:
      name: r2dbc_pool_product
      validation-depth: local
server:
  port: 8080
spring:
  application:
    name: @project.artifactId@
#  main:
#    allow-bean-definition-overriding: true
```

↓
```
Description:

The bean 'connectionFactory', defined in class path resource [org/xiaowu/behappy/common/r2dbc/config/R2dbcEntityTemplateConfigure.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/r2dbc/ConnectionFactoryConfigurations$Pool.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

```

I have to configure to allow java bean overrides(allow-bean-definition-overriding: true) ,is that right?
