### ISSUE TITLE
Document how to configure global logging level

### ISSUE THREAD

**Issue by jmisur** [spring-projects/spring-boot#2872]
Hi in http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html there is simple sample of logging of specific package. It would be nice to add note how to set global (root) level, since especially with using YAML file it's not quite intuitive. Only following examples worked for me:

##### application.properties:
```
logging.level.=ERROR
or 
logging.level.: ERROR
```
this does **not** work: `logging.level.*=ERROR`

##### application.yaml:
```
logging:
  level:
    '': ERROR
    org:
      springframework: INFO
```
or 
```
logging:
  level.: ERROR
  level:
    org:
      springframework: INFO
```

this does **not** work:
```
logging:
  level:
    .: ERROR
    org:
      springframework: INFO
```
```
logging:
  level:
    '*': ERROR
    org:
      springframework: INFO
```
```
logging:
  level.*: ERROR
  level:
    org:
      springframework: INFO
```

Using v1.2.3.
