### ISSUE TITLE
Actuator Info from application configuration missing after update to 2.6

### ISSUE THREAD

**Issue by eidottermihi** [spring-projects/spring-boot#28938]
My application is including custom information in the `/actuator/info` endpoint (as described here: https://www.baeldung.com/spring-boot-info-actuator-custom#static-properties-in-info).

application.yml:
```yml
management:
 endpoints:
    enabled-by-default: false
    web:      
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      probes.enabled: true
    info:
      enabled: true

# Additional metadata for /actuator/info Endpoint
info:
  mycustominfo: mycustomvalue
```

After updating from 2.5.6 to 2.6.1 the `mycustominfo` Property is no longer included in the response of `/actuator/info`.

The Release Notes only state that the "Env Info" contributor is disabled by default (https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#actuator-env-infocontributor-disabled-by-default).

When this contributor is explicitely enabled again, the behavior of 2.5.6 is restored:

```yml
management:
  info:
    env:
      enabled: true
```

However, I think this a bug, because the "Env Info" contributor is about providing system environment variables, and should therefore not have influence on custom info properties.
