### ISSUE TITLE
spring.config.import is not overriding values for multi-document files

### ISSUE THREAD

**Issue by joca-bt** [spring-projects/spring-boot#29272]
`spring.config.import` seems to not be working properly when working with multi-document files (either that or with `spring.config.activate.on-profile`, not sure who is the culprit).

I have a Spring Boot application that doesn't do anything and has the following application properties files:

`application.yaml`:
```
spring.config.import: 'application-overrides.yaml'

server:
  port: 443

---

spring.config.activate.on-profile: 'development'

server:
  port: 8443
```

`application-overrides.yaml`:
```
server:
  port: 9999
```

```> mvn spring-boot:run -Dspring-boot.run.profiles=development``` runs on port 8443 instead of 9999. The `server.port` override is not being applied. If I remove the document for `spring.config.activate.on-profile: 'development'` it will run on port 9999.

According to the [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.files.importing), the properties from `application-overrides.yaml` should override the ones from `application.yaml` in my example.

I was wondering if doing the following would help but it doesn't:

`application-overrides.yaml`:
```
spring.config.activate.on-profile: 'development'

server:
  port: 9999
```
