### ISSUE TITLE
Spring Naming Strategy works unexpectedly for column with single char in the end

### ISSUE THREAD

**Issue by daggerok** [spring-projects/spring-boot#29933]
Hello Spring Data team! Off topic: You are awesome!

We are using `spring-data-jpa` with spring naming strategy and we found bug when its generating a column name for entity with property ends with single char, like for example:
- `myTypeA` which I'm expecting should result into `my_type_a`
- or `myTypeB` => `my_type_b`

```yaml
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
```

Spring Data JPA Entity

```kotlin
@Entity
data class MyEntity(

    @Id
    @GeneratedValue(strategy = IDENTITY)
    val id: Long? = null,

    // @Column(name = "my_type_a") // when @Column annotation is commented resulted in my_typea
    val myTypeA: String = "",

    // @Column(name = "my_type_b") // when @Column annotation is commented resulted in my_typeb
    val myTypeB: String = "",
)
```

I'm **expecting** that `myTypeA` and `myTypeB` will be resulted into `my_type_a` and `my_type_b`,
but **actual** values are `my_typea` and `my_typeb`

If you look at `org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy#apply` method, you can see:
<img width="919" alt="image" src="https://user-images.githubusercontent.com/2445604/155023019-f7bba1c2-093b-499a-9e28-38d0839a72d1.png">

that last char is simply ignoring

```java
isUnderscoreRequired(builder.charAt(i - 1), builder.charAt(i), builder.charAt(i + 1))
```

---
Environment:
- Spring Boot 2.5.9
- JDK 11

---
Regards,
Maksim
