### ISSUE TITLE
Add Single Logout to SAML 2.0 configuration properties

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-boot#30643]
SAML 2.0 Single Logout support [was added](https://docs.spring.io/spring-security/reference/servlet/saml2/logout.html) in Spring Security 5.6.

In order to activate the feature, each configured `RelyingPartyRegistration` [must set](https://github.com/spring-projects/spring-security/issues/10674) a `singleLogoutServiceLocation`. Currently, there is no way to provide the property using Spring Boot.

The configuration may look like this:

```yml
spring:
    security:
        saml2:
            relyingparty:
                one:
                    ...
                    slo:
                        location: /logout/saml2/slo
                        response-location: /logout/saml2/slo
                        binding: POST
                    identityprovider:
                        ...
                        singlelogout:
                            location: ...
                            response-location: ...
                            binding: POST
```
