### ISSUE TITLE
Spring cloud config server does not return properties after upgrade to 2.4.2 spring boot

### ISSUE THREAD

**Issue by kboczek** [spring-projects/spring-boot#30775]
Environment: 

Spring Boot: 2.4.2
Spring Cloud: 2020.0.0

Spring cloud config server configuration for service configuration repository

```
spring:
  cloud:
    config:
      server:
        git:
          repos:
            service:
              uri: ssh://${git.url}/service-config.git/
```

Repository _service-config.git_ has following structure of files on master branch:

```
application.yml
service-alfa.yml
service-beta.yml

```
Using spring boot 2.4.1 config service returns properties using following url: _https://${configServiceUrl}/service/alfa_ 

```
{
  "name": "service",
  "profiles": [
    "alfa"
  ],
  "label": null,
  "state": null,
  "propertySources": [
    {
      "name": "ssh://git.url/service_config.git//service-alfa.yml",
      "source": {
        "property": "value"
      }
    },
    {
      "name": "ssh://git.url/service_config.git//application.yml",
      "source": {
        "pro": "val"
      }
    }
  ]
}
```

but after upgrade to 2.4.2 spring cloud config service does not return properties and no exception is thrown like:

```
{
  "name": "service",
  "profiles": [
    "alfa"
  ],
  "label": null,
  "state": null,
  "propertySources": []
}
```

Based on release notes I can see that this change https://github.com/spring-projects/spring-boot/issues/24504 could introduce such behaviour.
