### ISSUE TITLE
Confirm gh-308 has not broken XD

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#309]
RC1 introduced a regression in the way that profiles are handled with property files (see #308).

The fix broke the `ConfigFileApplicationListenerTests.yamlProfileCanBeChanged` test. It looks to me like the test was at fault. It enabled the `prod` profile with a property, then loaded `testsetprofiles.yml`:

``` yaml

---
spring:
  profiles:
    active: dev
my:
  property: fromyamlfile

---
spring:
  profiles: dev
my:
  property: fromdevprofile
```

I read this file as saying always active the `dev` profile, however, the original test explicitly checked that only `prod` was active.

It appears that the test may have been added as part of #198 but I don't understand this issue so we should confirm that the latest fix has not broken XD.
