### ISSUE TITLE
Properties loaded by config server (import:configserver:) do not override local one

### ISSUE THREAD

**Issue by antechrestos** [spring-projects/spring-boot#30977]
Let's suppose I have a `application.yml`  file put just next to my jar. This file looks like

```yaml

spring:
  application:
    name: test-app
---
spring:
  config:
    activate:
      on-profile: production

some:
  default:
     value: ${SOME_DEFAULT_VALUE:false}

--- 
spring:
  config:
    activate:
      on-profile: config-server
    import: "configserver:"
  cloud:
    config:
      enabled: true
      uri: http://config-server.uri/config

```

and my config server serves a file named `test-app-extra-profile.yaml` containing

```yaml
some:
  default:
     value: true
```

Starting application without legacy processing, with profiles `production,config-server,extra-profile` results in `some.default.value` valued to `false`. 
I would have expected the contrary due to that

According to [documentation](https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4), 

> Imports can be considered as additional documents inserted just below the document that declares them

If so why my application keeps seeing value to `false`?

Naive question: why isn't the import inserted directly in the section that declares it?

For example, the process of property loading could be

* crawl `application.yml` and for each import, resolve its properties and insert it
* crawl the resolved `application.yml` according to the law *The later in the document the stronger*.

After watching the [following discussion](https://github.com/spring-projects/spring-boot/issues/29272), I would have expected this behaviour
