### ISSUE TITLE
Disable auto-detection in tests that start Hazelcast

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#31715]
Programmatically, it's something like:

```java
getAutoDetectionConfig().setEnabled(false)
```

In YAML:

```yaml
hazelcast:
  network:
    join:
      auto-detection:
        enabled: false
```

And in XML:

```xml
<hazelcast>
    ...
    <network>
        <join>
            <auto-detection enabled="false" />
            ...
        </join>
    </network>
    ...
</hazelcast>
```

When configured correctly, the node should log the following:

```
WARNING: [192.168.178.45]:5701 [dev] [4.2.5] No join method is enabled! Starting standalone.
```

We don't want to see this:

```
INFO: [192.168.178.45]:5701 [dev] [4.2.5] Using Multicast discovery
```
