### ISSUE TITLE
Spring boot profile group not picking the properties file 

### ISSUE THREAD

**Issue by vignesh-ragavan** [spring-projects/spring-boot#32204]
I have `application-database.yml`, `application-sql.yml`. Tried running using `-Dspring.profiles.active=local` but properties data not picking up. How to run this?

Is there any properties to activate profile group or only way to activate like this `-Dspring.profile.active=groupname`. I want to use profile group in `application-local`.

application-local.yml

```yaml
spring:
  profiles:
    group:
      Dev: database, sql, message
  application: 
    name: HP-FETCHER-CONFIG-SERVICE
```
