### ISSUE TITLE
ConfigurationProperties Binding of Map<String, Map<Object, Object> takes a significant time

### ISSUE THREAD

**Issue by sstarcher** [spring-projects/spring-boot#329]
When attempting to bind using Map<String, Map<Object, Object> I'm seeing a 20 second start up increase when a binding 400 properties.

Binding Map<String, String> binds in less then a second.  Map<String, Object> also binds correct and in less then a second.

An example structure.  At the c level I have ~380 properties.

```
a:
  b:
    c: blah
    c1: blah2
  b1: 
    c2: blah
    c3: blah
```
