### ISSUE TITLE
DataSourceJmxConfiguration ignores spring.jmx.enabled=false

### ISSUE THREAD

**Issue by Alterant-zz** [spring-projects/spring-boot#33336]
boot version 2.7.5

Simple app made with Initializr and spring-boot-starter-jdbc dependency.

In the application.yml I have:
```
spring:
  application:
    name: Somename
  aop:
    auto: false
  jmx:
    enabled: false
```

Starting the app with --debug flag shows in the logs:

   DataSourceJmxConfiguration matched:
      - @ConditionalOnProperty (spring.jmx.enabled=true) matched (OnPropertyCondition)
