### ISSUE TITLE
spring boot 3 profile property values getting overridden in boostrap.yml

### ISSUE THREAD

**Issue by miriyalajanardhan** [spring-projects/spring-boot#33464]
I have posted my problem here. Can someone please check.
https://stackoverflow.com/questions/74646071/spring-boot-3-profile-property-values-getting-overridden-in-boostrap-yaml

**Comment by scottfrederick** [comment]
Please do not cross-post between StackOverflow and GitHub issues. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. The SO post should be sufficient to get help.

**Comment by miriyalajanardhan** [comment]
Reposting the complete problem here, as this looks be a bug.

Recently trying to upgrade to Spring Boot 3, but facing property issue. My bootstrap yml looks like below, When I run with profile dev, the configserver url is always getting connected to qa, basically whichever is declared last.

This is working fine in 2.7.X version of spring, but not in spring boot 3
```
spring:
  application:
    name: appname
  profiles:
    active: ${spring.profiles.active}
    include:
      - global-defaults
    group:
      dev:
        - config-server-dev
        - cloud-config-dev
      qa:
        - config-server-qa
        - cloud-config-qa

---

spring:
  config:
    activate:
      on-profile: config-server-dev
  cloud:
    config:
      enabled: true
      uri: http://urltoconfigserverdev
      label: master

---

spring:
  config:
    activate:
      on-profile: config-server-qa
  cloud:
    config:
      enabled: true
      uri: http://urltoconfigserverqa
      label: master

---
```
But the same is working fine if add the property migration pom dependency. which is not suggested for higher environments.
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-properties-migrator</artifactId>
    <scope>runtime</scope>
</dependency>
```

I don't see any WARN in the startup logs either.
