### ISSUE TITLE
All Documents Added To Environment When Using Legacy Processing

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-projects/spring-boot#33523]
Using Boot 2.7.5 I have this application.yaml

```
spring:
  config.use-legacy-processing: true
  application:
    name: demo

logging:
  level:
    org.springframework.web: info

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: alt


logging:
  level:
    org.springframework.web: debug
server:
  port: 9696

```

I have no profile enabled when running the app but all 3 documents in this application.yaml are added to the environment when setting `use-legacy-processing` to `true`.

![CleanShot 2022-12-14 at 13 43 05@2x](https://user-images.githubusercontent.com/524254/207685614-ce66dbd2-5742-465b-8c5d-8b515995d072.png)

When I start the app I notice that Tomcat starts on `9696`.  When `use-legacy-processing` is not used the server starts on `8080`.

I have attached a sample project that reproduces the problem.
[demo-2.7.5.zip](https://github.com/spring-projects/spring-boot/files/10230764/demo-2.7.5.zip)

**Comment by scottfrederick** [comment]
With `spring.config.use-legacy-processing: true` you'll also need to use the legacy style of activating profiles with `spring.profiles` instead of `spring.config.activate.on-profile`: 

```
spring:
  config.use-legacy-processing: true
  application:
    name: demo

logging:
  level:
    org.springframework.web: info

---
spring:
  profiles: local

---
spring:
  profiles: alt

logging:
  level:
    org.springframework.web: debug
server:
  port: 9696
```
