### ISSUE TITLE
Fixed `working_dir` (`/workspace`) for native images

### ISSUE THREAD

**Issue by Azbesciak** [spring-projects/spring-boot#33850]
Hello,
For created images with `gradle bootBuildImage` it is impossible to set the `working_dir` via docker-compose.

example 
```yaml
version: '3'
services:
  demo-service:
    restart: "no"
    image: demo:0.0.1-SNAPSHOT
    working_dir: /my-dir
```
In the runtime Spring writes (this is not only console bug) on the console

Starting AOT-processed BillingServiceApplicationKt using Java 17.0.5 with PID 1 (/workspace/[app main] started by cnb in /workspace)

Tested with
- spring boot 3.0.2-SNAPSHOT, 
- gradle 7.6,
- windows 10 Version 10.0.19045.2486, 
- openjdk version "18" 2022-03-22
- docker for windows 4.14.1 (91661)
