### ISSUE TITLE
Problems with the migration from Sleuth to Micrometer

### ISSUE THREAD

**Issue by benediktwetzel** [spring-projects/spring-boot#33977]
Hello,

we are upgrading from SB2.7 to SB3 and the migration from Sleuth to Micrometer is causing problems.

We register an `ObservationPredicate` Bean to ignore some observerations. For testing, we return `false` in all cases:

```Java
   @Bean
    public ObservationPredicate ignoreAllObservations() {
        return (name, context) -> false;
    }
   ```

However, to our surprise, some traces are still displayed in Zipkin. These are metrics from methods with are annotated with `@Scheduled(fixedRateString = X)`. Why are these Observations still being considered?

Also, we have some Sleuth configurations in our SB2.7 application, and we can't find any documentation to migrate the old configuration to Micrometer.

In particular, the following configuration parameters are the problem: 
```yaml
  sleuth:
    tx:
      enabled: false
    span-filter:
      additional-span-name-patterns-to-ignore:
        - '(?i)^messagebrokertaskscheduler$'
        - '(?i)^clientinboundchannelexecutor$'
    web:
      additional-skip-pattern: '/websocket.*|/connect.*'
    integration:
      websockets:
        enabled: false
```

Is there any guidance on how we can migrate this configuration to Micrometer?

Thanks in advance! :)
