### ISSUE TITLE
Thymeleaf templates cache even when spring.template.cache: false

### ISSUE THREAD

**Issue by checketts** [spring-projects/spring-boot#34]
When editing Thymeleaf templates, a server restart is required to view the updates.

Even with the following setting in `application.properties`:

```
# Allow Thymeleaf templates to be reloaded at dev time
spring.template.cache: false
```

To reproduce:
With `spring-boot-sample-web-ui`, run it with `mvn spring-boot:run` and edit any of the templates, they don't reload after server has been started.

**Comment by digitalsanctum** [comment]
For other folks that might run into this issue. I had the same problem until I realized that IntelliJ's key mapping for Ctrl-F9 was not actually doing what it was supposed to (Make Project). You can verify this in a couple of ways: 

1. monitor the timestamp of a Thymeleaf template in target/classes/templates after you make a change and use Ctrl-F9. 
2. make a change to a template, then use the Build > Make Project via the main menu.   

The fix for my particular case was to remap the keyboard shortcut for "Make Project". After I did this I was able to make changes to my templates, use my new keyboard shortcut for "Make Project", then reload the browser to see the changes.

**Comment by jgon** [comment]
@amr : Thank you.
The solution using the ThymeleafConfiguration worked perfectly. 
I just had to replace @Inject by @Autowired in my case.

**Comment by giovannicandido** [comment]
In my application-development.yml:
```
resources:
  projectroot: /Users/giovanni/Projects/projectName
spring:
   thymeleaf:
     cache: false
     prefix: file:///${resources.projectroot}/server/src/main/resources/templates/
```
This way in development it use the direct files, and in production the classpath
