### ISSUE TITLE
Not able to deploy to cloud foundry after upgrading to spring boot 2.7.3

### ISSUE THREAD

**Issue by adasgup2** [spring-projects/spring-boot#34058]
Hello, 
I have upgraded my spring boot version to 2.7.3. After that I am facing following issue while deploying my application to PCF:

```
Pushing app bsl-vehicle-filter-service-dev3 to org BSL_EDC1_Preprod / space BSL-dev3 as adasgup2@ford.com...
Applying manifest file C:\Ford\BSL\Workspace\Fossa\vehicle-filter-service\manifest.yml...

Updating with these attributes...
  ---
  applications:
  - name: bsl-vehicle-filter-service-dev3
    instances: 1
    path: C:\Ford\BSL\Workspace\Fossa\vehicle-filter-service\build\libs\bsl_vehicle_filter_service-1.3.1-plain.jar
    memory: 1G
    default-route: true
+   buildpack: java_buildpack_offline
    env:
      JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 11.+ } }'
      JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
    services:
      b2csl-config-server
      b2csl-dev3-redis
      b2csl-credhub-secretzero
      b2csl-rabbitmq
Manifest applied
Packaging files to upload...
Uploading files...
 54.93 KiB / 54.93 KiB [===================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Downloading java_buildpack_offline...
   Downloaded java_buildpack_offline
   Cell 8af4a74f-c202-4a97-906f-1365d65a05aa creating container for instance 8d5bdb31-1f5c-4d13-bbac-6d14d6a8d114
   Cell 8af4a74f-c202-4a97-906f-1365d65a05aa successfully created container for instance 8d5bdb31-1f5c-4d13-bbac-6d14d6a8d114
BuildpackCompileFailed - App staging failed in the buildpack compile phase
FAILED
```

Please find my manifest yaml:

```yaml
---
applications:
- name: bsl-vehicle-filter-service-dev3
  buildpack: java_buildpack_offline
  memory: 1G
  path: C:\Ford\BSL\Workspace\Fossa\vehicle-filter-service\build\libs\bsl_vehicle_filter_service-1.3.1-plain.jar
  instances: 1
  services:
    - b2csl-config-server
    - b2csl-dev3-redis
    - b2csl-credhub-secretzero
    - b2csl-rabbitmq
  env:
    JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 11.+ } }'
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
```

My CF CLI version is 8.3.0+e6f8a853a.2022-03-11.
Please help.
