### ISSUE TITLE
@ConfigurationProperties does not work correctly after Spring Boot v3.0.x (Kotlin v1.7.x +Spring Boot v3.0.4)

### ISSUE THREAD

**Issue by AnneMayor** [spring-projects/spring-boot#34594]
Hi All,
I am trying to connect multi datasources in my web application with Spring Boot v3.0.4. However, as I ran my web application the error below occurred.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: 
Failed to instantiate [org.flywaydb.core.Flyway]: 
Factory method 'flyway' threw exception with message: Error creating bean with name 'routingDataSource' defined in class path resource [CouponDbConfig.class]: 
Failed to instantiate [javax.sql.DataSource]: 
Factory method 'routingDataSource' threw exception with message: dataSource or dataSourceClassName or jdbcUrl is required.
```

This is my source code.
```kotlin
    @Bean
    @ConfigurationProperties(prefix = "spring.datasource.coupon.writer")
    fun couponDatasourceWriter(): DataSource = DataSourceBuilder.create().build()
   // ...

    @FlywayDataSource
    @Bean
    fun routingDataSource(): DataSource {
        val writerDataSource: DataSource = couponDatasourceWriter()
    //...
   }
```

And here is my application.yml file.
```yml
spring:
  datasource:
    coupon:
      writer:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:xxx/test
        username: xxx 
        password: xxx

```

At first, I suspected that `@ConfigurationProperties` annotation cannot inject my application properties(`myapplication.yml`). So, I tested with the below code and the application can be run successfully.

```kotlin
    @Bean
    fun couponDatasourceWriter(): DataSource = DataSourceBuilder.create()
        .driverClassName("org.postgresql.Driver")
        .url("jdbc:postgresql://localhost:xxx/test")
        .username("xxx")
        .password("xxx")
        .build()
   // ...

    @FlywayDataSource
    @Bean
    fun routingDataSource(): DataSource {
        val writerDataSource: DataSource = couponDatasourceWriter()
    //...
   }
```

The thing is that in Spring Boot v2.6.6 the above code which error had occurred has been worked successfully without an issue. I think there might be a problem on Spring Boot v3.0.x version on its own. I found some issues regarding `@ConfigurationProperties` annotation with Spring Boot v3.0.x not exactly the same but the similar one. Could you all check this issue?

**Comment by philwebb** [comment]
From the snippet you've included it appears that `DataSourceBuilder.create().build()` is being used to create the `DataSource` which you then expect configuration properties to be applied to. I'm surprised that worked in 2.6.

I'd recommend changing your `@Configuration` so that you inject `DataSourceProperties` and use them to create the builder. You can find an example in https://docs.spring.io/spring-boot/docs/3.0.x/reference/htmlsingle/#howto.data-access.configure-two-datasources.

If that doesn't work for you, could you please provide a sample application that works in 2.7 but fails in 3.0.

**Comment by AnneMayor** [comment]
Hi @philwebb , thanks for your comment.
I had tried two different things with Spring Boot v2.7.0 and Spring Boot v3.0.4.
The first one is the sample code which has been succeeded in Spring Boot v2.7.0 but failed in Spring Boot v3.0.4.

```kotlin
@Configuration(proxyBeanMethods = false)
class DbConfig {
    @Bean
    @Primary
    @FlywayDataSource
    @ConfigurationProperties(prefix = "spring.datasource.coupon.writer")
    fun couponDatasourceWriter(): DataSource = DataSourceBuilder.create().build()
}
```

```yml
spring.config.activate.on-profile: local
spring:

  datasource:
    coupon:
      writer:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:54322/couponWriter
        username: coupon
        password: coupon
      reader:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:54321/couponReader
        username: coupon
        password: coupon

```

The second is the sample code which has been failed both Spring Boot v2.7.0 and v3.0.4.
```kotlin
@Configuration(proxyBeanMethods = false)
class DbConfig {
    @Bean
    @ConfigurationProperties(prefix = "spring.datasource.coupon.writer")
    fun couponDatasourceProperty(): DataSourceProperties = DataSourceProperties()

    @Bean
    @Primary
    @ConfigurationProperties("spring.datasource.coupon")
    fun firstDataSource(couponDatasourceProperty: DataSourceProperties): DataSource {
        return couponDatasourceProperty.initializeDataSourceBuilder().build()
    }
```

```yml
spring.config.activate.on-profile: local
spring:

  datasource:
    coupon:
      writer:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:54322/couponWriter
        username: coupon
        password: coupon
      reader:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:54321/couponReader
        username: coupon
        password: coupon
```

The error message is like the below.
```text
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
Reason: Failed to determine suitable jdbc url
Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles local are currently active).
```

Make sure that there are no other settings such as flyway. I just tested if my sample application could be connected with my local postgre database. Please, let me know if you need more information about this issue.
