### ISSUE TITLE
Spring-boot-3 native jpa mysql Chinese charater error

### ISSUE THREAD

**Issue by w858269620** [spring-projects/spring-boot#34866]
### Environment
SpringBoot: 3.0.2
Spring Data jpa
MySql 8.x

application.yml

```yaml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: username
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
```

- Question
1. The same code. It gets the right result when using the command of "java -jar ". But it gets the fault result when running as native ways. As follows
![image](https://user-images.githubusercontent.com/28639191/230080639-1c4f5141-1443-4f21-927b-204932cb7754.png)

2. When using both chinese and number it gets an error.
