### ISSUE TITLE
Mail sender support for spring-boot-testcontainers

### ISSUE THREAD

**Issue by linux-china** [spring-projects/spring-boot#35127]
Mail catcher is good solution to test email sending by SMTP,  such as: 

* https://mailcatcher.me/
* https://github.com/linux-china/mail-catcher
* https://github.com/maildev/maildev 

It will be good to add `MailConnectionDetails` support to make email sending test easy with mail catcher container.

**Comment by wilkinsona** [comment]
We could update the auto-configuration to add `MailConnectionDetails` but I'm not sure how much we can do beyond that. As the list above shows, there are a variety of options for running an SMTP server. In terms of official Docker images for the above, there are:

- [mailcatcher](https://hub.docker.com/r/sj26/mailcatcher) 1M+ pulls
- [mail-catcher](https://hub.docker.com/r/linuxchina/mail-catcher) 404 pulls
- [maildev[(https://hub.docker.com/r/maildev/maildev) 10M+ pulls
- [MailHog](https://registry.hub.docker.com/r/mailhog/mailhog/) 100M+ pulls

How the SMTP server is configured differs from image to image so I don't think we can offer a general purpose implementation for getting connection details from a container. MailHog appears to be the most popular, so perhaps that's the place to start? It would feel a little odd to have `MailConnectionDetails` and only have a properties-based implementation.

**Comment by linux-china** [comment]
MailHog is good for me.  All these mail catchers, they almost use 1025 as SMTP port, and I think we just use 1025 as exposed port for `spring.mail.port`.

**Comment by wilkinsona** [comment]
The port should be fine. It's username and password that are more complicated. For example, maildev uses `MAILDEV_OUTGOING_USER` and `MAILDEV_OUTGOING_PASS` environment variables to configure the credentials for sending mail. These are easy for us to extract from the container and use in the connection details. On the other hand, MailHog seems to use a file which would be much harder to deal with unless we only supported the defaults..

**Comment by linux-china** [comment]
@wilkinsona, is it possible to introduce `org.springframework.boot.properties.xxxx` labels, and these labels will be added ad Spring Boot properties.   Example as following: 

```yaml
services:
  redis:
    image: "maildev/maildev"
    ports:
      - '1025'
    labels:
      org.springframework.boot.properties.spring.mail.host = "${container.getHost()}"
      org.springframework.boot.properties.spring.mail.port = "${container.getMappedPort(1025)}"
      org.springframework.boot.properties.spring.mail.username = demo
```

Value cloud be a SpEL, and container is the variable of  GenericContainer or sub GenericContainer.
