### ISSUE TITLE
Spring data findBy Field/All Timeout does not work

### ISSUE THREAD

**Issue by ahmedmaksoud** [spring-projects/spring-boot#35192]
I am using Spring Boot v3.0.6 / Spring v6.0.8/  oracle 19c / Java 17.0.5 , trying to set timeout for repositories findBy Field/All [findByName] , calling the methods from a Service method with `@Transactional`, it does not work and the query exceeds 15 seconds 
**However it works fine for other repositories methods that have `@Query` annotation** 

```java
@Repository
public interface Repo extends JpaRepository<EntityX, Long>, JpaSpecificationExecutor<EntityX>
    
	public List<EntityX> findAll()
        public List<EntityX> findByName()
```

I have set the following app Properties

```
spring:
  transaction:
    default-timeout: 15s
 jpa:
    properties:
      jakarta.persistence.query.timeout: 15000
      jakarta.persistence.lock.timeout: 15000
```

**I also tried this following code with no results** 

```
       @Transactional(timeout = 15)
	public List<EntityX> findAll()
```
