### ISSUE TITLE
Liquibase require a DataSource but can create one itself

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3538]
There is something strange in `LiquibaseAutoConfiguration`  - We require a `DataSource` that we autowire (so single `DataSource` required) but that class has a `getDataSource` method that is able to create a `DataSource` itself based on liquibase configuration. 

What's the requirement for requiring a (single) `DataSource` to be present in the context then?

**Comment by Infeligo** [comment]
This issue in combination with [HikariCP](https://github.com/brettwooldridge/HikariCP) led me to some problems. HikariCP eagerly creates connection pool when `HikariDataSource` is created, meaning that is tries to connect to the database. However, the user that was intended for the connection was still to be created by Liquibase changeset. I fixed this by creating `HikariDataSource` in a such way that it would initialize connection pool on first `getConnection()` call, but that's less optimal than it could be.

**Comment by philwebb** [comment]
See also `@FlywayDataSource`

**Comment by snicaise** [comment]
Just found this problem in my application, it seems related to this conversation. 

If I use this settings, I expect to have 5 connections on the database, but it's not the case, spring open 15 connections.
```
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://xxxxx
    username: xxxxx
    password: xxxxx
    driver-class-name: org.postgresql.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    max-active: 5
    max-idle: 5
    min-idle: 5
    initial-size: 5

liquibase:
  enabled: true
  url: jdbc:postgresql://xxxxx
  user: xxxxx
  password: xxxxx
```

If I remove `liquibase.url` spring-boot make 5 connections on the database as expected :
```
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://xxxxx
    username: xxxxx
    password: xxxxx
    driver-class-name: org.postgresql.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    max-active: 5
    max-idle: 5
    min-idle: 5
    initial-size: 5

liquibase:
  enabled: true
  user: xxxxx
  password: xxxxx
```

I don't think it's a good idea to create a new DataSource with a new database pool for Liquibase, the number of connection is not predictive : how can you size your database pool if you work with multiple server instances connected to the same database.
