### ISSUE TITLE
Document how to add parameters to the JDBC URL created for a Docker Compose managed container

### ISSUE THREAD

**Issue by GrantGochnauer** [spring-projects/spring-boot#35636]
Version: Spring Boot 3.1

application.yml:
```
spring:
  docker:
    compose:
      file: "./docker-compose.yml"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/platform_db?currentSchema=application
    username: postgres
    password: example
```

If I do not include:
```
implementation 'org.springframework.boot:spring-boot-docker-compose'
```

then when I start the app, Spring uses the correct JDBC url. Note I have providing a specific database and schema.

When I include docker-compose support, HikariCP ignores my configuration:

```
DEBUG com.zaxxer.hikari.HikariConfig.logConfiguration[1132] - jdbcUrl.........................jdbc:postgresql://127.0.0.1:15432/postgres
```

and the application fails to run because it's ignoring my JDBC url.

Thanks
