### ISSUE TITLE
spring.jpa.hibernate.ddl-auto is not working 

### ISSUE THREAD

**Issue by lso5507** [spring-projects/spring-boot#35757]
Spring Boot 3.0.5 is in use.
You set ddl-auto as follows, but ddl-auto is set to create.
```
spring:
  security.debug: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none
```
However, if you change the settings as follows, it will work fine.
```
spring:
  security.debug: false
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        format_sql: true
        use_sql_comments: true
```
