### ISSUE TITLE
PropertiesMigrationListener wrongly reports property as deprecated

### ISSUE THREAD

**Issue by martinvisser** [spring-projects/spring-boot#35774]
With the following configuration:
```yaml
spring:
  kafka:
    producer:
      client-id: some-id
      ssl:
        key-password: secret
        key-store-location: classpath:keystore.jks # line 18
        key-store-password: secret
        trust-store-location: classpath:truststore.jks
        trust-store-password: secret
```

I get the following message:
```
[WARN] org.springframework.boot.context.properties.migrator.PropertiesMigrationListener - 
The use of configuration keys that have been renamed was found in the environment:

Property source 'migrate-Config resource 'class path resource [application-integration.yml]' via location 'optional:classpath:/'':
	Key: spring.kafka.producer.ssl.keystore-location
		Line: 18
		Replacement: spring.kafka.producer.ssl.key-store-location
	Key: spring.kafka.producer.ssl.keystore-password
		Line: 19
		Replacement: spring.kafka.producer.ssl.key-store-password
	Key: spring.kafka.producer.ssl.truststore-location
		Line: 20
		Replacement: spring.kafka.producer.ssl.trust-store-location
	Key: spring.kafka.producer.ssl.truststore-password
		Line: 21
		Replacement: spring.kafka.producer.ssl.trust-store-password

Property source 'Config resource 'class path resource [application-integration.yml]' via location 'optional:classpath:/'':
	Key: spring.kafka.producer.ssl.keystore-location
		Line: 18
		Replacement: spring.kafka.producer.ssl.key-store-location
	Key: spring.kafka.producer.ssl.keystore-password
		Line: 19
		Replacement: spring.kafka.producer.ssl.key-store-password
	Key: spring.kafka.producer.ssl.truststore-location
		Line: 20
		Replacement: spring.kafka.producer.ssl.trust-store-location
	Key: spring.kafka.producer.ssl.truststore-password
		Line: 21
		Replacement: spring.kafka.producer.ssl.trust-store-password


Each configuration key has been temporarily mapped to its replacement for your convenience. To silence this warning, please update your configuration to use the new keys.
```

But I already changed them to the new one. It's just a warning, but it seems to be incorrect. Also interesting it shows it twice with different property source names.
