### ISSUE TITLE
spring boot cloud kafka properties are not working as expected

### ISSUE THREAD

**Issue by rjadiya** [spring-projects/spring-boot#36005]
properties.yaml

```
              consumer:
                enableDql: true
                dlqName: test.dlq
                autoCommitOnError: true
                autoCommitOffset: true
                deliveryAttemptHeader: 1000
                maxAttempts: 1000
                backOffMaxInterval: 3000
                backOffInitialInterval: 3000
                backoffMultiplier: 3.0
                defaultRetryable: true
```                
                
```java
public Consumer<Message<T>> test() {
		log.info("received message");
		return message -> {
			log.debug("Incoming msg:: {} ", message);
			log.info("Received the msg for {} ", message.getPayload());
			MsgMetaInfo msgMetaInfo = getMsgMetaInfo(message.getPayload(), message.getHeaders());
			if (null != message.getHeaders().get("test")) {
				//
			}
			testService.processMessage(message.getPayload(), msgMetaInfo);
		};

	}
```

Note : testService.processMessage throwing exception and trying 3 times only
	
once consumer failed to process the message I am not able to retry it more than 3 times and message are not going to deadletter queue even
