### ISSUE TITLE
Please add server.ssl.key-store-password-file-name property

### ISSUE THREAD

**Issue by Shubham-Vishwakarma** [spring-projects/spring-boot#36067]
### Please add server.ssl.key-store-password-file-name property

In the previous/current versions of spring boot, if I have to enable SSL i.e. make it HTTPS.
I have to provide the below details in application.properties or application.yaml file

```
server:
  port: <port-no>                                         
  ssl:
    key-alias: yourKeyAlias                          
    key-store: path/to/keystore                      
    key-store-password: yourKeyStorePassword         
    key-password: yourKeyPassword                    
    trust-store: path/to/trust-store                 
    trust-store-password: yourTrustStorePassword     

```
https://docs.spring.io/spring-cloud-skipper/docs/1.0.0.BUILD-SNAPSHOT/reference/html/configuration-security-enabling-https.html

Here the property **key-store-password** is a plaintext password.
**I would be happy if I can provide a file location and Spring will read the file's content to use it as a password.**
I am aware I can write a few lines of code to create a custom web servlet.
However, it would be easy to pass it as a property without any code to be written.
