### ISSUE TITLE
Document that validation of @ConfigurationProperties in a native image requires @Valid to cascade validation

### ISSUE THREAD

**Issue by KimSeongIl** [spring-projects/spring-boot#37101]
spring boot version: 3.1.0
graalvm plugin version: id("org.graalvm.buildtools.native") version "0.9.20"
graalvm version: 22.3.r17

DemoContext.kt
```kotlin
@ConfigurationProperties(prefix = "demo.context")
@Validated
class DemoContext {

    var exclude: List<Exclude> = mutableListOf()

    data class Exclude(
        var url: List<String>? = null,

        var httpMethod: List<HttpMethod>? = null,

        var httpStatus: List<@Pattern(regexp="^([1-5][x|X]{2}|[1-5][0-9]{2})\$") String>? = null,

        var elapsedTime: Long? = null
    )

}
```

application.yml
```yaml
demo:
  context:
    exclude:
      - httpStatus: 2xx
```

nativeRun result
```
Binding to target [Bindable@517a5ddb type = java.util.List<DemoContext$Exclude>, value = 'provided', annotations = array<Annotation>[[empty]]] failed:

    Property: demo.context.exclude[0].httpstatus
    Value: "2xx"
    Origin: class path resource [application.yml] - 31:21
    Reason: The elements [demo.context.exclude[0].httpstatus] were left unbound.

Action:

Update your application's configuration
```

It worked fine before, but when I run it on the native image I get an error.
However, if I remove the Pattern annotation, it works fine.

Why is this problem occurring?
What should I do to resolve this?
