### ISSUE TITLE
spring-boot-docker-compose java.lang.IllegalStateException: No POSTGRES_PASSWORD defined

### ISSUE THREAD

**Issue by derylspielman** [spring-projects/spring-boot#37188]
Hi I'm using spring-boot-docker-compose to have a postgres database start when the app starts but getting error at startup
```
java.lang.IllegalStateException: No POSTGRES_PASSWORD defined
```
This is due to [PostgresEnvironment](https://github.com/spring-projects/spring-boot/blob/018c188cebfda2750d2cc4302343a646105fe0a7/spring-boot-project/spring-boot-docker-compose/src/main/java/org/springframework/boot/docker/compose/service/connection/postgres/PostgresEnvironment.java#L47) extracting environment variables but assuming there is a `POSTGRES_PASSWORD` environment variable.

I am using the supported `POSTGRES_PASSWORD_FILE` environment variable instead, which is how you can keep secrets out of version control. 

## Steps to reproduce
1. Configure pom.xml
```xml
...
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-docker-compose</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
...
```
2. Add docker-compose.yml in the root project folder
```yml
version: '3.8'

services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 5432:5432
    secrets:
      - db_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

secrets:
  db_password:
    file: src/main/resources/postgres_password.txt
```
3. Save a secrets file
   - Save the postgres password in the Spring Boot app under `src/main/resources/postgres_password.txt`
4. Run the app
5. Expecting the app to start but instead getting `java.lang.IllegalStateException: No POSTGRES_PASSWORD defined`

Running `docker compose up` works fine and the container starts.

Spring Boot version: 3.1.1
Java version: openjdk 17.0.8.1
