### ISSUE TITLE
Springboot Kafka autoconfiguration - SSL Bundle for SASL_PLAINTEXT with SCRAM-SHA-512

### ISSUE THREAD

**Issue by radu-barbu-sage** [spring-projects/spring-boot#39144]
Since SpringBoot version 3.2 Kafka autoconfiguration is deprecated and marked for removal in version 3.4 https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/kafka/KafkaProperties.html#buildAdminProperties() and it is recommended to use SSLBundles.

As we are connecting to Kafka cluster using SASL_PLAINTEXT with SCRAM-SHA-512
```

  kafka:
    security:
      protocol: SASL_PLAINTEXT
    bootstrap-servers: adress_of_the_server
    properties:
      sasl:
        mechanism: SCRAM-SHA-512
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="username" password="password";
    jaas:
      enabled: true
```

how should I configure SslBundle for SASL_PLAINTEXT with SCRAM-SHA-512?
