### ISSUE TITLE
Bug : CSS Related issue in Documentation

### ISSUE THREAD

**Issue by AlFahimBinFaruk** [spring-projects/spring-boot#39411]
### Issue
In the documentation the content section is always scrollable. I think this is annoying to the readers.

### Solution
However if we add : 

```css
.doc #content {
    margin: 0 2rem;
    padding: 0 1rem;
}
body.toc-left #doc {
    overflow: visible;
}
```
this will resolve the issue for desktop-mode and will add more to the user experience.
### Before
![Screenshot from 2024-02-06 14-07-18](https://github.com/spring-projects/spring-boot/assets/85015121/db40dff3-8964-4f01-a090-21d395c5cdc0)

### After
![Screenshot from 2024-02-06 14-09-31](https://github.com/spring-projects/spring-boot/assets/85015121/9d6946d0-31e6-47b4-b1d8-6d7f9ee1593f)

In here you can see that the sections are much more readable after adding the following css.

* I am using Ubuntu 22 as my OS and Chrome as my browser.
