### ISSUE TITLE
Add support for actuator Tomcat configuration of threads pool

### ISSUE THREAD

**Issue by GooDer** [spring-projects/spring-boot#39866]
Hello, during some investigation I found out that there is no possibility to set different thread pool setting for Tomacat server which run Spring application itself and actuator enpoint in case that it runs on different port.

```yaml
server:
  port: 80
  tomcat:
    threads:
      min-spare: 15
management:
  server:
    port: 8787 -> this will create another thread pool with minimum of 15 threads
```

I think it could be handy to be able to set separate thread pool configuration in application properties/yaml for both endpoints.

e.g.

```yaml
management:
  server:
    threads:
      min-spare: 15
      max: 200
    accept-count: 100
```
