### ISSUE TITLE
spring security on profile doesn't load

### ISSUE THREAD

**Issue by Subrhamanya** [spring-projects/spring-boot#39955]
I am migrating from spring boot 2.7.18 to spring boot 3.2.x and I have noticed a strange behavior in spring security configuration on the basis of spring profile.

I am creating a spring cloud config server with basic authentication as follows.

```
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.config.server.EnableConfigServer;

@SpringBootApplication
@EnableConfigServer
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

}
```

My basic spring security looks like below

```
package com.example.demo;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.security.config.Customizer;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityCustomizer;
import org.springframework.security.web.SecurityFilterChain;

@Configuration(proxyBeanMethods = false)
@EnableWebSecurity
@Order(Ordered.HIGHEST_PRECEDENCE)
public class SecurityConfiguration {
  @Bean
  public WebSecurityCustomizer webSecurityCustomizer() {
    return web ->
        web.ignoring()
            .requestMatchers(
                "/meta/**",
                "/encrypt/**");
  }

  @Bean
  public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
    return http.httpBasic(Customizer.withDefaults())
        .csrf(csrf -> csrf.ignoringRequestMatchers("/decrypt/**"))
        .build();
  }
}
```

application.yml file looks like below

```
spring:
  application:
    name: demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/uri
          username: name
          password: password
          basedir: /app/config/cache
          defaultLabel: master
          cloneOnStart: true
          force-pull: true
server:
  port: 8888
  ssl.enabled: false
  servlet.jsp.registered: false
eureka:
  client:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: secure
  security:
    user:
      password: "secret"
  cloud:
    config:
      server:
        encrypt:
          enabled: true

encrypt:
  key:  cipher text
```

Now when I run my config server, it starts with the profile **default**. Here authentication is done which is expected by default. But when I run the application with profile **secure**, all profile settings are loaded from application.yml file except
```
  security:
    user:
      password: "secret"
```
ie let's say we call endpoint /decrypt without password secret, it should return 401. But we are getting 200. I am just confused why server.encrypt.enabled is loaded and not just spring.security.user.password?? Isn't only requests with **password: secret** should be allowed for **profile: secure**??

Spring boot 2.7.18 is working fine without any issues.
