### ISSUE TITLE
Spring hikari datasource metrics not visible on prometheus endpoint

### ISSUE THREAD

**Issue by abhisheksurve45** [spring-projects/spring-boot#40048]
Using spring boot 3.2.3

Have initialised a JDBC Datatsource like

```yml
  datasource:
    url: jdbc:mysql://x.x.x.x:xxxx/xxx
    username: xxxx
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: xxxx
    hikari:
      pool-name: xxxx
```

in application.yml

The Datasource bean of type HikariDataSource gets created and I'm able to use it.

I also do get metrics such as `jdbc_connections_max` in actuator endpoint, however I want hikaricp metrics which are present in https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/metrics/micrometer/MicrometerMetricsTrackerFactory.java

I'm using micrometer for other metrics as well.

**Comment by abhisheksurve45** [comment]
I see property `metrics-tracker-factory` in `hikari`

example

```yml
 datasource:
    url: jdbc:mysql://x.x.x.x:xxxx/xxx
    username: xxxx
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: xxxx
    hikari:
      pool-name: xxxx
      metrics-tracker-factory: ?
```

But I'm not sure how to set it.

Ive initialised the Micrometer `MeterRegistry` via

```java
@Bean
    public MeterRegistry getMeterRegistry() {
        return new CompositeMeterRegistry();
    }
```
