### ISSUE TITLE
Unable to use Docker Compose support when mixing dedicated and shared services

### ISSUE THREAD

**Issue by sivaprasadreddy** [spring-projects/spring-boot#40139]
I have a microservices-based mono-repo with multiple spring-boot applications. I would like to use Spring Boot Docker Compose support to start the dependent services. There are few services (ex: db) that are specific to each service and there are some services (ex: RabbitMQ) shared by multiple services.

All the microservices dependencies are defined in a single `compose.yml` fil. If I start any one microservice it starts all the services defined in the compose.yml file, which is ok for me.

```
version: "3.8"
services:
  catalog-db:
    image: postgres:16-alpine
    ...
  orders-db:
    image: postgres:16-alpine
    ...
  rabbitmq:
    image: rabbitmq:3.12.11-management
    ...
```

**But the problem is, when I have multiple databases defined for different services, Flyway initialization fails.**

```
Parameter 0 of method flyway in org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration required a single bean, but 2 were found:
	- flywayConnectionDetailsForCatalogDb: defined in unknown location
	- flywayConnectionDetailsForOrdersDb: defined in unknown location
```

Is there a way to configure at the microservice level (using `spring.docker.compose.*` properties) to take only certain services into account?

**Comment by sivaprasadreddy** [comment]
Instead of putting all the services in a single `compose.yml` file, I tried to split them into separate files.

common.yml

```
version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.12.11-management
    ...
```


catalog.yml

```
version: "3.8"
services:
  catalog-db:
    image: postgres:16-alpine
    ...
```


orders.yml

```
version: "3.8"
include:
  - common.yml
services:
  orders-db:
    image: postgres:16-alpine
    ...
```

Now, in the application.properties file I configured which file to use as follows:

```
spring.docker.compose.file=deployment/docker-compose/orders.yml
spring.docker.compose.lifecycle-management=start_only
```

Now, the problem is, that the first spring-boot app (say order-service) that I started works as expected. But when I start the second application (say catalog-service) I see the following message due to which the required services are not being started.

```
s.b.d.c.l.DockerComposeLifecycleManager : Using Docker Compose file '/path/compose-files/catalog.yml'
s.b.d.c.l.DockerComposeLifecycleManager : There are already Docker Compose services running, skipping startup
```

**Comment by scottfrederick** [comment]
> I tried to split them into separate files.

Another option would be to keep the services in one file, use [Docker Compose profiles](https://docs.docker.com/compose/profiles/), and [modify your `application.properties` ](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.docker-compose.profiles) to control when individual services are started. 

> I see the following message due to which the required services are not being started.

This behavior is mentioned in the [documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.docker-compose): 

> If the Docker Compose services are already running when starting the application, Spring Boot will only create the service connection beans for each supported container. It will not call `docker compose up` again and it will not call `docker compose stop` when the application is shutdown.

There is some discussion on why we chose to implement things this way in https://github.com/spring-projects/spring-boot/issues/38398. 

You can set `spring.docker.compose.lifecycle-management=none` to prevent this message. You will have to start the service manually (for example, with `docker compose up`), but Spring Boot will create the service connections as expected. 

An additional mode like the one suggested in #39749, where `docker compose up` would be called without first checking to see what services are running, could help this situation. I will close this issue in favor of that issue.

**Comment by sach429** [comment]
@scottfrederick 

> Another option would be to keep the services in one file, use [Docker Compose profiles](https://docs.docker.com/compose/profiles/), and [modify your application.properties ](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.docker-compose.profiles)to control when individual services are started.

Do you mean to say, if I create a single file

`version: "3.8"
services:
  catalog-db:
    image: postgres:16-alpine
    profiles:
      - catalog
    ...
  orders-db:
    image: postgres:16-alpine
    profiles:
      - order
    ...
  rabbitmq:
    image: rabbitmq:3.12.11-management
    ...
`
And then specify in the [application.properties](https://docs.spring.io/spring-boot/reference/features/dev-services.html#features.dev-services.docker-compose.profiles) of Catalog service and Order service `spring.docker.compose.profiles.active=catalog` and ` spring.docker.compose.profiles.active=order` respectively, then there will be two DB instances running but Catalog service and Order Service will only create **one** DB ConnectionDetails instead of **two**?

**Comment by bclozel** [comment]
@sach429 that is correct.

**Comment by sach429** [comment]
> @sach429 that is correct.

@bclozel I don't think it's working that way. Let me clarify how I am running my applications. I have two spring boot apps and I am running them directly from IntelliJ one after another.

For eg. this is my setup and my intention is to have Catalog and Order have their own separate DBs but share the same Redis server

Catalog:
application.properties
`spring.docker.compose.profiles.active=catalog,redis`
compose.yml
```
version: "3.8"
services:
  catalog-db:
    image: postgres:16-alpine
    profiles:
      - catalog
    ...
  redis:
    image: redis:latest
    profiles:
      - redis
    .....

```

Order:
application.properties
`spring.docker.compose.profiles.active=order`
compose.yml
```
version: "3.8"
services:
  orders-db:
    image: postgres:16-alpine
    profiles:
      - order
    ...
  redis:
    image: redis:latest
    profiles:
      - redis
    .....

```

I am running Catalog first, followed by Order. When I start Order, it detects the already running postgres container and eventually created two `ConnectionDetails `instances instead of one. I put breakpoints in the code, [DefaultDockerCompose, list contains all the running containers in the host machine](https://github.com/spring-projects/spring-boot/blob/86b0c768e72a5c2d4c2488718434e5d2f1bcfb3f/spring-boot-project/spring-boot-docker-compose/src/main/java/org/springframework/boot/docker/compose/core/DefaultDockerCompose.java#L108) and seems like the code is designed that way to detect all the existing running containers and eventually creating a `ConnectionDetails `instance as long as they match any of the supported services.

It does not matter if I merge the two compose files into one and refer to the same file in two Projects. I believe the profiles value is being passed as a flag when starting the docker services. So it's executing `docker compose --profile catalog  --profile redis up` and `docker compose --profile order` when running Catalog and Order services respectively. It's not used to filter an existing running container.
