### ISSUE TITLE
publish a gradle version catalog

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#40156]
https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog-declaration

I'd love to have a version catalog that I can just use, that is fundamentally equivalent to what's in the bom.

I understand these can be published in some way, but I'd just be happy with just toml file I could download right now. Currently I have this, but I'm still adding things as I need to reference them directly somewhere. I can't imagine I'm the only one who would enjoy this for static accessors.

I'm not suggesting this as a replacment for the bom's (although they could replace boms and starters), just as a way to get gradle's static accessors without everyone having to do what I'm doing, which is adding dependency as I need it.

```toml
spring-boot-core = { module = "org.springframework.boot:spring-boot" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-test-core = { module = "org.springframework.boot:spring-boot-test" }
spring-boot-test-autoconfigure = { module = "org.springframework.boot:spring-boot-test-autoconfigure" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-beans = { module = "org.springframework:spring-beans" }
spring-context = { module = "org.springframework:spring-context" }
spring-core = { module = "org.springframework:spring-core" }
spring-data-jpa = { module = "org.springframework.data:spring-data-jpa" }
spring-data-envers = { module = "org.springframework.data:spring-data-envers" }
spring-instrument = { module = "org.springframework:spring-instrument" }
spring-orm = { module = "org.springframework:spring-orm" }
spring-test = { module = "org.springframework:spring-test" }
spring-transaction = { module = "org.springframework:spring-tx" }
spring-security-core = { module = "org.springframework.security:spring-security-core" }
spring-security-oauth2-authorization-server = { module = "org.springframework.security:spring-security-oauth2-authorization-server" }
spring-security-oauth2-core = { module = "org.springframework.security:spring-security-oauth2" }
spring-security-web = { module = "org.springframework.security:spring-security-web" }
spring-data-commons = { module = "org.springframework.data:spring-data-commons" }
spring-data-neo4j = { module = "org.springframework.data:spring-data-neo4j" }
spring-web = { module = "org.springframework:spring-web" }
starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop" }
starter-core = { module = "org.springframework.boot:spring-boot-starter" }
starter-jackson = { module = "org.springframework.boot:spring-boot-starter-jackson" }
starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
starter-log4j2 = { module = "org.springframework.boot:spring-boot-starter-log4j2" }
starter-neo4j = { module = "org.springframework.boot:spring-boot-starter-data-neo4j" }
starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }
starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
```
