### ISSUE TITLE
io.lettuce.core.RedisConnectionException: Unable to connect to [docker-server-name]/<unresolved>:6379

### ISSUE THREAD

**Issue by LiuJingQiang** [spring-projects/spring-boot#40317]
spring-boot-version: 3.2.4

redis config:

```
spring:
  data:
    redis:
      host: [docker-server-name]
      port: 6379
```

no password, so error message is: io.lettuce.core.RedisConnectionException: Unable to connect to [docker-server-name]/<unresolved>:6379

but use local env file ,just change host: localhost is ok

eg:

```yaml 
spring:
  data:
    redis:
      host: localhost
      port: 6379
```

important： 
spring-boot version:  3.0.4

```
spring:
  data:
    redis:
      host: [docker-server-name]
      port: 6379
```

this config is ok
