### ISSUE TITLE
RFC: new property "spring.devtools.livereload.additional-paths" 

### ISSUE THREAD

**Issue by metaforte** [spring-projects/spring-boot#40342]
Thymeleaf allows using files from src folder during development.
 However live reload does not have a file system watcher for "additional paths" to auto reload based on those templates

Just as there is there is `spring.devtools.restart.additional-paths`, 

request new property `spring.devtools.livereload.additional-paths`

this should work in support of `thymeleaf.prefix`

````yaml
logging:
  config: classpath:log4j2-local.xml
spring:
  devtools:
    livereload:
      enabled: 'true'
      additional-paths:
        - file:src/main/resources/static/
        - file:src/main/resources/templates/
  thymeleaf:
    cache: 'false'
    prefix: file:src/main/resources/templates/
    check-template-location: 'true'

  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/
      cache:
        period: 0
````
