### ISSUE TITLE
RelaxedDataBinding broken for jackson configuration via yaml in M5

### ISSUE THREAD

**Issue by madorb** [spring-projects/spring-boot#4038]
I've got an application.yaml with properties:

```
spring:
   ...
    jackson:
        serialization-inclusion: non_null
        serialization:
            write_dates_as_timestamps: false
```

This was working properly in M3 but now is failing in M5 with errors like:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.boot.autoconfigure.jackson.JacksonProperties org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperBuilderConfiguration.jacksonProperties; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.jackson.CONFIGURATION_PROPERTIES': Could not bind properties to JacksonProperties (prefix=spring.jackson, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'spring.jackson' on field 'null': rejected value [write_dates_as_timestamps]; codes [typeMismatch.spring.jackson.null,typeMismatch.null,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [spring.jackson.null,null]; arguments []; default message [null]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'com.fasterxml.jackson.databind.SerializationFeature' for property 'null'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.String to type com.fasterxml.jackson.databind.SerializationFeature for value 'write_dates_as_timestamps'; nested exception is java.lang.IllegalArgumentException: No enum constant com.fasterxml.jackson.databind.SerializationFeature.write_dates_as_timestamps]
```

This seems to work properly if i modify my configuration to look like:

```
spring:
   ...
    jackson:
        serialization-inclusion: NON_NULL
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
```
that is, both keys and values appear to now have to match case exactly. I am using Jackson 2.6.1
