### ISSUE TITLE
TraceId is not propagating in microservices using micrometer and zipkin

### ISSUE THREAD

**Issue by pSinghDelaplex** [spring-projects/spring-boot#40704]
I'm generating request from service 1 to service 2 , traceId and spanId are getting generated in the logs for service 1 but when calls service 2 REST API, traceId and spanId get changed. TraceId should be constant for the complete request and response call but it is not happening it also getting changed. I'm running my zipkin server locally and using WebClient for sending request for service calls.

Microservice 1

build.gradle

```
    id "org.springframework.boot" version "3.1.9"
    springCloudVersion = "2022.0.5"
    springBootAdminVersion = "3.2.2"
    
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-integration"
    implementation "org.springframework.boot:spring-boot-starter-log4j2"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-webflux"
    implementation "org.springframework.integration:spring-integration-http"
    implementation "org.springframework.cloud:spring-cloud-config-client"
    implementation "org.springframework.integration:spring-integration-ip:6.2.2"
    **implementation 'io.micrometer:context-propagation:latest.integration'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'**
```

application.yml

```
management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
zipkin:
  tracing:
    endpoint: http://localhost:9411
logging:
  config: classpath:log4j2-spring.yml
  file.name: service1.log    
```

  SpringBootApplication.java 
  
```
  import brave.sampler.Sampler;
    @Bean
  public Sampler defaultSampler()
  {
    return Sampler.ALWAYS_SAMPLE;
  }
```

log4j2-spring.yml

```
    RollingFile:
      - name: RollingFile_Appender
        fileName: ${log-path}/${sys:LOG_FILE}
        filePattern: "${log-path}/${sys:LOG_FILE}.%d{yyyy-MM-dd}T%d{HH-mm-ss}.%i.log"
        PatternLayout:
          pattern: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%X{traceId},%X{spanId}] [%-5level] [%5T] [%-25logger{1}]: %message%n"
```
---------------------------------------------------------------------------------------------------

Microservice 2

build.gradle

```
    id "org.springframework.boot" version "3.2.5"
    springCloudVersion = "2023.0.1"
    springBootAdminVersion = "3.2.2"
    
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-integration"
    implementation "org.springframework.boot:spring-boot-starter-log4j2"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-webflux"
    implementation "org.springframework.integration:spring-integration-http"
    implementation "org.springframework.cloud:spring-cloud-config-client"
    implementation "org.springframework.integration:spring-integration-ip:6.2.2"
    **implementation 'io.micrometer:context-propagation:latest.integration'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'**
```

application.yml

```
management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
zipkin:
  tracing:
    endpoint: http://localhost:9411
logging:
  config: classpath:log4j2-spring.yml
  file.name: service2.log    
```

  SpringBootApplication.java 
  
```
  import brave.sampler.Sampler;
    @Bean
  public Sampler defaultSampler()
  {
    return Sampler.ALWAYS_SAMPLE;
  }
```

log4j2-spring.yml

```
    RollingFile:
      - name: RollingFile_Appender
        fileName: ${log-path}/${sys:LOG_FILE}
        filePattern: "${log-path}/${sys:LOG_FILE}.%d{yyyy-MM-dd}T%d{HH-mm-ss}.%i.log"
        PatternLayout:
          pattern: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%X{traceId},%X{spanId}] [%-5level] [%5T] [%-25logger{1}]: %message%n"
```
