### ISSUE TITLE
Nested livenes/rediness group not working

### ISSUE THREAD

**Issue by kubav182** [spring-projects/spring-boot#40773]
In SB 2.7 i could write this config

```
management:
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: 'readinessState,binders/kafka,db,redis'
        liveness:
          include: 'livenessState,binders/kafka,db,redis'
```

but in SB3 it does not work because binders/kafka does not exist and app won't start. I can use just binders without kafka. When i look to liveness endpoint it contains binders with nested kafka. So how can i select just kafka in SB3? I tried diffferent separators like : . :/ - and nothing works. I use SB 3.2.4
