### ISSUE TITLE
The value of the tomcat.threads.config.max metric is always -1, irrespective of the configured maximum number of threads

### ISSUE THREAD

**Issue by lass9436** [spring-projects/spring-boot#40957]
## Bug
my application.yml is

application.yml
```
management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
server:
  tomcat:
    threads:
      max: 400
      min-spare: 10
    mbeanregistry:
      enabled: true
```
but 

http://localhost:8080/actuator/prometheus
![1](https://github.com/spring-projects/spring-boot/assets/57583282/dedcac19-ed19-4e67-855d-1fdf1374a41e)

I don't know why not working.

## Environment
- Spring Boot version: 3.3.0
- JDK version: 17
- OS: Windows 10

## solution
my only solution is downgrading spring boot 3.3.0 to 3.2.6

Fortunately, it works successfully in 3.2.6, but I report this bug.
