### ISSUE TITLE
spring.json.type.mapping, kafka producer doen't work with spring boot 3.3.0

### ISSUE THREAD

**Issue by SzestKam** [spring-projects/spring-boot#41240]
I have problem after upgrade spring boot version from 3.2.6 to version 3.3.0

other dependency, they're the same even I change spring boot version:
org.springframework.kafka:spring-kafka:3.2.0
com.fasterxml.jackson.module:jackson-module-kotlin:2.17.1
io.projectreactor.kafka:reactor-kafka:1.3.23

configuration for spring kafka
```yaml
spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.charger.communication.service.config.CustomKafkaJsonValueSerializer
      properties:
        spring.json.type.mapping: "rawLogEvent:com.charger.communication.service.event.RawLogEvent,
        detailedLogEvent:com.charger.communication.service.event.DetailedLogEvent,"
    properties:
      spring.json.trusted.packages: "*"
```

in section above important mapping is: `spring.json.type.mapping`

`CustomKafkaJsonValueSerializer` is used to deliver customized `com.fasterxml.jackson.databind.ObjectMapper`

with sprig boot version 3.2.6 event on the kafka topic has inside the header key: `__TypeId__` with value `rawLogEvent` so it means that mapping works as expected

with version 3.3.0 this key: `__TypeId__` cointains entry `com.charger.communication.service.event.RawLogEvent`, no mapping applied

I tried to check documentation for each module, nowhere info about changes. Also I try to obey suggested configuration without expected results.

I need your help to understand how to properly use mappings with newer spring boot version.
