### ISSUE TITLE
@ConditionalOnProperty for branch of values not match

### ISSUE THREAD

**Issue by lowcasz** [spring-projects/spring-boot#41621]
A have sample yaml property file:
```
prefix:
  branch1:
    branch2conditioned:
      branch3a:
        value: true
      barnch3b:
        value: false
```
I want use `@ConditionalOnProperty` and create bean when `branch2conditioned` is defined in application.
It does not work actually.

I tried:
'''
@ConditionalOnProperty("prefix.branch1.branch2conditioned")
@ConditionalOnProperty(prefix ="prefix.branch1", name="branch2conditioned")
@ConditionalOnProperty(prefix ="prefix.branch1.branch2conditioned")
'''
Neither condition match.
