### ISSUE TITLE
Configuring metric `percentiles-histogram` and `percentiles` disables the `quantile` tag since at least `Spring Boot 3.3.1`

### ISSUE THREAD

**Issue by OathMeadow** [spring-projects/spring-boot#41880]
Hello!

We upgraded from Spring Boot 3.2.3 to 3.3.1 (later switched to 3.3.2) and noticed my quantile tags has disappeared of multiple metrics. Our configuration was the following:

```
management:
  endpoints:
    web.exposure.include: "health,info,metrics,configprops,prometheus"
  metrics:
    distribution:
      percentiles-histogram:
        http.client.requests: true
        http.server.requests: false
      percentiles:
        http.client.requests: 0.50,0.95,0.99,0.999
        http.server.requests: 0.50,0.95,0.99,0.999
```

Weeks after the upgrade, we saw our HTTP Client 99, 95 and 50 percentiles Grafana Dash boards died. However, our histogram heatmap was still functional. After scratching my hair we decided to upgrade to 3.3.2 due to a micrometer warning log appeared and it seemed connected to a bug. However, this did not resolve the issue.

After some checking and testing, we noticed that the HTTP Server metrics was still functional, so after playing around, we decided to configure the following:

```
management:
  endpoints:
    web.exposure.include: "health,info,metrics,configprops,prometheus"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: false
      percentiles:
        http.client.requests: 0.50,0.95,0.99,0.999
        http.server.requests: 0.50,0.95,0.99,0.999
```

And viola! Metrics with the quantile tag pops up! We also have bucket metrics, even though `http.client.requests: true` is not configured and set to true.

Am I missing something or is this a bug?

Thank you!
