### ISSUE TITLE
Explain that enabling virtual threads disables traditional thread pools

### ISSUE THREAD

**Issue by stsypanov** [spring-projects/spring-boot#41937]
While investigating this issue https://stackoverflow.com/questions/78790376/spring-boot-application-gets-stuck-when-virtual-threads-are-used-on-java-21 I've found out, that the property
```yaml
server:
  tomcat:
    threads:
      max: 110
```
works only for platform threads and doesn't affect amount of carrier threads in `ForkJoinPool` when 
```yaml
spring:
  threads:
    virtual:
      enabled: true
```
the only way to change their amount is to use `-Djdk.virtualThreadScheduler.parallelism=n` which seems to be wrong in this case as it would affect all the JVM, not one particular `ForkJoinPool`. See https://stackoverflow.com/questions/78815247/can-i-configure-parallelism-of-forkjoinpool-created-for-tomcat-in-spring-boot-ap/78815410
