### ISSUE TITLE
Health probes response changes when additional-path specified

### ISSUE THREAD

**Issue by igr** [spring-projects/spring-boot#42057]
SpringBoot v3.3.3

I added actuator and have the following configuration:

```yaml
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
      group:
        live:
          additional-path: server:/healthz
```

It provides the following endpoints:

+ /actuator/health - returns the full health status
+ /healthz - same as above
+ /actuator/health/liveness - returns just liveness information
+ /actuator/health/readiness - returns just readiness information

This is ok. Now, I want to add additional paths for liveness and readiness probes:

```yaml
management:
  endpoint:
    health:
      group:
        live:
          additional-path: server:/healthz
        liveness:
          additional-path: server:/livez
        readiness:
          additional-path: server:/readyz
```

This configurations adds two endpoints: `/livez` and `/readyz`.

However, these new endpoints are now returning the **full** health status, just as the `health` endpoint.

Expected behaviour is of new additional paths is to return just the probes status.
