### ISSUE TITLE
Spring Boot (Webflux) - Swagger UI - redirect URI does not include Gateway Prefix 

### ISSUE THREAD

**Issue by dreamstar-enterprises** [spring-projects/spring-boot#42317]
This was closed, but I really do think this is a Spring Boot issue, rather than external library issue.

Re-opening for further consideration:

https://github.com/spring-projects/spring-boot/issues/42305

**Comment by dreamstar-enterprises** [comment]
I don't undersand why this was closed?

**Comment by wilkinsona** [comment]
As Brian already explained, we want to allow the Springdoc team some time to evaluate https://github.com/springdoc/springdoc-openapi/issues/2708. Please respect the team's wishes. Opening duplicate issues across multiple projects just waste the time of the OSS community.

**Comment by dreamstar-enterprises** [comment]
Yes, no problem I will wait, as requested. I do still think this is a Spring Boot framework thing, since these settings are for Spring Boot (not Spring Docs) - so whichever library tries to generate an internal redirect URL, the code to add the Gateway prefix should NOT be in their library code. It should be managed by Spring Boot.

```
# default server settings
server:
  address: ${LOCALHOST}
  port: ${RESOURCE_SERVER_PORT}
  ssl:
    enabled: false
  forward-headers-strategy: native (here framework doesn't work for me - I keep getting 403 Forbidden)
```

I can see my BFF forwarding the right headers in the request to the Resource Server:

```
Forwarded: proto=http;host="localhost:7080";for="127.0.0.1:51801"
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
X-Forwarded-Prefix: /bff
X-Forwarded-Port: 7080
X-Forwarded-Host: localhost:7080
host: localhost:9090
content-length: 0
Authorization: Bearer eyJhb...
```

**Comment by wilkinsona** [comment]
If you believe it's a Spring Boot problem, then you should provide a complete, yet minimal sample that demonstrates that's the case. If indeed it is a Spring Boot problem, such a sample should not depend on Spring Docs, or any other third-party code. Instead it should only depend on Spring Boot and contain the minimal amount of application code that's necessary to reproduce the problem.

**Comment by dreamstar-enterprises** [comment]
Hi Wilinsona, 

Thanks for offering to consider this further.. 


My Resource Server YAML settings are just this. It has one protected endpoint called /secret-message
It has a security chain too, 

**Resource Server YAML Config**

```
#**********************************************************************************************************************#
#***************************************************** VARIABLES ******************************************************#
#**********************************************************************************************************************#

dse-servers:
  # server settings
  scheme: ${SCHEME}
  hostname: ${HOST}

  # reverse proxy server
  reverse-proxy-host: ${REVERSE_PROXY_HOST}
  reverse-proxy-port: ${REVERSE_PROXY_PORT}

  # bff server
  bff-server-prefix: ${BFF_SERVER_PREFIX}

  # resource server
  resource-server-port: ${RESOURCE_SERVER_PORT}
  resource-server-prefix: ${RESOURCE_SERVER_PREFIX}

  # auth-0 authorization server
  auth0-auth-registration-id: ${AUTH0_SERVER_REG_ID}
  auth0-issuer-uri: ${AUTH0_SERVER_ISSUER_URI}
  auth0-dreamstar-frontiers-url: ${AUTH0_DREAMSTAR_FRONTIERS_URL}

#**********************************************************************************************************************#
#************************************************** SPRING SETTINGS ***************************************************#
#**********************************************************************************************************************#

# default spring settings
spring:
  # application settings
  application:
    name: Timesheets-RESTApiApplication
  # profile settings
  profiles:
    active: dev
  # lifecycle settings
  lifecycle:
    timeout-per-shutdown-phase: ${TIMEOUT_SHUTDOWN}
  # main settings
  main:
    allow-bean-definition-overriding: true
  # webflux settings
  webflux:
    base-path: ${RESOURCE_SERVER_PREFIX}
  # postgreSQL configurations
  r2dbc:
    url: ${R2DBC_POSTGRES_URL}
    username: ${R2DBC_POSTGRES_USERNAME}
    password: ${R2DBC_POSTGRES_PASSWORD}
    pool:
      max-size: 10
      max-acquire-time: 10s
  # flyway configurations
  flyway:
    url: ${JDBC_POSTGRES_URL}
    user: ${R2DBC_POSTGRES_USERNAME}
    password: ${R2DBC_POSTGRES_PASSWORD}
    schemas: public
    table: flyway_schema_history
    locations: classpath:db/migration
    clean-on-validation-error: false
    clean-disabled: false
    baseline-on-migrate: true
    out-of-order: true
    enabled: true
    baseline-description: "init"
    baseline-version: 1
  # security configurations
  security:
    oauth2:
      client:
        registration:
          # oauth2.0 client registrations - (for auth0 auth server)
          auth0:
            client-id: ${AUTH0_SERVER_CLIENT_ID}
            client-secret: ${AUTH0_SERVER_CLIENT_SECRET}
          # oauth2.0 client registrations - (for in-house auth server)

#**********************************************************************************************************************#
#************************************************** SERVER SETTINGS ***************************************************#
#**********************************************************************************************************************#

# default server settings
server:
  address: ${LOCALHOST}
  port: ${RESOURCE_SERVER_PORT}
  ssl:
    enabled: false
  forward-headers-strategy: native

#**********************************************************************************************************************#
#************************************************ SPRING DOC SETTINGS *************************************************#
#**********************************************************************************************************************#

# spring doc settings
springdoc:
  api-docs:
    enabled: true
    version: openapi_3_1
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /v1/swagger-ui.html
    url: /v3/api-docs
    operations-sorter: method
  show-actuator: false
  enable-kotlin: true
  enable-spring-security: true
  enable-default-api-docs: true
  default-produces-media-type: application/json


#**********************************************************************************************************************#
#************************************************** END OF YAML *******************************************************#
#**********************************************************************************************************************#
```

**Env Variables**
My local.env file settings are:

SCHEME=http
HOST=localhost
LOCALHOST=127.0.0.1

TIMEOUT_SHUTDOWN=30s
TIMEOUT_SESSION=2100

REVERSE_PROXY_HOST=localhost
REVERSE_PROXY_PORT=7080

ANGULAR_SERVER_HOST=localhost
ANGULAR_SERVER_PORT=4200
ANGULAR_SERVER_PREFIX=/angular-ui

BFF_SERVER_HOST=localhost
BFF_SERVER_PORT=9090
BFF_SERVER_PREFIX=/bff

RESOURCE_SERVER_PORT=8080
RESOURCE_SERVER_PREFIX=/api/v1/resource

**Resource Server Security Chain**

```
@Configuration
@EnableWebFluxSecurity
@EnableReactiveMethodSecurity(useAuthorizationManager = true)
internal class ResourceSecurityConfig {

    @Bean
    /* security filter chain for authentication & authorization (reactive) */
    /* this should be webSession stateless */
    fun resourceServerSecurityFilterChain(
        http: ServerHttpSecurity,

        authenticationEntryPoint: AuthenticationEntryPoint,
        accessDeniedHandler: AccessDeniedHandler,

        authenticationManagerResolver: ReactiveAuthenticationManagerResolver<ServerWebExchange>,

        ipWhiteListFilter: IPWhiteListFilter,
        validEndPointFilter: ValidEndPointFilter,

        reactiveRequestCache: ReactiveRequestCache,
        statelessSecurityContextRepository: StatelessSecurityContextRepository,

        ): SecurityWebFilterChain {

            /* enable csrf */
            http.csrf { csrf ->
                csrf.disable()
            }

            /* configure request cache */
            http.requestCache { cache ->
                cache.requestCache(reactiveRequestCache)
            }

            /* configure security context */
            http.securityContextRepository(statelessSecurityContextRepository)

            /* configure session management */
            // there is no explicit createSessionPolicy.NEVER for Spring Webflux like there is for Spring Servlet

            /* oauth2.0 resource server */
            http.oauth2ResourceServer { oauth2 ->
                oauth2.authenticationManagerResolver(authenticationManagerResolver)
                oauth2.authenticationEntryPoint(authenticationEntryPoint)
                oauth2.accessDeniedHandler(accessDeniedHandler)
            }

            /* configure authorization  */
            http.authorizeExchange { authorize ->
                authorize
                    .pathMatchers("/hello").permitAll()
                    .pathMatchers(
                        "/v3/api-docs",
                        "/v1/swagger-ui.html",
                        "/v1/webjars/swagger-ui/**").permitAll()
                    .anyExchange().authenticated()
            }

            /* other filters */
            // apply ip-whitelist filter before http basic authentication
            http.addFilterBefore(ipWhiteListFilter, SecurityWebFiltersOrder.HTTP_BASIC)
            // apply valid end-point filter before http basic authentication
            http.addFilterBefore(validEndPointFilter, SecurityWebFiltersOrder.HTTP_BASIC)

            /* exception handling */
            // handlers for any exceptions not handled elsewhere
            http.exceptionHandling { exceptionHandling ->
                exceptionHandling.authenticationEntryPoint(authenticationEntryPoint)
                exceptionHandling.accessDeniedHandler(accessDeniedHandler)
            }

        return http.build()
    }

}
```

Accssing this works:

<img width="601" alt="Screenshot 2024-09-16 at 12 17 46" src="https://github.com/user-attachments/assets/0dece3fe-3ddc-4a16-81bc-69f436c7687b">

But I notice that in the response header, here is no /bff prefix, next to the "Location:" field

Hence, in the next browser re-direct I get this:

<img width="607" alt="Screenshot 2024-09-16 at 12 18 22" src="https://github.com/user-attachments/assets/0aa6a45d-2182-43e8-9d17-5d10f54d1250">

**Spring BFF Config**

I did check my Spring BFF (Spring Cloud Gateway) to see if the relevant headers were being forwarded, and I do see this:
So, all the relevant headers (including an access token)

```
Forwarded: proto=http;host="localhost:7080";for="127.0.0.1:51801"
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
X-Forwarded-Prefix: /bff
X-Forwarded-Port: 7080
X-Forwarded-Host: localhost:7080
host: localhost:9090
content-length: 0
Authorization: Bearer eyJhb...
```

The full settings to my BFF can be found here:

https://github.com/dreamstar-enterprises/docs/blob/master/Spring%20BFF/BFF/src/main/resources/application.yaml

So, I'm not sure why the Resource Server is not adding the /bff Gateway prefix, even though the request should have X-Forwarded-Prefix: /bff present?

Grateful for any help, on where you think I may have gone wrong, or if this is a bug.
