### ISSUE TITLE
Custom actuator endpoint not working in 3.4.0-RC1

### ISSUE THREAD

**Issue by nicolasb29** [spring-projects/spring-boot#42987]
Hi,

I have a custom actuator endpoint that works perfectly in Spring Boot 3.3.5, but it no longer functions in Spring Boot 3.4.0-RC1 (I have a 404 error because the endpoint is not registered).

I created an example project to demonstrate the issue. The source code is available at [this GitHub repository](https://github.com/nicolasb29/testactuator). The main branch uses Spring Boot 3.3.5, while the [3.4.0-RC1_deprecated](https://github.com/nicolasb29/testactuator/tree/3.4.0-RC1_deprecated) branch is based on Spring Boot 3.4.0-RC1.

I have also tried the reworked method with access on [3.4.0-RC1_access](https://github.com/nicolasb29/testactuator/tree/3.4.0-RC1_access), but it does not resolve the issue either.

Test results can be found [here](https://github.com/nicolasb29/testactuator/actions)

The code of the custom actuator endpoint:

```java
@Component
@Endpoint(id = "custom")
public class TestActuatorEndpoint {

    @ReadOperation
    public String read() {
        return "OK";
    }
}
```

The configuration:

```yaml
spring:
  application:
   name: testactuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
  cors:
    allowed-origins: "*"
    allowed-methods: GET
```

**Comment by nicolasb29** [comment]
It seems that the endpoint isn't [invocable](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/annotation/EndpointDiscoverer.java#L212) because operation was filtered (list is empty) due to [this line](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/endpoint/PropertiesEndpointAccessResolver.java#L101).

**Comment by philwebb** [comment]
In Spring Boot 3.3 the `management.endpoints.enabled-by-default` property was exclusively handled by `OnAvailableEndpointCondition`, in 3.4 it's handled at a higher level.

We're reading `management.endpoints.enabled-by-default=false` as a signal to disable any endpoints that haven't been explicitly enabled.

To fix things, you can do the following:

```yaml
spring:
  application:
   name: testactuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    custom:
      enabled: true
  cors:
    allowed-origins: "*"
    allowed-methods: GET
```

(or use the new access properties).

I'm not sure if we should treat this as a regression or not. Arguably, it's more consistent the way things are in 3.4.
