### ISSUE TITLE
External config feature: if no environment variable is set, will use the placeholder name as value

### ISSUE THREAD

**Issue by Gregsen** [spring-projects/spring-boot#4302]
First things first: An example for reproduction can be found at https://github.com/Gregsen/spring-config-tester

I have two environment variables as placeholder in my application.yml.

```
config:
    param: ${SOME_PARAM}
    listParams:
      - Test1
      - Test2
    path: ${SOME_PATH}
```

The first value is loaded via the `@Value("${config.param}")`annotation. The app will not start (as expected) when the env var is not set. 
However, the second value is loaded via configuration class (with `@ConfigurationProperties(prefix = "config")`). When this env var is not set, my application **will** start and the value of my variable is "${SOME_PATH)".
