### ISSUE TITLE
Percentiles not published after inlcuding spring batch dependency

### ISSUE THREAD

**Issue by sikrip** [spring-projects/spring-boot#43049]
Spring boot 3.2.6 (also tried under 3.3.5).

On the app config I have

```
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles:
        all: 0.5, 0.95
```

And I was getting percentiles on my metrics. 

After adding the following dependency:

```
<dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-batch</artifactId>
</dependency>
```

Percentiles stopped being published (unless I explicitly add the percentiles in java code).
