### ISSUE TITLE
Document that server.ssl.cipher and server.ssl.enabled-protocols are not fallbacks used with SSL bundles

### ISSUE THREAD

**Issue by matthew-js-porter** [spring-projects/spring-boot#43353]
When configuring server SSL, would it make sense to fallback to the configured `server.ssl.ciphers` and `server.ssl.enabled-protocols` properties when the SSL Options for a bundle is not specified?

Given this example:

```yaml
server:
  ssl:
    ciphers:
      - TLS_CHACHA20_POLY1305_SHA256
    enabled-protocols:
      - TLSv1.3
    bundle: local
    server-name-bundles:
      - server-name: localhost
        bundle: localhost
      - server-name: 127.0.0.1
        bundle: local
      - server-name: other
      - bundle: other

spring:
  ssl:
    bundle:
      jks:
        localhost:
          keystore:
            location: "classpath:test-keystore.jks"
            password: secret
            type: JKS
        local:
          keystore:
            location: "classpath:test-keystore.jks"
            password: secret
            type: JKS
        other:
          keystore:
            location: "classpath:test-keystore.jks"
            password: secret
            type: JKS
          options:
            ciphers:
              - TLS_AES_256_GCM_SHA384
            enabled-protocols:
              - TLSv1.3
```

I would expect the server to use `TLS_CHACHA20_POLY1305_SHA256` and `TLSv1.3` for **localhost** and **127.0.0.1** and `TLS_AES_256_GCM_SHA384` for **other**.

**Comment by philwebb** [comment]
I can see why falling back would make sense, but I'm concerned it would then make it hard for a bundle to indicate that it wants to use the server defaults and not apply any customization. This would also be a breaking change, so not something we can consider until 3.5 at the earliest. It would also mean that the bundle could behave differently depending on where it was used.

I'm wondering if we should add something to `spring.ssl.bundle` if we want a way to apply default options to all bundles. Something like:

```yaml
spring:
  ssl:
    bundle:
      default-options:
        ciphers:
        - TLS_CHACHA20_POLY1305_SHA256
        enabled-protocols:
        - TLSv1.3
      jks:
        localhost:
          keystore:
            location: "classpath:test-keystore.jks"
            password: secret
            type: JKS
        local:
          keystore:
            location: "classpath:test-keystore.jks"
            password: secret
            type: JKS
        other:
          keystore:
            location: "classpath:test-keystore.jks"
            password: secret
            type: JKS
          options:
            ciphers:
              - TLS_AES_256_GCM_SHA384
            enabled-protocols:
              - TLSv1.3
```
