### ISSUE TITLE
Whether it is possible to create a class annotated by @ConfigurationProperties before the AOT processing stage can be used directly in BeanFactoryInitializationAotContribution

### ISSUE THREAD

**Issue by admintertar** [spring-projects/spring-boot#43426]
For example, the AOT processing stage reads mapperLocations in mybatisProperties to add hints.resources()

```
public class MybatisBeanFactoryInitializationAotContribution implements BeanFactoryInitializationAotContribution {

    private final MybatisProperties mybatisProperties;

    public MybatisBeanFactoryInitializationAotContribution(MybatisProperties mybatisProperties) {
        this.mybatisProperties = mybatisProperties;
    }

    @Override
    public void applyTo(GenerationContext generationContext, BeanFactoryInitializationCode beanFactoryInitializationCode) {
        log.info("MybatisBeanFactoryInitializationAotContribution {}", mybatisProperties.getMapperLocations());

        RuntimeHints hints = generationContext.getRuntimeHints();

        String[] mapperLocations = mybatisProperties.getMapperLocations();
        if (mapperLocations != null) {
            log.info("mapperLocations-{}", mapperLocations);
            Stream.of(mapperLocations).map(item -> item.replace("classpath:/", "")).forEach(hints.resources()::registerPattern);
        }
    }

}
```

```
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
```
