### ISSUE TITLE
Usage list type for spring.autoconfigure.exclude property in Yaml

### ISSUE THREAD

**Issue by mind-blowing** [spring-projects/spring-boot#4352]
Can you please add ability to use list in yml for spring.autoconfigure.exclude. 

Currently in Spring Boot 1.3.0.RC1 is possible only such usage:
```yaml
spring:
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration,
      org.springframework.boot.actuate.autoconfigure.ManagementWebSecurityAutoConfiguration,
      org.springframework.boot.autoconfigure.security.FallbackWebSecurityAutoConfiguration
```

But it will be nice to use regular list syntax, like this:
```yaml
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.FallbackWebSecurityAutoConfiguration
```
