### ISSUE TITLE
AutoConfiguredRestClientSsl overwrites configuration from HttpClientProperties

### ISSUE THREAD

**Issue by kzander91** [spring-projects/spring-boot#43618]
This is similar to #36594 and #27360 but I'm not sure if a solution for those issues would also fix mine, so feel free to close this if you consider this to be a duplicate.

Issue: Configuration made through the `spring.http.client` properties is ignored if I use `AutoConfiguredRestClientSsl`. For example, configuration like
```yaml
spring:
  http:
    client:
      redirects: dont_follow
```
does not work if I also have this:
```java
@Bean
RestClientCustomizer clientCertConfigurer(RestClientSsl restClientSsl) {
    return builder -> builder.apply(restClientSsl.fromBundle("my-bundle"));
}
```

The reason for this is that `AutoConfiguredRestClientSsl` _replaces_ the request factory and thus discards any configuration made via the `spring.http.client` properties:
https://github.com/spring-projects/spring-boot/blob/183285258d7b5092224eab1600a2cfa8332682d9/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/client/AutoConfiguredRestClientSsl.java#L52-L56

For _this_ specific issue I can work around this by removing my `RestClientCustomizer` and use
```yaml
spring:
  http:
    client:
      redirects: dont_follow
      ssl:
        bundle: "my-bundle"
```
instead, but this only works in this static scenario, if I needed some more sophisticated logic to determine the SSL bundle to use at runtime, this wouldn't work.
