### ISSUE TITLE
build doc task failed

### ISSUE THREAD

**Issue by stepjacky** [spring-projects/spring-boot#43634]
I execute build task on spring boot project ,after clone spring boot project code to local disk ,and check branch to **docs-build** ,then run node run.js on current path 
but npx complains with  the flowwing error stacks:
 Running Antora
```
$ npx antora antora-playbook.yml --stacktrace --ui-bundle-url https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.18/ui-bundle.zip
[17:28:06.247] FATAL (antora): Unable to download 'https://repo.spring.io/release/org/springframework/boot/spring-boot-docs/3.3.7/spring-boot-docs-3.3.7-root-aggregate-content.zip' due to HTTP response code 401 ()
    Cause: HTTPError
        at download (/home/jacky/projects/spring-boot/node_modules/@springio/antora-zip-contents-collector-extension/lib/index.js:401:27)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async getZipFile (/home/jacky/projects/spring-boot/node_modules/@springio/antora-zip-contents-collector-extension/lib/index.js:284:20)
        at async doWithIncludes (/home/jacky/projects/spring-boot/node_modules/@springio/antora-zip-contents-collector-extension/lib/index.js:243:23)
        at async addContentAggregateIncludes (/home/jacky/projects/spring-boot/node_modules/@springio/antora-zip-contents-collector-extension/lib/index.js:110:7)
        at async GeneratorContext.contentAggregated (/home/jacky/projects/spring-boot/node_modules/@springio/antora-zip-contents-collector-extension/lib/index.js:48:11)
        at async GeneratorContext.notify (/home/jacky/projects/spring-boot/node_modules/@antora/site-generator/lib/generator-context.js:65:39)
        at async Promise.all (index 0)
        at async generateSite (/home/jacky/projects/spring-boot/node_modules/@antora/site-generator/lib/generate-site.js:25:5)
        at async Command.parseAsync (/home/jacky/projects/spring-boot/node_modules/commander/lib/command.js:935:5)
Unexpected error
```

obviously ,it told me that the resource https://repo.spring.io/release/org/springframework/boot/spring-boot-docs/3.3.7/spring-boot-docs-3.3.7-root-aggregate-content.zip
can not be download ,and then I checkout the antora-playbook.yml file and found need username/password
it's config 
   ```
    **username: '${env.ARTIFACTORY_USERNAME}'
    password: '${env.ARTIFACTORY_PASSWORD}'**
    locations:
    - url: https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-docs/${version}/spring-boot-docs-${version}-${name}-${classifier}.zip
      for-version-type: [snapshot]
    - url: https://repo.spring.io/milestone/org/springframework/boot/spring-boot-docs/${version}/spring-boot-docs-${version}-${name}-${classifier}.zip
      for-version-type: [milestone, rc]
    - url: https://repo.spring.io/release/org/springframework/boot/spring-boot-docs/${version}/spring-boot-docs-${version}-${name}-${classifier}.zip
      for-version-type: [release]
    # The root component extension must be last!
  - require: '@springio/antora-extensions/root-co
```
as used it as a open source project ,how can i found these resource ?
