### ISSUE TITLE
Add support for configuring the Redis database using spring.data.redis.url

### ISSUE THREAD

**Issue by Demonese** [spring-projects/spring-boot#43810]
Both Jedis and Lettese clients support specifying a database in the URL
* Jedis: https://github.com/redis/jedis/blob/master/src/main/java/redis/clients/jedis/util/JedisURIHelper.java
* Lettuce: https://github.com/redis/lettuce/wiki/Redis-URI-and-connection-details

Unfortunately, [spring-boot-autoconfigure ignore them](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/PropertiesRedisConnectionDetails.java)
```java
	@Override
	public Standalone getStandalone() {
		if (this.properties.getUrl() != null) {
			ConnectionInfo connectionInfo = connectionInfo(this.properties.getUrl());
			return Standalone.of(connectionInfo.getUri().getHost(), connectionInfo.getUri().getPort(),
					this.properties.getDatabase());
		}
		return Standalone.of(this.properties.getHost(), this.properties.getPort(), this.properties.getDatabase());
	}
```

This causes the following URL actually connect to database 0
```yaml
spring:
  data:
    redis:
      url: redis://127.0.0.1:6379/8
```

The current workaround in my project is
```yaml
spring:
  data:
    redis:
      url: redis://127.0.0.1:6379/8
      database: 8
```

: (
