### ISSUE TITLE
endpoints.configprops.keys-to-sanitize ignores prefixes

### ISSUE THREAD

**Issue by westse** [spring-projects/spring-boot#4415]
`endpoints.configprops.keys-to-sanitize` only works on keys mapped to the `@ConfigurationProperties`-annotated bean, and not on the prefix (declared with `ConfigurationProperties.prefix`).

For example, given this configuration
````
endpoints.configprops.keys-to-sanitize=*\.secrets.*
my.prefix.secrets:
  mine: "mySecret"
  yours: "yourSecret"
````
and a bean
````
@ConfigurationProperties("my.prefix")
@Component
public class MyConfigProperties {
    private Map<String, String> secrets;
}
````
Then the `/configprops` actuator endpoint should sanitize the contents of `MyConfigProperties.secrets`, but does not, thereby exposing the secret values.

For now, we have had to disable configprops actuator (`endpoints.configprops.enabled: false`).
