### ISSUE TITLE
List Environment Variable Binding Error in SpringBoot 3.4.0

### ISSUE THREAD

**Issue by hky035** [spring-projects/spring-boot#44508]
Hello,
I am working on a project using Spring Boot 3.4.0. 
I defined **_List_** environment variables, but I encountered a binding error.

Here is my code and the error log:

```yaml
// application.yml
kis:
  domain: ${KIS_DOMAIN:domain}
  appkey:
  - ${KIS_APPKEY_1:appkey}
  - ${KIS_APPKEY_2:appkey}
  appsecret:
  - ${KIS_APPSECRET_1:appsecret}
  - ${KIS_APPSECRET_2:appsecret}
  web-socket-domain: ${KIS_WEBSOCKET_DOMAIN:domain}
```

```java
// KisProperties.java
@Component
@ConfigurationProperties(prefix = "kis")
@Getter
@Setter
@ToString
public class KisProperties {
    private String domain;
    private String webSocketDomain;
    private List<String> appkey;
    private List<String> appsecret;

   ...
}
```

```
Description:

Binding to target [Bindable@651a3e01 type = java.util.List<java.lang.String>, value = 'provided', annotations = array<Annotation>[[empty]], bindMethod = [null]] failed:

    Property: kis.appkey[1]
    Value: "===hidden==="
    Origin: System Environment Property "KIS_APPKEY_1"
    Reason: The elements [kis.appkey[1],kis.appkey[2]] were left unbound.
    Property: kis.appkey[2]
    Value: "===hidden==="
    Origin: System Environment Property "KIS_APPKEY_2"
    Reason: The elements [kis.appkey[1],kis.appkey[2]] were left unbound.

Action:

Update your application's configuration
```

I resolved the issue by changing the environment variable names. 

```yaml
// application.yml
kis:
  domain: ${KIS_DOMAIN:domain}
  appkey:
  - ${KIS_APPKEY_0:appkey}  # 1 → 0
  - ${KIS_APPKEY_1:appkey}  # 2 → 1
  appsecret:
  - ${KIS_APPSECRET_0:appsecret}  # 1 → 0
  - ${KIS_APPSECRET_1:appsecret}  # 2 → 1
  web-socket-domain: ${KIS_WEBSOCKET_DOMAIN:domain}
```

I believe the error occurred because the environment variable names ended with _1, which led to them being bound as [1].

According to the [official documentation](https://docs.spring.io/spring-boot/3.3/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables), the variable names should be wrapped in underscores with numbers to be properly bound. 

> **"Environment variables can also be used when binding to object lists. To bind to a List, the element number should be surrounded with underscores in the variable name."**
\- SpringBoot 3.3.9 and SpringBoot 3.4.3 Documentation

However, in my case, `KIS_APPKEY_1`, `KIS_APPKEY_2` were bound as `KIS_APPKEY_[1]`, `KIS_APPKEY_[2]`, resulting in a binding error.

To test this issue, I used Spring Boot 3.4.3 with the same configuration, and it executed successfully.

I am curious why this error occurs only in 3.4.0 and why Spring Boot 3.3.9 and 3.4.3 behave differently, even though the official documentation regarding environment variable binding is the same for both versions.
