### ISSUE TITLE
spring-boot-docker-compose: ignore healthchecks for services labeled with org.springframework.boot.ignore

### ISSUE THREAD

**Issue by ArnauAregall** [spring-projects/spring-boot#44711]
Similar to what `org.springframework.boot.ignore` labels does to ignore the auto service connections for some compose services, would be really helpful to also ignore the labeled services **healthchecks** to be able to start the application.

As an example use case:

```yml
  # Database service where app will automatically connect using Spring Data JDBC
  postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'postgres'
  # Third party service own database, ignored
  third_party_service_database:
    image: postgres:16-alpine
    restart: always
    ports:
      - '5433:5433'
    environment:
      PGPORT: '5433'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - 'third_party_service_'
    volumes:
      - 'third_party_service_database_volume:/var/lib/postgresql/data:rw'
    labels:
      org.springframework.boot.ignore: true # Ignore third_party_service_database for application JDBC connection
```

When starting the Spring Boot application it could also ignore the healthcheck of `third_party_service_database`. 

This would allow us to auto start and connect to our application to the needed services (`postgres`), but also start and ignore completely the `third_party_service_database`, which is added to compose for commodity on bootstraping third party dependencies and not mandatory to start the app.

A new label like `org.springframework.boot.ignore.health-check` would also work.
