### ISSUE TITLE
Cannot override properties from imported config

### ISSUE THREAD

**Issue by williamwjs** [spring-projects/spring-boot#44723]
Assuming the below files on my classpath:

- application-staging.yml
```
spring:
  data:
    mongodb:
      uri: stagingUrI

# ... (bunch of other properties)
```

- application-dev.yml
```
spring:
  config:
    import: application-staging.yml
  data:
    mongodb:
      uri: myDevOne
```

When running with dev profile:

Expected: `spring.data.mongodb.uri` is `myDevOne`
Actual: `spring.data.mongodb.uri` is `stagingUrI`

Is it something that should support?
Thank you!
