### ISSUE TITLE
Show the use of token properties in authorization server clients configuration example

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#44990]
Spring Authorization Server allows defining per-client token settings.
https://github.com/spring-projects/spring-authorization-server/issues/1385#issuecomment-1772439977

However, Boot's `OAuth2AuthorizationServerProperties` does not expose this. I'd like to see something like this:

```yaml
spring.security.oauth2.authorizationserver.client:
  my-client:
    client-id: 41fd9212-dc6f-4ced-a7a8-e6431a3f49da
    client-secret: '{noop}secret'
    tokens:
      authorization-code-time-to-live: 5m
      access-token-time-to-live: 10m
      access-token-format: reference
      reuse-refresh-tokens: false
      refresh-token-time-to-live: 28d
```

Possibly an ability to set a default for all clients too.
