### ISSUE TITLE
Inconsistent docker-compose path resolution in multi-module project

### ISSUE THREAD

**Issue by devmizz** [spring-projects/spring-boot#45169]
Hello,
I’m currently using the docker-compose dependency in a multi-module project.

In one of the submodules, I configured the `application.yaml` to reference the path to the Docker Compose file, and it works correctly when running the main application. However, I encountered an issue when writing tests that also rely on the same docker-compose setup: an exception is thrown indicating that the Compose file cannot be found at the specified path.

For example, assuming the root project is named root, the submodule is app, and the Docker Compose file is located at `root/app/docker/docker-compose.yaml`

#### root/app/docker/docker-compose.yaml
```yaml
services:
    mysql:
        container_name: practice-mysql
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: practice
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
```

#### root/app/src/main/resources/application.yaml
```yaml
spring:
    docker:
        compose:
            enabled: true
            service: spring-practice
            stop:
                command: down
            skip:
                in-tests: false
            file: app/docker/docker-compose.yaml
```

<img src="https://github.com/user-attachments/assets/0b5af2af-c092-46dc-8c93-12cf692dc2fc" width=60%>

<img src="https://github.com/user-attachments/assets/4c295ced-ae49-4847-aa7f-23967bd69ada" width=60%>

-	When running the main application, FS.userDir is set to root
-	But when running tests, FS.userDir is set to root/app

Because of this difference, the path resolution behaves inconsistently between main and test executions. As a workaround, I ended up duplicating the `application.yaml` under the test resources and customizing the path manually for tests.

#### root/app/test/resources/application.yaml
```yaml
spring:
    docker:
        compose:
            # ...
            file: docker/docker-compose.yaml
```

Even though the Docker Compose file is located in the same path, the behavior varies depending on whether the main application or tests are being run. This inconsistency can lead to confusion and misconfiguration.

Would it be possible to improve this so that the Compose file path resolution is consistent within the same module, regardless of whether it’s running as part of the main application or during tests?

Here is my [sub-module link](https://github.com/devmizz/spring-boot-practice/tree/main/app)

**Comment by nosan** [comment]
Hello @devmizz

Unfortunately, you haven't provided details about exactly how you're running your application, but I'll assume you're using IntelliJ IDEA. When you run `AppApplication` via IntelliJ IDEA, the working directory automatically defaults to the [project's root directory](https://www.jetbrains.com/help/idea/run-debug-configuration-spring-boot.html#operating-system), which in your case is **spring-boot-practice**. Therefore, the file `app/docker/docker-compose.yaml` is correctly found, allowing all required Docker containers to start properly.

However, when executing tests, IntelliJ IDEA uses the module directory as the working directory (`$MODULE_WORKING_DIR$`). In your specific scenario, this corresponds to **spring-boot-practice/app**. Consequently, the path `app/docker/docker-compose.yaml` becomes incorrect, resulting in the error: `Docker Compose file 'app/docker/docker-compose.yaml' does not exist`.

I've tried running your application directly via Gradle:

```shell
cd app
gradle bootRun
```

However, it fails due to the same issue:

```
/Users/dmytronosan/IdeaProjects/spring-boot-practice/app % gradle :bootRun


> Task :bootRun FAILED

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.4.4)

2025-04-13T13:21:36.516+03:00  INFO 73706 --- [           main] co.app.AppApplicationKt                  : Starting AppApplicationKt using Java 21.0.4 with PID 73706 (/Users/dmytronosan/IdeaProjects/spring-boot-practice/app/build/classes/kotlin/main started by dmytronosan in /Users/dmytronosan/IdeaProjects/spring-boot-practice/app)
2025-04-13T13:21:36.517+03:00  INFO 73706 --- [           main] co.app.AppApplicationKt                  : No active profile set, falling back to 1 default profile: "default"
2025-04-13T13:21:36.591+03:00 ERROR 73706 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalArgumentException: Docker Compose file 'app/docker/docker-compose.yaml' does not exist

```


If you remove the `application.yaml` file from your test resources and update your `application.yaml` and `docker-compose.yaml` files accordingly:

**application.yaml:**
```yaml
spring:
    docker:
        compose:
            enabled: true
            service: spring-practice
            lifecycle-management: start_only
            stop:
                command: down
            skip:
                in-tests: false
            file: docker/docker-compose.yaml
```

**docker-compose.yaml:**

```yaml
services:
    mysql:
        container_name: practice-mysql
        image: mysql:8.0
        ports:
            - '3308:3306'
        environment:
            MYSQL_DATABASE: practice
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        restart: always
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --skip-character-set-client-handshake

    redis:
        image: redis:alpine
        ports:
            - "6380:6379"
```

Then both Gradle tasks, `bootRun` and `build` will work correctly.


You can also resolve this issue in IntelliJ IDEA by configuring the working directory when running your Spring Boot application:

<img width="1155" alt="Image" src="https://github.com/user-attachments/assets/7955e49e-bde8-4247-bda6-a6aa342b54dc" />
