### ISSUE TITLE
Wrong log level from /actuator/loggers

### ISSUE THREAD

**Issue by cdprete** [spring-projects/spring-boot#45868]
Hello.

In my application I'm using Spring Boot 3.5.0 with the Log4j2 loggers configured externally as follows:
```xml
<Loggers>
    <Root level="info">
        <AppenderRef ref="ApplicationLogs"/>
        <AppenderRef ref="PatrolLogs"/>
        <AppenderRef ref="SplunkLogs"/>
    </Root>
    <Logger name="SplunkMeterRegistry" level="info" additivity="false">
        <AppenderRef ref="MetricsLogs"/>
    </Logger>
    <Logger name="InvalidMessagesLogger" level="warn" additivity="false">
        <AppenderRef ref="InvalidMsgsLogs"/>
    </Logger>
    <Logger name="com.netflix.eureka" level="OFF" additivity="false" />
    <Logger name="com.netflix.discovery" level="OFF" additivity="false" />
    <Logger name="foo.client.consumer" level="DEBUG"/>
</Loggers>
```
but then, in Spring Boot Admin as well as calling the `GET /actuator/loggers`, I can see all the loggers on `DEBUG` level:

![Image](https://github.com/user-attachments/assets/f0656ad5-1d34-4864-af68-b4fef8d90711)

Moreover, according to the feedback provided in https://github.com/spring-projects/spring-boot/issues/45854, `POST /loggers/{name} <body>` should also work if the logging is configured externally (`-Dlogging.config=config/log4j2-spring.xml` in my case), but it doesn't. 
Even if in Spring Boot Admin I change the log level, nothing happens.

On the contrary, the logging handling seems to be way worse now that I updated the application to Spring Boot 3.5.0, because the `SplunkMeterRegistry` is not dumping anymore the Micrometer metrics into the "log" file.
More info on it:
```java
public class SplunkMeterRegistry extends StepMeterRegistry {
    ...
    private final static Logger metricsLogger = LoggerFactory.getLogger("SplunkMeterRegistry");
    private final StepRegistryConfig config;

    public SplunkMeterRegistry(StepRegistryConfig config, Clock clock) {
        super(config, clock);
        this.config = config;
        start(new NamedThreadFactory("logging-metrics-publisher"));
    }

    @Override
    protected void publish() {
        if (config.enabled())
            getMeters().forEach(meter -> metricsLogger.info("metric_name={}{}{}", meter.getId().getName(),
                    meter.getId().getTags().stream().map(m -> m.getKey() + "=" + m.getValue()).collect(Collectors.joining(",", ",", "")),
                    StreamSupport.stream(meter.measure().spliterator(), false).map(m -> m.getStatistic().name() + "=" + m.getValue()).collect(Collectors.joining(",", ",", ""))));
    }

    protected TimeUnit getBaseTimeUnit() {
        return TimeUnit.MILLISECONDS;
    }
}

**Comment by wilkinsona** [comment]
Thanks for the report but it isn't actionable as we can't see the full picture. For example, you have only provided a section of your logging configuration. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by cdprete** [comment]
> Thanks for the report but it isn't actionable as we can't see the full picture. For example, you have only provided a section of your logging configuration. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

Hello.

Given that the logging configuration shows the `root` logger with level `info` but then in the UI everything is on level `debug`, it's already clear to me there is something that doesn't work anymore. 

Anyway, in terms of configuration:
`application.yaml` (delivered within the JAR):
```yaml
spring:
  application.name: HIKU MDF PoolFiller
  cloud.discovery.client.health-indicator.enabled: false

server:
  http2.enabled: true
  compression.enabled: true
  servlet.jsp.registered: false

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    # Disable some unneeded endpoints by setting the access to none
    env.access: none
    conditions.access: none
    configprops.access: none
    beans.access: none
    caches.access: none
    mappings.access: none
    features.access: none
    health:
      show-details: always
      show-components: always
  info:
    os.enabled: true
    env.enabled: true
    java.enabled: true
    process.enabled: true
  health:
    ssl.enabled: false
    eureka.enabled: false
    diskspace.path: ${hikupoolfiller.filesystem.paths.poolfiller-home}

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    metadata-map.management.context-path: ${spring.webflux.base-path:}/actuator
    status-page-url-path: ${eureka.instance.metadata-map.management.context-path}/info
    health-check-url-path: ${eureka.instance.metadata-map.management.context-path}/health
  client:
    enabled: false
    fetch-registry: false
    jersey.enabled: false
    webclient.enabled: true
    service-url.defaultZone: http://${eureka.instance.hostname}:8761/${spring.webflux.base-path:}/eureka

hikupoolfiller:
  stt:
    enabled: ...
  mdstreamer:
    # by default retry 300 times for 5 minutes against one or (hopefully) more instances
    retries: 300
    retryFixedDelay: 1s
    readTimeout: 30s
    connectionTimeout: 30s
    batchSize: 1_000
    backfill:
      enabled: false
      # ISO-8601 format
      # If you wish to backfill more data than is available on merge servers, use corresponding trace servers (hosts configuration)
      dateTimeFrom: 2024-10-25T07:30Z
      # ISO-8601 format
      # If user wishes to backfill data until now, dateTimeTo have to be set up far into the future i.e. year 2099.
      dateTimeTo: 2099-10-25T07:40Z

  rollover:
    per-message-type-rollover-duration:
      PED: 5m
      AED: 5m
      LED: 5m
      LMD: 1h
    max-number-of-lines-per-file: 100_000
    batchSize: 1_000
    batchTimeout: 5s
  filesystem:
    paths:
      working-directory: target/
      poolfiller-home: ${hikupoolfiller.filesystem.paths.working-directory}/hikupf_message_pool
      gsn: ${hikupoolfiller.filesystem.paths.poolfiller-home}/gsn.txt
      # check MASTER file only on environments with multi-regions deployments (DEV, QA, PROD).
      check-master-file-existence: true
      master-file: /etc/opt/six/hiku/control/MASTER

metrics:
  step: 1m
```
`application-dev.yaml` (external configuration under `$PWD/config`):
```yaml
hikupoolfiller:
  mdstreamer:
    hostnames: [ ...]
    port: 16100
  filesystem:
    paths:
      working-directory: /
      poolfiller-home: ${hikupoolfiller.filesystem.paths.working-directory}/hikupf_message_pool_dev/fromEODM
  bc-configuration:
    bc-config-resource: file:config/bc-configuration-dev.csv

server.port: 8029

eureka.client:
  enabled: true
  service-url.defaultZone: https://foo/eureka

info.tags.environment: dev

management.endpoint.logfile.external-file: log/hiku-mdf-poolfiller.log
```
`log4j2-spring.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="warn">
    <Properties>
        <Property name="APPLICATION_NAME" value="hiku-mdf-poolfiller"/>
        <Property name="LOG_DIRECTORY" value="log"/>
        <Property name="LOG_ARCHIVE_DIRECTORY" value="${LOG_DIRECTORY}/archive"/>
        <Property name="APPLICATION_LOG_FILENAME" value="${APPLICATION_NAME}"/>
        <Property name="INVALID_MSG_LOG_FILENAME" value="invalid_msgs.log"/>
        <Property name="PATROL_LOG_FILENAME" value="patrol.log"/>
        <Property name="SPLUNK_APPLICATION_LOG_FILENAME" value="splunk.log"/>
        <Property name="METRICS_FILENAME" value="metrics.log"/>
        <Property name="HIKU_COMPATIBLE_PATTERN"
                  value="%d{yyyy-MM-dd'T'HH:mm:ss},%p,${sys:hostName},${sys:user.name},${APPLICATION_NAME},%t,%c{1.}:%L,%m%n"/>
        <Property name="PATROL_PATTERN" value="%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%t] %-5p %c - %msg%n%xEx"/>
    </Properties>
    <Appenders>
        <RollingFile name="ApplicationLogs" fileName="${LOG_DIRECTORY}/${APPLICATION_LOG_FILENAME}.log"
                     filePattern="${LOG_ARCHIVE_DIRECTORY}/${APPLICATION_LOG_FILENAME}_%d{yyyy-MM-dd}_%i.log">
            <PatternLayout pattern="${HIKU_COMPATIBLE_PATTERN}" charset="UTF-8"/>
            <Policies>
                <OnStartupTriggeringPolicy/>
                <TimeBasedTriggeringPolicy/>
            </Policies>
            <DefaultRolloverStrategy max="200">
                <Delete basePath="${LOG_ARCHIVE_DIRECTORY}" maxDepth="1">
                    <IfFileName glob="${APPLICATION_LOG_FILENAME}*.log"/>
                    <IfLastModified age="90d"/>
                </Delete>
            </DefaultRolloverStrategy>
        </RollingFile>
        <RollingFile name="SplunkLogs" fileName="${LOG_DIRECTORY}/${SPLUNK_APPLICATION_LOG_FILENAME}"
                     filePattern="${LOG_ARCHIVE_DIRECTORY}/splunk_%d{yyyy-MM-dd}_%i.log">
            <UnifiedLogEventLayout environment="${sys:spring.profiles.active}">
                <!--TODO fill applicationId and componentId once it's being established -->
                <Product name="hiku-mdf-poolfiller"
                         version="${project.version}"
                         vendor="FOO"
                         applicationId="TBD"
                         componentId="TBD"
                />
            </UnifiedLogEventLayout>
            <Policies>
                <TimeBasedTriggeringPolicy/>
            </Policies>
            <DefaultRolloverStrategy>
                <Delete basePath="${LOG_ARCHIVE_DIRECTORY}" maxDepth="1">
                    <IfFileName glob="splunk*.log"/>
                    <IfLastModified age="10d"/>
                </Delete>
            </DefaultRolloverStrategy>
        </RollingFile>

        <RollingFile name="MetricsLogs" fileName="${LOG_DIRECTORY}/${METRICS_FILENAME}"
                     filePattern="${LOG_ARCHIVE_DIRECTORY}/metrics_%d{yyyy-MM-dd}_%i.log">
            <PatternLayout pattern="ts=%d{ISO8601_OFFSET_DATE_TIME_HHCMM},%m%n"/>
            <Policies>
                <TimeBasedTriggeringPolicy/>
            </Policies>
            <DefaultRolloverStrategy>
                <Delete basePath="${LOG_ARCHIVE_DIRECTORY}" maxDepth="1">
                    <IfFileName glob="metrics*.log"/>
                    <IfLastModified age="10d"/>
                </Delete>
            </DefaultRolloverStrategy>
        </RollingFile>

        <RollingFile name="PatrolLogs" fileName="${LOG_DIRECTORY}/${PATROL_LOG_FILENAME}"
                     filePattern="${LOG_ARCHIVE_DIRECTORY}/patrol.%d{yyyy-MM-dd}.log">
            <PatternLayout pattern="${PATROL_PATTERN}"/>
            <ThresholdFilter level="ERROR" onMatch="ACCEPT" onMismatch="DENY"/>
            <Policies>
                <TimeBasedTriggeringPolicy/>
            </Policies>
            <DefaultRolloverStrategy max="200">
                <Delete basePath="${LOG_ARCHIVE_DIRECTORY}" maxDepth="1">
                    <IfFileName glob="patrol*.log"/>
                    <IfLastModified age="30d"/>
                </Delete>
            </DefaultRolloverStrategy>
        </RollingFile>
        <RollingFile name="InvalidMsgsLogs" fileName="${LOG_DIRECTORY}/${INVALID_MSG_LOG_FILENAME}"
                     filePattern="${LOG_ARCHIVE_DIRECTORY}/invalid_msgs_%d{yyyy-MM-dd}_%i.log">
            <PatternLayout pattern="${HIKU_COMPATIBLE_PATTERN}" charset="UTF-8"/>
            <Policies>
                <OnStartupTriggeringPolicy/>
                <TimeBasedTriggeringPolicy/>
            </Policies>
            <DefaultRolloverStrategy>
                <Delete basePath="${LOG_ARCHIVE_DIRECTORY}" maxDepth="1">
                    <IfFileName glob="invalid_msgs_*.log"/>
                    <IfLastModified age="10d"/>
                </Delete>
            </DefaultRolloverStrategy>
        </RollingFile>


    </Appenders>
    <Loggers>
        <Root level="info">
            <AppenderRef ref="ApplicationLogs"/>
            <AppenderRef ref="PatrolLogs"/>
            <AppenderRef ref="SplunkLogs"/>
        </Root>
        <Logger name="SplunkMeterRegistry" level="info" additivity="false">
            <AppenderRef ref="MetricsLogs"/>
        </Logger>
        <Logger name="InvalidMessagesLogger" level="warn" additivity="false">
            <AppenderRef ref="InvalidMsgsLogs"/>
        </Logger>
        <Logger name="com.netflix.eureka" level="OFF" additivity="false" />
        <Logger name="com.netflix.discovery" level="OFF" additivity="false" />
        <Logger name="foo.client.consumer" level="DEBUG"/>
    </Loggers>
</Configuration>
```
The application is started as 
```shell
"$JAVA_HOME/bin/java" -Dlogging.config='config/log4j2-spring.xml' -Dspring.profiles.active=${profile} -Djavax.net.ssl.trustStore="/etc/pki/java/cacerts" -jar hiku-mdf-poolfiller.jar
```
