### ISSUE TITLE
Spring Boot Undertow Compression not work

### ISSUE THREAD

**Issue by masonmei** [spring-projects/spring-boot#4769]
When use Undertow with following configuration, the response is not compressed

```
server:
  port: 8888
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - application/json
      - application/xml
      - application/xhtml+xml
      - text/html
      - text/xml
      - text/plain
```
