### ISSUE TITLE
Spring boot ssl optoins do not get propagated to Embedded Undertow server.

### ISSUE THREAD

**Issue by reddy6ue** [spring-projects/spring-boot#4805]
I am unable to access my REST urls after I configure SSL in the application.yml. Here are the security options I used. 

```
server:
    contextPath: /myapps
    port: 8000
    ssl:
        enabled: true
        keyStore: classpath:mykeystore.db
        keyStorePassword: changeit
        keyPassword: changeit
```

Has anybody successfully used an ssl based embedded undertow container on spring boot? I was unable to find anybody who did.
