### ISSUE TITLE
Error {too many redirects} when get to root actuator endpoint with management.context-path property

### ISSUE THREAD

**Issue by sixrandanes** [spring-projects/spring-boot#4853]
I've got an infinite loop when I am trying to get to the root actuator endpoint with that configuration :
```
management:
 port: 8084
 address: 127.0.0.1
 context-path: /supervision
```

1/ http://localhost:8084/supervision is redirected to http://localhost:8084/supervision/
2/ http://localhost:8084/supervision/  is redirected to http://localhost:8084/supervision

Partially due to my previous issue : #4575

I am using spring-boot 1.3.1.
