### ISSUE TITLE
/docs actuator not found when endpoints.enabled:false and endpoints.docs.enabled: true

### ISSUE THREAD

**Issue by RaphC** [spring-projects/spring-boot#5007]
Hi 

I'm facing an issue about /docs endpoint

If i disabled all endpoints by default and enable only docs endpoints:

```yaml
endpoints:
 enabled: false # par defaut desactive
 docs:
   enabled: true
```

The application returns 404 where if I enable all by default it works.
