### ISSUE TITLE
Make autoconfig work better for web app with client credentials and @EnableOAuth2Client

### ISSUE THREAD

**Issue by fkowal** [spring-projects/spring-boot#5011]
I have a web application, configured like this

```
security:
  basic.enabled: false
  sessions: stateless
  oauth2:
    client:
      id: 'id'
      grant-type: client_credentials
      client-id: client_id
      client-secret: secret
      scope: myscope
      access-token-uri: http://someuri/oauth/token
    resource:
      jwt.key-uri: http://someuri/oauth/token_key
```

I @EnableOAuth2Client hoping that OAuthRestTemplate would use client_credentials on use.

sadly OAuth2RestOperationsConfiguration has the following code:

``` @Configuration
    protected abstract static class BaseConfiguration {

        @Bean
        @ConfigurationProperties("security.oauth2.client")
        @Primary
        public AuthorizationCodeResourceDetails oauth2RemoteResource() {
            AuthorizationCodeResourceDetails details = new AuthorizationCodeResourceDetails();
            return details;
        }

    }

    @Configuration
    @ConditionalOnNotWebApplication
    protected static class SingletonScopedConfiguration {

        @Bean
        @ConfigurationProperties("security.oauth2.client")
        @Primary
        public ClientCredentialsResourceDetails oauth2RemoteResource() {
            ClientCredentialsResourceDetails details = new ClientCredentialsResourceDetails();
            return details;
        }

        @Bean
        public DefaultOAuth2ClientContext oauth2ClientContext() {
            return new DefaultOAuth2ClientContext(new DefaultAccessTokenRequest());
        }

    }
```

SingletonScopedConfiguration is not used because of ConditionalOnNotWebApplication

AuthorizationCodeResourceDetails is created BUT the grant_type is overriden and set to _client_credentials_ :/. This causes AuthorizationCodeAccessTokenProvider to fail on 

```
public boolean supportsResource(OAuth2ProtectedResourceDetails resource) {
        return resource instanceof AuthorizationCodeResourceDetails
                && "authorization_code".equals(resource.getGrantType());
    }
```

Can i make a pull request changing @ConditionalOnNotWebApplication
to @ConditionalOnProperty(value="spring.oauth2.client.grant-type", havingValue="client-credentials") ?
