### ISSUE TITLE
Config behavior changed when upgrading from from 1.2.x to 1.3.3

### ISSUE THREAD

**Issue by khoubyari** [spring-projects/spring-boot#5363]
There is a sample project here. Both branches below have been upgraded to 1.3.3 from 1.2.8

https://github.com/khoubyari/spring-boot-rest-example

The master branch is what I had to do in order to get configs to be picked up for "test" profile. I basically had to copy and paste everything from "default" profile section to "test" profile section in this file:
https://github.com/khoubyari/spring-boot-rest-example/blob/master/src/main/resources/application.yml

(if you run this, you will see the server starts on port 8090 which is the port specifically specified for "test" profile)

However in this branch:
https://github.com/khoubyari/spring-boot-rest-example/tree/upgrade-breaks-config

I kept the config the way it was all through my 1.2.x deployments. The "test" section used to inherit from the "default" section:
https://github.com/khoubyari/spring-boot-rest-example/blob/upgrade-breaks-config/src/main/resources/application.yml

(notice how brief the "test" profile section is)

However, in the master branch the "test" profile does not inherit the properties from "default". This can be seen right away by starting the app and it starts on the port "8080" even though the "default" profile specifies port "8090". In 1.2.x running with this same configuration the app always started on port "8090" since the default profile had specified this. It's not just the port, I can demonstrate this with all other configurations. 

If this is a behavior change in 1.3, I would have to copy-paste the "common" configurations into every profile and that would be a step back.

In all of the above when I say run it in "test" profile I mean something like `java -Dspring.profiles.active=test -jar target/spring-boot-rest-example-0.3.0.war`

**Comment by wilkinsona** [comment]
I haven't checked the behaviour on 1.2.x, but it looks like 1.3.x is working as designed to me. As [described in the documentation](http://docs.spring.io/spring-boot/docs/1.3.3.RELEASE/reference/htmlsingle/#boot-features-external-config-multi-profile-yaml), the `default` profile is only active when there are no other profiles active. When you run with `--spring.profiles.active=test` the `default` profile is no longer active so you lose all of its configuration.

If you want the configuration that's in the `default` profile to be used all of the time, then it shouldn't be profile-specific. Other profiles can then override this as necessary.

**Comment by khoubyari** [comment]
So the "cascading" behavior that was there all the way through 1.2.x versions was a bug? By simply changing the Spring Boot version to 1.2.x in the pom file, I can see that the configurations from "default" gets inherited by "test" unless "test" actually overrides them. We actually use this behavior extensively in our apps so that we don't have to copy and paste common configurations that do not change from profile to profile. This reduced the possibility of human error if one of those common configs changes because they all inherit it from "profile". This was a feature we were actually taking advantage of.

**Comment by wilkinsona** [comment]
The documentation for default profiles was improved in [this commit](https://github.com/spring-projects/spring-boot/commit/eb49f4bfec6ff5e66b50aa43905b452ae6a1c54d).

**Comment by wilkinsona** [comment]
@khoubyari You can still use the "cascading" behaviour. You just need to update your YAML so that all your default properties are not attached to any particular profile. This works for me with both 1.2.8.RELEASE and 1.3.3.RELEASE:

```yaml
### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring.jmx:
   enabled: false

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: spring-boot-rest-example
  version: 0.1
  description: boot-example default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

hotel.service:
  name: 'default profile:'
---
spring:
  profiles: test

spring.jpa:
    hibernate.ddl-auto: create-drop

hotel.service:
  name: 'test profile:'
```
