### ISSUE TITLE
Bind fails for nested yaml (list inside collections)

### ISSUE THREAD

**Issue by fzakaria** [spring-projects/spring-boot#5431]
```yaml
schools:
        - Meadow Glen
        - Forest Creek
        - Shady Grove
      libraries:
        - Joseph Hollingsworth Memorial
        - Andrew Keriman Memorial
```

The following fails at RelaxDataBinder#extendCollectionIfNecessary:341 with a NullPointerException
