### ISSUE TITLE
managment.security.enabled=false load Spring Security

### ISSUE THREAD

**Issue by marcelalburg** [spring-projects/spring-boot#5441]
Hello,

i've a project, what's not using spring security but if i set:

```
management:
  port: <int>
  context-path: /
  security:
    enabled: false  
```

i always get:

```
Caused by: java.lang.NoClassDefFoundError: org/springframework/security/config/http/SessionCreationPolicy
#011at org.springframework.boot.actuate.autoconfigure.ManagementServerProperties$Security.<init>(ManagementServerProperties.java:166)
```

if i remove  security.enabled: false - everything is working. But i guess, it's not the best solution. If i say please disable security, it should not load.

i'm using spring boot 1.3.3

Thanks
