### ISSUE TITLE
Better support for spring.profiles.active in yaml configuration

### ISSUE THREAD

**Issue by jgogstad** [spring-projects/spring-boot#5442]
Parsing of the current active profiles could be better:
Doesn't work:
```yaml
---
spring:
  profiles:
    active:
      - dev
      - healthcheck
```

Doesn't work:
```yaml
---
spring:
  profiles:
    active: dev, healthcheck
```

Works (notice the space missing after comma):
```yaml
---
spring:
  profiles:
    active: dev,healthcheck
```

**Comment by snicoll** [comment]
Good catch. That property is advertized as a String so it makes sense that the first example doesn't work (your IDE should warn you about that in theory). But we can do better I guess. 

Wen you say "doesn't work do you mean that it's trying to enable " healthcheck" instead of "healthcheck"?

**Comment by jgogstad** [comment]
Most likely. It fails with an error message that the property can't be found. 

Regarding the first example, I guess you're right. I like the yaml syntax for representing lists, and I find it logical to use for properties like this, but it will probably look wierd in a property file.

**Comment by eddumelendez** [comment]
I have submitted a PR. I tried to support the first scenario mentioned by @jgogstad 

```yaml
---
spring:
  profiles:
    active:
      - dev
      - healthcheck
```

But, in order to get the property we should access to `spring.profiles.active[0]` and `spring.profiles.active[1]` in the `propertySource`.
