### ISSUE TITLE
Overriding application.properties outside packaged jar in application.yml problem

### ISSUE THREAD

**Issue by nodje** [spring-projects/spring-boot#5844]
The problem occurs both for 1.3.3 and 1.4.0.M2

I'm using the `application.yml` format for app configuration.

While trying to put reusable default configuration in an external jar so that could be shared between apps, I stumble on the doc [boot-features-external-config-yaml-shortcomings](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml-shortcomings) section.
So I switched to an `application.properties` format. So far so good, but when I need to override theses settings in an application using `application.yml` it ONLY works if the overriding settings are put in the profile section of the `application.yml`.

this works:
```
---
spring:
    profiles: dev
app:
    metrics:
        logs:
            enabled: true
```
this doesn't:
```
app:
    metrics:
        logs:
            enabled: true
---
spring:
    profiles: dev
```

hope this is clear. 
Basically the second section should work so that the default for all profiles could be locally override on a per profile basis.

**Comment by snicoll** [comment]
The shortcomings section has no link to what you're describing here as far as I can see. You can load `application.yml` from the same locations as `application.properties` and with the same feature. That section states that if you are using `@PropertySource` you can't use it with yaml files. That's not what you're doing, are you?

**Comment by nodje** [comment]
True, the section I indicated is not directly linked to what I'm describing.
But I've been experimenting loading an `application.yml` from an external jar without success, also without success trying with `@PropertySource("commons.yml")` so I guess I associated the two problem as being due to this limitation.
Anyway I switched back to the `.properties` format, which is working, but with the limitation I indicated.

**Comment by wilkinsona** [comment]
@nodje I'm not sure that I understand your description of the behaviour, or what the problem is. Can you please provide a small sample with some tests that illustrate the problem?

**Comment by nodje** [comment]
It'd be difficult for me to provide it in the coming days. I'll try though if needed.
To reiterate on the problem:
Structure:
```
common.jar
\application.properties
   app.metrics.log.enable=false
```
```
main-application.war -->dependency common.jar
\application.yml
```
I need to override the `app.metrics.log.enabled` in my main app's `application.yml`
this works:
```
---
spring:
    profiles: dev
app:
    metrics:
        logs:
            enabled: true
```
this doesn't:
```
app:
    metrics:
        logs:
            enabled: true
---
spring:
    profiles: dev
```
Only the profile section of the `application.yml` take into account the overriding property, not the global/default section
