### ISSUE TITLE
Cannot resolve gzip static resource at same time with versioned static resource

### ISSUE THREAD

**Issue by kazuki43zoo** [spring-projects/spring-boot#5876]
## Description

I tried as following settings:

* `src/main/resources/application.yml`

```yaml
spring:
    resources:
        chain:
            gzipped: true
            strategy:
                content:
                    enabled: true
```

I will expect to be outputted  the「`Content-Encoding: gzip`」 as response header.
However, actually it does not outputted.

## Possible solutions
I think the `GzipResourceResolver` should be applied before than the `VersionResourceResolver`. 
What do you think ?

## Affected version/s
* 1.4.0-BUILD-SNAPSHOT (at 2016-05-05)
