### ISSUE TITLE
Environment variables in yaml lists not substituted

### ISSUE THREAD

**Issue by jrw972** [spring-projects/spring-boot#5904]
In version 1.3.3:

Suppose the USER environment variable is set to Bob and application.yml contains:

```yaml
foo:
  key1: ${USER}
  key2:
    - ${USER}
```

Accessing the property foo.key1 will yield Bob.
Accessing the property foo.key2[0] will yield ${USER}.
