### ISSUE TITLE
EL statements are not interpreted in YAML file

### ISSUE THREAD

**Issue by mikert** [spring-projects/spring-boot#5988]
I added Consul support [using this tutorial](http://cloud.spring.io/spring-cloud-consul/spring-cloud-consul.html), and the EL statements were not being evaluated. This is what my configuration looks like:

```
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: ${management.contextPath}/health
        healthCheckInterval: 15s
  application:
    name: my-service
```

The `healthCheckPath` branch is going to Consul as `$management.contextPath}/health`, not as the evaluated version of that statement.

It's a really simple app with one configuration bean and one controller. I'm not customizing anything in how the properties are loaded; it's just application.yml in src/main/resources.
