### ISSUE TITLE
Support for database migration as an app

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#6035]
It is a common requirement to be able to run database migrations as a different user than the one that runs the main app. We already support that by allowing a separate `DataSource` to be configured for Flyway (and possibly Liquibase as well). We don't really have a convenient way to run that as a separate process though, which is kind of part of the same requirement (so that the admin user credentials can stay separate). Ideally, probably being able to run the application JAR with a switch of some sort would be the best way to do it. You can probably already do something with `PropertiesLauncher` but it's not very obvious, so we need at least a proof of concept and some documentation.

See also #787.

**Comment by dsyer** [comment]
cc @robharrop

**Comment by dsyer** [comment]
This worked for me in the stock spring-boot-sample-flyway:

application.yml:
```
spring:
  datasource:
    url: jdbc:h2:./target/testdb
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  h2:
    console:
      enabled: true

flyway:
  enabled: false

---
spring:
  profiles: admin
  main:
    web-environment: false
flyway:
  enabled: true
  url: jdbc:h2:./target/testdb
  user: sa
  password: 
```

Then the test works (I also added some code to delete the database files in between tests), and you can run the jar with `--spring.profiles.active=admin` to initialize the database.

I think that's pretty easy to extrapolate to other databases, etc. We could put it in the user guide.
