### ISSUE TITLE
Tomcat acceptCount

### ISSUE THREAD

**Issue by peterdnight** [spring-projects/spring-boot#6433]
Enhancement:
Add additional tomcat parameter: accept-count. This is incredibly useful parameter when implementing throttles to protect resources from heavy activity spikes. It is the best friend of max-threads which is already supported. Otherwise you end up with hundreds of sockets sitting in blocked state, rather then sending a 503 - try again later.

```
server:
  port: 8080
  tomcat:
    max-threads: 10
    accept-count: notImplemented
```
