### ISSUE TITLE
dataSourceClassName can not be configured for HikariCP

### ISSUE THREAD

**Issue by elDracoRus** [spring-projects/spring-boot#6568]
In Spring Boot 1.4 configuration of `data-source-class-name` property for HikariCP results in runtime exception. Example configuration:
```yml
spring:
  datasource:
    url: jdbc:postgresql://localhost/database-name
    hikari:
      data-source-class-name: org.postgresql.ds.PGSimpleDataSource
```
Then getting exception like this on application startup:
```
Caused by: java.lang.IllegalArgumentException: cannot use driverClassName and dataSourceClassName together.
	at com.zaxxer.hikari.HikariConfig.validate(HikariConfig.java:770) ~[HikariCP-2.4.7.jar:na]
```
The reason of such behavior is in `org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration` which unconditionally configures `driverClassName` for any dataSource in `createDataSource` method.
