### ISSUE TITLE
Make JndiDataSourceAutoConfiguration ConditionalOnJndi

### ISSUE THREAD

**Issue by jhitt25** [spring-projects/spring-boot#6913]
I am creating a project that can be run via embedded Tomcat or in a standalone Tomcat container.  Datasource configuration in the standalone installation is done via JNDI so certain applications can share connection pools, but embedded deployments are responsible for their own data sources.

Here is the `application.yml` excerpt i am attempting to use:

```yaml
datasource.jndi-name: java:comp/env/jdbc/oracle/my-app
datasource.url: jdbc:oracle:thin:@db-server.mydomain:1521:my-db
datasource.driver-class-name: oracle.jdbc.OracleDriver
datasource.username: my_app
datasource.password: my_password
```

My assumption was that since `JndiDataSourceAutoConfiguration` runs first, JNDI would be looked for and configured when present.  If a JNDI context was not available, `DataSourceAutoConfiguration` would have configuration data available to make the connection itself.  However, `JndiDataSourceAutoConfiguration` is not conditional on JNDI being available.  As a result, the configuration listed above will result in an error when attempting to run embedded because there is no JNDI InitialContext.

Simply adding `@ConditionalOnJndi` to `JndiDataSourceAutoConfiguration` would solve this problem, allowing JNDI configuration with internal fallback.  This also seems to make logical sense.  Why would we attempt `DataSource` configuration via JNDI without first verifying that JNDI is indeed available?
