### ISSUE TITLE
spring.mvc.locale is ignored

### ISSUE THREAD

**Issue by ufoscout** [spring-projects/spring-boot#6990]
After upgrading from spring-boot 1.3.7 to 1.4.1 the spring.mvc.locale value in the application.yml file is not taken into account any more.
This is our web configuration:

```
spring:
    thymeleaf:
        cache: false 
        suffix: ''
        prefix: file:i18nBundles/
        encoding: UTF-8
        mode: LEGACYHTML5        
    mvc:
        locale: es
```

With this configuration, spring-boot 1.3.7 uses the Spanish bundle, but 1.4.1 always uses the English one. We don't know exactly if the issue is linked to thymeleaf or spring-boot or spring-mvc tough.
We tested it with both Tomcat and Jetty embedded and the behaviour is the same.
