### ISSUE TITLE
RandomValuePropertySource returns a different random value each time a random property is referenced

### ISSUE THREAD

**Issue by whboyd** [spring-projects/spring-boot#7009]
Currently, randomized configuration properties produce new randomized values each time they are referenced within config.

For example, with the following yaml configuration:
```
my:
    random: ${random.value}
another:
    property: ${my.random}
```

my.random and another.property will be two different randomized values when pulled in via @Value, for example.

Even using the same property twice will result in two different values:
```
@Value("${my.random}")
String random1;
@Value("${my.random}")
String random2;
```

In the above case, random1 will not equal random2.

It seems like it would be useful and more consistent for the my.random property to be randomized but reflect the same random value no matter where, how, or how many times it is referenced.

**Comment by whboyd** [comment]
One possible strategy that I thought of would be to store the values generated by RandomValuePropertySource (perhaps in a map within RandomValuePropertySource itself). However, this would require a change to the expressions used to reference random values, perhaps adding some way to arbitrarily "name" random values such that the named value would remain consistent, for example:
```
my:
    random:
       one: ${random.value.one}
       two: ${random.value.one}
       three: ${random.value.another}
```
In this case, my.random.one would be equal to my.random.two but not my.random.three

I'm curious as to whether anyone has any ideas on a more elegant solution. I'm willing to put together a pull request following some discussion.
