### ISSUE TITLE
Property in yaml file does not override default values

### ISSUE THREAD

**Issue by ralscha** [spring-projects/spring-boot#7015]
Spring Boot 1.4.1

If an application tries to set the static-locations property like this, it will not override the default values. Boot will prepend the two values from the yaml file to the default list. 

``` yml
spring:
  resources:
    static-locations: 
      - file:client/
      - classpath:/static/
```

The `staticLocations` field in the `ResourceProperties` class (can be seen in the `WebMvcAutoConfiguration` class) contains these values: 
`[file:client/, classpath:/static/, classpath:/resources/, classpath:/static/, classpath:/public/]`

But if the yaml looks like this

``` yml
spring:
  resources:
    static-locations: file:client/,classpath:/static/
```

`staticLocations` contains these values
`[file:client/, classpath:/static/]`

Not sure if this a bug or the indented behavior.

**Comment by philwebb** [comment]
This is an unfortunate side effect of the way that YAML lists are mapped. I consider it a bug, but it might not be something we can fix until 2.0.

**Comment by mbhave** [comment]
Fixed by the new binder work. Test case that proves this: https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/test/java/org/springframework/boot/context/properties/bind/CollectionBinderTests.java#L168

**Comment by viruscamp** [comment]
I have met an error related to this issue in spring-boot 1.5.4:
application.yml
```yml
spring:
  resources:
    staticLocations:
      - /
      - classpath:/static1/ # added
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
```
Then I got the error
```
Binding to target org.springframework.boot.autoconfigure.web.ResourceProperties@7e1a1da6 failed:

    Property: spring.resources.staticLocations
    Value: /,classpath:/static1/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,null
    Reason: Property 'staticLocations' threw exception; nested exception is java.lang.NullPointerException
```
