### ISSUE TITLE
Add array support for spring.profiles

### ISSUE THREAD

**Issue by nathansgreen** [spring-projects/spring-boot#7397]
I would like to see `spring.profiles` support YAML arrays in addition to the existing comma-delimited string behavior. So the following:

```YAML
spring:
  profiles:
    - default
    - develop
---
spring.profiles:
  - default
  - develop
---
spring.profiles: [default, develop]
---
spring.profiles: 'default,develop'  # only this line actually works
```
should all be equivalent. This is related to #6995. I'm not totally sure, but I think the PR for that issue (#7175) needs to be merged before this can move forward.
