### ISSUE TITLE
YamlPropertiesFactoryBean getObject() ignores the active profile data and returns incorrect profile's data

### ISSUE THREAD

**Issue by edward0001** [spring-projects/spring-boot#7429]
I am experiencing an issue, using **YamlPropertiesFactoryBean** to get the Properties object. 
I have 3 profiles configured in the application.yaml file. 
One of them is set as the active (profile2).

**Server.java**
`YamlPropertiesFactoryBean yaml = new  YamlPropertiesFactoryBean();`
`yaml.setResources(new ClassPathResource("/config/application.yaml"));`
`yaml.getObject();`

**application.yaml** file
```
spring:
  profiles:
    active: profile2
---
spring:
  profiles: profile1
dev:
  datasource:
    url:  jdbcUrl...   
    username: profile1DevUsername
    password: profile1DevPassword
prod:
  datasource:
    url: jdbcUrl...
    username: profile1ProdUsername
    password: profile1ProdPassword
---
spring:
  profiles: profile2
dev:
  datasource:
    url: jdbcUrl
    username: profile2DevUsername
    password: profile2DevPassword
prod:
  datasource:
    url: jdbcUrl
    username: profile2ProdUsername
    password: profile2ProdPassword
---
spring:
  profiles: profile3
dev:
  datasource:
    url: jdbcUrl
    username: profile3DevUsername
    password: profile3DevPassword
prod:
  datasource:
    url: jdbcUrl
    username: profile3ProdUsername
    password: profile3ProdPassword

```
Though the active profile has been set to **profile2**, **yaml.getObject()** returns me the data of the last profile, specified in the file. (in this case it is **profile3**, but this is true for profile2, when it is in the end of the list).
The rest of the data, placed after profiles (in the global scope) is being displayed correctly. 

P.S. The same thing is about YamlMapFactoryBean
