### ISSUE TITLE
logging.pattern.console doesn't work with log4j2

### ISSUE THREAD

**Issue by searhiy** [spring-projects/spring-boot#7757]
This [issue](https://github.com/spring-projects/spring-boot/issues/7719) fixed bug with environment variable. But I found that colors don't work for log4j2 logger

application.yaml

```
logging:
  file: "logs/dev_app.log"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-8level) ${PID} --- [%-21thread] %clr(%-80.80logger{80}){cyan} : %m%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.apache.tomcat: INFO
    org.apache.catalina: INFO

```

pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.3.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>logback-classic</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>


</project>
```

And console contains following message:

`ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.`

That works with LogBack.
