### ISSUE TITLE
Non-default Thymeleaf templates location causes app restart on change, instead of reload

### ISSUE THREAD

**Issue by JetForMe** [spring-projects/spring-boot#7878]
I think this is a bug, but I may be overlooking some configuration aspect. This is in reference to my Stackoverflow [question](http://stackoverflow.com/questions/41455936/one-gradle-thymeleaf-project-reloads-on-resource-change-the-other-relaunches).

Everything works fine if the Thymeleaf templates are in the default location (i.e. `src/main/resources/templates`). But if they are somewhere else (e.g. `src/main/resources/my-app/templates`, and configured in an `application.yml` file loaded explicitly at app launch with a call like `System.setProperty("spring.config.name", "tools-server");`), then Spring Boot Devtools does notice the change, but it causes a restart of the application, rather than simply reloading the changed Thymeleaf template.

Hmm, one note. I configured Thymeleaf like this:

```
spring:
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/tools-server/templates/    # Trailing / mandatory
```

It still seems to find my templates in the source tree, and not in the built classpath, but it restarts the app, rather than reloading the changed template. I run with `gradle bootRun`.
