### ISSUE TITLE
h2 not run schema.sql when start

### ISSUE THREAD

**Issue by Dreampie** [spring-projects/spring-boot#7933]
```yml
spring:
    profiles: dev
    datasource:
      schema: classpath:db/schema.sql
      url: jdbc:h2:~/h2/test;MODE=MySql
      driver-class-name: org.h2.Driver
      username: sa
      initialize: true
    h2:
      console:
        enabled: true
```

```sql
CREATE TABLE alc_city (
  id          INT PRIMARY KEY AUTO_INCREMENT,
  name        VARCHAR,
  state       VARCHAR,
  country     VARCHAR,
  delete_able INT,
  deleted_at  TIMESTAMP
);

INSERT INTO alc_city (name, state, country, delete_able, deleted_at)
VALUES ('San Francisco', 'CA', 'US', 1, '2016-10-10 10:11:20');
```

![image](https://cloud.githubusercontent.com/assets/3667080/21794683/81c723c4-d737-11e6-8486-72ff48ac0c27.png)
