### ISSUE TITLE
where active profiles are specified in config files, YAML profile negation subdocument is pulled in early

### ISSUE THREAD

**Issue by mbenson** [spring-projects/spring-boot#8191]
Where an application is started with the expectation that active profiles will be pulled in via config, the following config file will result in unexpected behavior:

```
spring:
  profiles:
    active:
      - foo

sbyaml:
  message: default message

---
spring.profiles: "!foo"

sbyaml:
  message: some other message
```

Attaching a runnable sample app that demonstrates the issue.
[sbyaml.tar.gz](https://github.com/spring-projects/spring-boot/files/751071/sbyaml.tar.gz)
