### ISSUE TITLE
endpoints.configprops.keys-to-sanitize not working with array objects

### ISSUE THREAD

**Issue by droram** [spring-projects/spring-boot#8197]
I am using spring-boot-actuator-1.4.2.

I have a configuration having an array of objects, containing a configuration of a pool of connections. When I try to hide a property named "pass", but nothing happens when I set this property:

```yaml
endpoints:
  configprops:
    keys-to-sanitize: pass
```

My example configuration:

```yaml
app:
  data:
    pool:
      maxTotal: 10
      maxWaitMillis: 30000
      
  poolData:
    - poolName: poolSPAIN
      user: user_spain
      pass: the_spain_pass
      domain: mydomain.es
      url: https://exampleurl.es
	  
    - poolName: poolUK
      user: user_uk
      pass: the_uk_pass
      domain: mydomain.uk
      ewsUrl: https://otherurl.uk
```

I think that is needed an improvement in the method `private Map<String, Object> sanitize(String prefix, Map<String, Object> map)` of class: `ConfigurationPropertiesReportEndpoint`, or an improvement in the method `public Object sanitize(String key, Object value)` of class: `Sanitizer` (package: `org.springframework.boot.actuate.endpoint`), because it seems that they don't consider that an object could be an array.

**Comment by snicoll** [comment]
That's not you define an array in YAML, the proper configuration is:

```yaml
endpoints:
  configprops:
      keys-to-sanitize:
         - pass
```

Your configurtion is not indented so it's hard to read. If I've missed something, feel free to reopen with a sample that demonstrates the issue.
