### ISSUE TITLE
Problem with flatten map of VCAP_SERVICES of CloudFoundry

### ISSUE THREAD

**Issue by tvluong051** [spring-projects/spring-boot#8313]
We are working on a Spring Boot project which is deployed on CloudFoundry cloud. So we are using Spring cloud starter project.
Currently, I had a _manifest.yml_ file to describe our deployment on CF.
```
applications:
  - name: app-name
    services:
      - service1 #service 1 name
      - service2 #service 2 name
```
and in _application.yml_ of our Spring project, we need to access to **service1** credentials through VCAP_SERVICES:
```
service1:
  credentials:
    username: ${vcap.services.service1.credentials.username}
    pwd: ${vcap.services.service1.credentials.password}
```
Until now, everything works smoothly.

The problem is when we want to deploy our application in different environments (dev, integration, prod), the services names are all different from environment to another (like **service1** becomes **service1-int**, **service1-prod**, etc...) so our code does not work anymore because the properties placeholders are based on service name.

So do we have any solution to access to CloudFoundry's VCAP_SERVICES without knowing beforehand services names? I'm thinking about a propety in **vcap.service...** flatten map which is based on services types and not services names (somthing like **vcap.service.service_type[0].username**).

Thank you for your response.

**Comment by spencergibb** [comment]
Profiles?

**Comment by tvluong051** [comment]
To put it simple, our service name is only defined at deployment day and it clearly not a good idea to change your _application.yml_ at that time. So you can't know beforehand the service name in different environments then even though using Spring profiles, the problem persists.

**Comment by spencergibb** [comment]
Spring Boot supports external configuration, application.yml, env vars and system properties.

**Comment by tvluong051** [comment]
Could you please give more details how theses features could solve the problem?
In the case that I mentioned earlier, the credentials fields is generated by CF so harding code theirs values is not an option. And I really don't want to mess with external conf because we do not really have control on which architecture is used in Cloud platform. We just want all the source code packaged in one jar then push it to CF.

**Comment by wilkinsona** [comment]
You don't need to use external configuration if you don't want to. It sounds like your service names follow a naming convention depending on the deployment environment. You could use profile-specific configuration the follows the same convention. For example, in an `application-prod.yml` file you could have:

```
service1:
  credentials:
    username: ${vcap.services.service1-prod.credentials.username}
    pwd: ${vcap.services.service1-prod.credentials.password}
```

And in `application-int.yml` you could have:

```
service1:
  credentials:
    username: ${vcap.services.service1-int.credentials.username}
    pwd: ${vcap.services.service1-int.credentials.password}
```
