### ISSUE TITLE
management.security.roles cannot be set to a single role containing commas

### ISSUE THREAD

**Issue by jonfreedman** [spring-projects/spring-boot#8314]
I have a spring-boot application which sits behind an in-house servlet filter which does kerberos authentication and exposes LDAP groups via HttpServletRequest#isUserInRole

I want to use the following in my application.yaml
```
management:
  security:
    roles: CN=some-group,OU=somewhere,OU=in,OU=ldap,DC=example,DC=com
```
but this results in checking for membership of the following
 * CN=some-group
 * ROLE_CN=some-group
 * OU=somewhere
 * ROLE_OU=somewhere
 * etc.

**Comment by wilkinsona** [comment]
You need to make it clear that you're providing a single item rather than multiple comma-separated items:

```
management:
  security:
    roles:
    - CN=some-group,OU=somewhere,OU=in,OU=ldap,DC=example,DC=com
```
