### ISSUE TITLE
Multi-profile YAML files with negated profile not working.

### ISSUE THREAD

**Issue by shollander** [spring-projects/spring-boot#8318]
According to the [documentation](http://docs.spring.io/spring-boot/docs/1.5.1.RELEASE/reference/htmlsingle/#boot-features-external-config-multi-profile-yaml), profiles can be negated to exclude sections of a YAML file. For example if the following is the contents of application.yml:
```
prop:
  other: false
---
spring:
  profiles: '!something'
test:
  property: true
---  
```

The property `test.property` should not be set when the `something` profile is active. This does not work for me. I have created an example project and unit test to demonstrate: https://github.com/shollander/test-sb-properties/blob/master/src/test/java/TestPropertiesTest.java
