### ISSUE TITLE
Support binding of map key with dots

### ISSUE THREAD

**Issue by dantesun** [spring-projects/spring-boot#8326]
Suppose I have an Bean like this:

```java
@ConfigurationProperties("foo")
public class FooBean {
    Map<String, Item> items = new HashMap<>();
    public Map<String, Item> getItems() {
      return items;
    }
}
public class Item {
    private String name;
    private int value;
    ///... bean method getter and setter ignored
}
```

And the corresponding .yml file 
```yaml
foo:
  items:
    key.1:
      name: key1
      value: 13
    key.2:
      name: key2
      value: 42
```
org.springframework.boot.bind.RelaxedDataBinder#modifyProperties will resolve the property name as 'items[key].1[name]' and failed to binding values to bean property "items".

**Comment by snicoll** [comment]
@philwebb looks like an additional use case to take into account here (YAML doesn't tell us if the current element is a `Map` but we could derive that from the `metadata`. Also this gives more context to the uniform property definition that we are currently building.

**Comment by mbhave** [comment]
@dantesun You can achieve this by doing:
```yaml
foo:
  items:
    '[key.1]':
      name: key1
      value: 13
    '[key.2]':
      name: key2
      value: 42
```
