### ISSUE TITLE
Add --logging.pattern.dateformat to only change that part of the logging pattern

### ISSUE THREAD

**Issue by hdohlmann** [spring-projects/spring-boot#8506]
Currently, when we need to change the date-part of the logging pattern, we need to copy the pattern from defaults.xml and overwrite both console and file pattern, like this:
```
logging:
  pattern:
    console: '%clr(%d{"yyyy-MM-dd''T''HH:mm:ss,SSSZ"}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
    file: '%d{"yyyy-MM-dd''T''HH:mm:ss,SSSZ"} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n%wEx'
```

The suggestion is to introduce `LOG_DATEFORMAT_PATTERN`, `logging.pattern.dateformat`or some other well-chosen names for these, that allow us to just provide that piece of the logging pattern. Example:
```
logging:
  pattern:
    dateformat: "yyyy-MM-dd'T'hh:mm:ss,SSSZ"
