### ISSUE TITLE
Enhancement Request: configuring RabbitMQ to use SASL External mechanism using externalized configuration

### ISSUE THREAD

**Issue by behrangsa** [spring-projects/spring-boot#8561]
Sometimes in order to connect to RabbitMQ over SSL, the SASL External mechanism is used (see [1](https://www.rabbitmq.com/authentication.html), [2](https://www.rabbitmq.com/plugins.html), [3](https://github.com/rabbitmq/rabbitmq-auth-mechanism-ssl/blob/rabbitmq_v3_6_6/README.md)).

This mechanism:

> Authenticates the user, obtaining the username from the client's SSL certificate. The user's password is not checked.
> 
> In order to use this mechanism the client must connect over SSL, and present a client certificate.
> 
> The mechanism must also be enabled in RabbitMQ's configuration file - see TLS Authentication guide for more details, or in short, ensure that the 'rabbit' section of your configuration contains:
> 

At the moment it is not possible to set Spring to use this mechanism using externalized configuration and this should be configured using custom code. For example:

```java
connectionFactory.getRabbitConnectionFactory().setSaslConfig(DefaultSaslConfig.EXTERNAL);
```

Ideally it should be possible to configure this next to other RabbitMQ properties in the externalized configuration file:

```yaml
spring:
  rabbitmq:
    host: example.com
    port: 5671
    saslConfig: external  # <-- New configuration option (see com.rabbitmq.client.DefaultSaslConfig for all options (i.e. `external` and `plain`))
    ssl:
      enabled: true
      key-store: file:/example.p12
      key-store-password: example
      trust-store: file:/example.jks
      trust-store-password: example      
    virtual-host: /Example
```
