### ISSUE TITLE
management.security.roles cannot be set to multiple roles containing commas

### ISSUE THREAD

**Issue by jonfreedman** [spring-projects/spring-boot#8602]
Following on from issue #8314 if I attempt to set management.security.roles to an array using the config below I get an `UnsupportedOperationException` thrown from `java.util.AbstractList#add` for the second element

```
management:
  context-path: /management
  security:
    enabled: true
    roles:
    - CN=some-group,OU=somewhere,OU=in,OU=ldap,DC=example,DC=com
    - CN=some-other-group,OU=somewhere,OU=in,OU=ldap,DC=example,DC=com
```

I have updated https://github.com/jonfreedman/spring-boot-management-demo to illustrate
