### ISSUE TITLE
Spring does not check for missing placeholders in yml configuration files

### ISSUE THREAD

**Issue by gstaykov** [spring-projects/spring-boot#8693]
Spring does not check for missing placeholders in yml configuration files. For example if you have the following application.yml:

```
spring:
  application:
    name: example
  datasource:
    url: jdbc:mysql://locahost:3306/customer_db?useSSL=false
    username: root
    password: ${DB_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
    ...
```

and you don't have DB_PASSWORD as environment variable Spring will set spring.datasource.password = "${DB_PASSWORD}"   I think that in this situation the Spring should throw some `RuntimeException` with "Could not resolve placeholder 'spring.datasource.password' " as in `@Value` This is very important because when I use auto-configuration for the connection to the DB the application is starting successfully even that the connection to the DB is failing because of wrong `spring.datasource.password`. I think that it would be better if the application fail to start in this case.
