### ISSUE TITLE
1.1.0.BUILD-SNAPSHOT: Spring Data JPA applications fail to start when hibernate.dialect is not set.

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-boot#909]
We're not able to start our Spring Data JPA application using 1.1.0.BUILD-SNAPSHOT using this configuration while the same configuration works for 1.0.2-RELEASE

```
spring:
  datasource:
    url: jdbc:postgresql://localhost/project_development
    username: pivotal
    password:
    driverClassName: org.postgresql.Driver
```

```
 Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
```
