### ISSUE TITLE
Random properties generation not properly evaluated

### ISSUE THREAD

**Issue by rLitto** [spring-projects/spring-boot#9130]
If using spring RandomValuePropertySource [https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-random-values] referencing a values previously defined with a random value generates a new random value instead of the already generated one

`application.yml`	configuration
```
values:
  value1: ${random.int}
  value2: ${values.value1}
  value3: ${values.value2}
```
provides three different values
`http://localhost/env `actuator endpoint example result:
```
applicationConfig: [classpath:/application.yml]: {
...
values.value1: "-1492876808",
values.value2: "1652707893",
values.value3: "1156107610",
}
```
