### ISSUE TITLE
No and Yes keywords in yaml files

### ISSUE THREAD

**Issue by lalib** [spring-projects/spring-boot#9186]
In yaml file No and Yes values are not allowed to use. They are converted to False and True automaticly. For example:

```
countryValues:
    TR: 10
    NO: 5
    FR: 4

```

If i do not put quatos to the country codes, the result becomes:

```
countryValues:
    TR: 10
    false: 5
    FR: 4

```

The valid version is:

```
countryValues:
    'TR': 10
    'NO': 5
    'FR': 4

```

Is it intended or a bug?
