### ISSUE TITLE
spring.database.username defaults to sa at all times

### ISSUE THREAD

**Issue by nebhale** [spring-projects/spring-boot#94]
Currently the value of spring.database.username defaults to `sa` at all times.  If you choose to use a different database that doesn't require a username (Postgres for example, can authenticate by process owner), there isn't a great way to indicate that you want to use _no_ username.

The following fails with `FATAL: rolde "sa" does not exist` which stands to reason.

``` yaml

---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/test
```

The following fails with `FATAL: no PostgreSQL username specified in startup packet` which again matches expectations because it's not that the username is empty, it's that it shouldn't be set at all.

``` yaml

---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/test
    username:
```

A workaround at the moment is to use the `$USER` or `user.name`.

``` yaml

---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/test
    username: ${user.name}
```

This work around isn't ideal and I think that boot shouldn't use the `sa` default if it hasn't also defaulted the url.  Arguably, the defaulting of `org.h2.Driver` shouldn't happen for the same reasons.
