### ISSUE TITLE
failed to load elasticsearch nodes with docker container.

### ISSUE THREAD

**Issue by iquirino88** [spring-projects/spring-boot#9647]
Hi guys! 

Im trying to connect with elasticsearch using spring boot version 2.0.0.M2 with spring-boot-starter-data-elasticsearch and elasticsearch 5.4.3 via docker container.

When i start the application always raise this exception failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available.

My application.yml config:
```
spring:
    application:
        name: elastic-demo
    data:
      elasticsearch:
        cluster-nodes: localhost:9300
        cluster-name: docker-cluster
```
docker container cmd:

```
docker run -p 9200:9200 -p 9300:9300 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.4.3
```

Please can anybody help me?

![image](https://user-images.githubusercontent.com/3419140/27752764-10a95b04-5db9-11e7-81c1-5afc3173dcfb.png)
